.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_8016ECA0

dlabel D_8016ECA0
    /* F1D90 8016ECA0 032D1821 */ .word 0x032D1821
    /* F1D94 8016ECA4 C44A0000 */ .word 0xC44A0000
    /* F1D98 8016ECA8 C4440008 */ .word 0xC4440008
    /* F1D9C 8016ECAC 25EFF9C0 */ .word 0x25EFF9C0
    /* F1DA0 8016ECB0 46025401 */ .word 0x46025401
    /* F1DA4 8016ECB4 01CF1821 */ .word 0x01CF1821
    /* F1DA8 8016ECB8 460C2481 */ .word 0x460C2481
    /* F1DAC 8016ECBC 46108202 */ .word 0x46108202
enddlabel D_8016ECA0
