.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_80093CE0

dlabel D_80093CE0
    /* 948E0 80093CE0 AC6F0028 */ .word 0xAC6F0028
    /* 948E4 80093CE4 8E430000 */ .word 0x8E430000
    /* 948E8 80093CE8 8C790028 */ .word 0x8C790028
    /* 948EC 80093CEC 8478002C */ .word 0x8478002C
enddlabel D_80093CE0
