.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_8009AD60

dlabel D_8009AD60
    /* 9B960 8009AD60 24630001 */ .word 0x24630001
    /* 9B964 8009AD64 146BFFFB */ .word 0x146BFFFB
    /* 9B968 8009AD68 24420002 */ .word 0x24420002
    /* 9B96C 8009AD6C 240B0080 */ .word 0x240B0080
enddlabel D_8009AD60
