.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008FC20, 0x8

glabel func_8008FC20
    jr $ra
    nop
endlabel func_8008FC20

nonmatching D_8008FC28, 0x1C

glabel D_8008FC28
    jr $ra
    nop
  .L8008FC2C:
    jr $ra
    nop
endlabel D_8008FC28

nonmatching D_8008FC44, 0xC

glabel D_8008FC44
    jr $ra
    nop
endlabel D_8008FC44
