.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008D750, 0x10

glabel func_8008D750
    /* 8E350 8008D750 ACA00004 */  sw         $zero, 0x4($a1)
    /* 8E354 8008D754 ACA00008 */  sw         $zero, 0x8($a1)
    /* 8E358 8008D758 8E0D000C */  lw         $t5, 0xC($s0)
    /* 8E35C 8008D75C 24070510 */  addiu      $a3, $zero, 0x510
endlabel func_8008D750
