.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008D940, 0x18

glabel func_8008D940
    /* 8E540 8008D940 0C0236C0 */  jal        func_8008DB00
    /* 8E544 8008D944 8FA40040 */   lw        $a0, 0x40($sp)
    /* 8E548 8008D948 960E001A */  lhu        $t6, 0x1A($s0)
    /* 8E54C 8008D94C 31D8EFFF */  andi       $t8, $t6, 0xEFFF
    /* 8E550 8008D950 A618001A */  sh         $t8, 0x1A($s0)
    /* 8E554 8008D954 3303FFFF */  andi       $v1, $t8, 0xFFFF
endlabel func_8008D940

nonmatching D_8008D958, 0x4

glabel D_8008D958
    /* 8E558 8008D958 30790200 */  andi       $t9, $v1, 0x200
endlabel D_8008D958

nonmatching D_8008D95C, 0xC0

glabel D_8008D95C
    /* 8E55C 8008D95C 1320001C */  beqz       $t9, .L8008D9D0
    /* 8E560 8008D960 8FA50034 */   lw        $a1, 0x34($sp)
    /* 8E564 8008D964 8FA60034 */  lw         $a2, 0x34($sp)
    /* 8E568 8008D968 24C60020 */  addiu      $a2, $a2, 0x20
    /* 8E56C 8008D96C 00C02025 */  or         $a0, $a2, $zero
    /* 8E570 8008D970 0C023B6E */  jal        func_8008EDB8
    /* 8E574 8008D974 AFA60024 */   sw        $a2, 0x24($sp)
    /* 8E578 8008D978 9603001A */  lhu        $v1, 0x1A($s0)
    /* 8E57C 8008D97C 8FA60024 */  lw         $a2, 0x24($sp)
    /* 8E580 8008D980 30694000 */  andi       $t1, $v1, 0x4000
    /* 8E584 8008D984 11200006 */  beqz       $t1, .L8008D9A0
    /* 8E588 8008D988 00C02025 */   or        $a0, $a2, $zero
    /* 8E58C 8008D98C 44800000 */  mtc1       $zero, $fv0
    /* 8E590 8008D990 00000000 */  nop
    /* 8E594 8008D994 E4C00014 */  swc1       $fv0, 0x14($a2)
    /* 8E598 8008D998 E4C00010 */  swc1       $fv0, 0x10($a2)
    /* 8E59C 8008D99C 9603001A */  lhu        $v1, 0x1A($s0)
  .L8008D9A0:
    /* 8E5A0 8008D9A0 306A0100 */  andi       $t2, $v1, 0x100
    /* 8E5A4 8008D9A4 11400004 */  beqz       $t2, .L8008D9B8
    /* 8E5A8 8008D9A8 8FA50038 */   lw        $a1, 0x38($sp)
    /* 8E5AC 8008D9AC 0C023CF6 */  jal        func_8008F3D8
    /* 8E5B0 8008D9B0 AFA60024 */   sw        $a2, 0x24($sp)
    /* 8E5B4 8008D9B4 8FA60024 */  lw         $a2, 0x24($sp)
  .L8008D9B8:
    /* 8E5B8 8008D9B8 02002025 */  or         $a0, $s0, $zero
    /* 8E5BC 8008D9BC 0C0237A0 */  jal        func_8008DE80
    /* 8E5C0 8008D9C0 8FA50034 */   lw        $a1, 0x34($sp)
    /* 8E5C4 8008D9C4 8FA80038 */  lw         $t0, 0x38($sp)
    /* 8E5C8 8008D9C8 10000006 */  b          .L8008D9E4
    /* 8E5CC 8008D9CC AD020038 */   sw        $v0, 0x38($t0)
  .L8008D9D0:
    /* 8E5D0 8008D9D0 02002025 */  or         $a0, $s0, $zero
    /* 8E5D4 8008D9D4 0C0237A0 */  jal        func_8008DE80
    /* 8E5D8 8008D9D8 24A60020 */   addiu     $a2, $a1, 0x20
    /* 8E5DC 8008D9DC 8FAD0038 */  lw         $t5, 0x38($sp)
    /* 8E5E0 8008D9E0 ADA20038 */  sw         $v0, 0x38($t5)
  .L8008D9E4:
    /* 8E5E4 8008D9E4 960B001A */  lhu        $t3, 0x1A($s0)
    /* 8E5E8 8008D9E8 8FAE0040 */  lw         $t6, 0x40($sp)
    /* 8E5EC 8008D9EC 3C198000 */  lui        $t9, %hi(func_80001CE8)
    /* 8E5F0 8008D9F0 316F0001 */  andi       $t7, $t3, 0x1
    /* 8E5F4 8008D9F4 11E00004 */  beqz       $t7, .L8008DA08
    /* 8E5F8 8008D9F8 25C40008 */   addiu     $a0, $t6, 0x8
    /* 8E5FC 8008D9FC 27391CE8 */  addiu      $t9, $t9, %lo(func_80001CE8)
    /* 8E600 8008DA00 0320F809 */  jalr       $t9
    /* 8E604 8008DA04 25C5000E */   addiu     $a1, $t6, 0xE
  .L8008DA08:
    /* 8E608 8008DA08 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 8E60C 8008DA0C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 8E610 8008DA10 27BD0040 */  addiu      $sp, $sp, 0x40
    /* 8E614 8008DA14 03E00008 */  jr         $ra
    /* 8E618 8008DA18 00000000 */   nop
endlabel D_8008D95C

nonmatching func_8008DA1C, 0x24

glabel func_8008DA1C
    /* 8E61C 8008DA1C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 8E620 8008DA20 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8E624 8008DA24 8C990010 */  lw         $t9, 0x10($a0)
    /* 8E628 8008DA28 0320F809 */  jalr       $t9
    /* 8E62C 8008DA2C 00000000 */   nop
    /* 8E630 8008DA30 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8E634 8008DA34 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 8E638 8008DA38 03E00008 */  jr         $ra
    /* 8E63C 8008DA3C 00000000 */   nop
endlabel func_8008DA1C

nonmatching func_8008DA40, 0x1C

glabel func_8008DA40
    /* 8E640 8008DA40 3C04801D */  lui        $a0, %hi(D_801C82C0)
    /* 8E644 8008DA44 248482C0 */  addiu      $a0, $a0, %lo(D_801C82C0)
    /* 8E648 8008DA48 848E0078 */  lh         $t6, 0x78($a0)
    /* 8E64C 8008DA4C 000E7880 */  sll        $t7, $t6, 2
    /* 8E650 8008DA50 008FC021 */  addu       $t8, $a0, $t7
    /* 8E654 8008DA54 03E00008 */  jr         $ra
    /* 8E658 8008DA58 8F02003C */   lw        $v0, 0x3C($t8)
endlabel func_8008DA40

nonmatching func_8008DA5C, 0xA4

glabel func_8008DA5C
    /* 8E65C 8008DA5C 3C02801D */  lui        $v0, %hi(D_801C82C0)
    /* 8E660 8008DA60 244282C0 */  addiu      $v0, $v0, %lo(D_801C82C0)
    /* 8E664 8008DA64 844E0078 */  lh         $t6, 0x78($v0)
    /* 8E668 8008DA68 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 8E66C 8008DA6C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8E670 8008DA70 000E7880 */  sll        $t7, $t6, 2
    /* 8E674 8008DA74 004FC021 */  addu       $t8, $v0, $t7
    /* 8E678 8008DA78 8C830034 */  lw         $v1, 0x34($a0)
    /* 8E67C 8008DA7C 8F19003C */  lw         $t9, 0x3C($t8)
    /* 8E680 8008DA80 00002825 */  or         $a1, $zero, $zero
    /* 8E684 8008DA84 24070005 */  addiu      $a3, $zero, 0x5
    /* 8E688 8008DA88 AFB90020 */  sw         $t9, 0x20($sp)
    /* 8E68C 8008DA8C 94680048 */  lhu        $t0, 0x48($v1)
    /* 8E690 8008DA90 946A004A */  lhu        $t2, 0x4A($v1)
    /* 8E694 8008DA94 3C198000 */  lui        $t9, %hi(func_800027B0)
    /* 8E698 8008DA98 00084840 */  sll        $t1, $t0, 1
    /* 8E69C 8008DA9C 012A0019 */  multu      $t1, $t2
    /* 8E6A0 8008DAA0 273927B0 */  addiu      $t9, $t9, %lo(func_800027B0)
    /* 8E6A4 8008DAA4 AFA30024 */  sw         $v1, 0x24($sp)
    /* 8E6A8 8008DAA8 00003012 */  mflo       $a2
    /* 8E6AC 8008DAAC 0320F809 */  jalr       $t9
    /* 8E6B0 8008DAB0 00000000 */   nop
    /* 8E6B4 8008DAB4 8FA30024 */  lw         $v1, 0x24($sp)
    /* 8E6B8 8008DAB8 00402825 */  or         $a1, $v0, $zero
    /* 8E6BC 8008DABC 8FA40020 */  lw         $a0, 0x20($sp)
    /* 8E6C0 8008DAC0 946B0048 */  lhu        $t3, 0x48($v1)
    /* 8E6C4 8008DAC4 946D004A */  lhu        $t5, 0x4A($v1)
    /* 8E6C8 8008DAC8 AFA2001C */  sw         $v0, 0x1C($sp)
    /* 8E6CC 8008DACC 000B6040 */  sll        $t4, $t3, 1
    /* 8E6D0 8008DAD0 018D0019 */  multu      $t4, $t5
    /* 8E6D4 8008DAD4 AFA30024 */  sw         $v1, 0x24($sp)
    /* 8E6D8 8008DAD8 00003012 */  mflo       $a2
    /* 8E6DC 8008DADC 0C000424 */  jal        func_80001090
    /* 8E6E0 8008DAE0 00000000 */   nop
    /* 8E6E4 8008DAE4 8FA30024 */  lw         $v1, 0x24($sp)
    /* 8E6E8 8008DAE8 8FA2001C */  lw         $v0, 0x1C($sp)
    /* 8E6EC 8008DAEC AC620008 */  sw         $v0, 0x8($v1)
    /* 8E6F0 8008DAF0 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8E6F4 8008DAF4 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 8E6F8 8008DAF8 03E00008 */  jr         $ra
    /* 8E6FC 8008DAFC 00000000 */   nop
endlabel func_8008DA5C

nonmatching func_8008DB00, 0x5C

glabel func_8008DB00
    /* 8E700 8008DB00 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 8E704 8008DB04 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 8E708 8008DB08 8C830034 */  lw         $v1, 0x34($a0)
    /* 8E70C 8008DB0C 3C02801D */  lui        $v0, %hi(D_801C82C0)
    /* 8E710 8008DB10 244282C0 */  addiu      $v0, $v0, %lo(D_801C82C0)
    /* 8E714 8008DB14 94790048 */  lhu        $t9, 0x48($v1)
    /* 8E718 8008DB18 9469004A */  lhu        $t1, 0x4A($v1)
    /* 8E71C 8008DB1C 844E0078 */  lh         $t6, 0x78($v0)
    /* 8E720 8008DB20 00194040 */  sll        $t0, $t9, 1
    /* 8E724 8008DB24 01090019 */  multu      $t0, $t1
    /* 8E728 8008DB28 000E7880 */  sll        $t7, $t6, 2
    /* 8E72C 8008DB2C 004FC021 */  addu       $t8, $v0, $t7
    /* 8E730 8008DB30 8F04003C */  lw         $a0, 0x3C($t8)
    /* 8E734 8008DB34 8C650008 */  lw         $a1, 0x8($v1)
    /* 8E738 8008DB38 AFA3001C */  sw         $v1, 0x1C($sp)
    /* 8E73C 8008DB3C 00003012 */  mflo       $a2
    /* 8E740 8008DB40 0C000424 */  jal        func_80001090
    /* 8E744 8008DB44 00000000 */   nop
    /* 8E748 8008DB48 8FA3001C */  lw         $v1, 0x1C($sp)
    /* 8E74C 8008DB4C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 8E750 8008DB50 8C620008 */  lw         $v0, 0x8($v1)
    /* 8E754 8008DB54 03E00008 */  jr         $ra
    /* 8E758 8008DB58 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_8008DB00

nonmatching func_8008DB5C, 0x34

glabel func_8008DB5C
    /* 8E75C 8008DB5C 3C07801D */  lui        $a3, %hi(D_801C82C0)
    /* 8E760 8008DB60 24E782C0 */  addiu      $a3, $a3, %lo(D_801C82C0)
    /* 8E764 8008DB64 84E50078 */  lh         $a1, 0x78($a3)
    /* 8E768 8008DB68 2401FFFF */  addiu      $at, $zero, -0x1
    /* 8E76C 8008DB6C 8C830034 */  lw         $v1, 0x34($a0)
    /* 8E770 8008DB70 24A5FFFE */  addiu      $a1, $a1, -0x2
    /* 8E774 8008DB74 00052C00 */  sll        $a1, $a1, 16
    /* 8E778 8008DB78 00052C03 */  sra        $a1, $a1, 16
    /* 8E77C 8008DB7C 54A10003 */  bnel       $a1, $at, .L8008DB8C
    /* 8E780 8008DB80 2401FFFE */   addiu     $at, $zero, -0x2
    /* 8E784 8008DB84 24050002 */  addiu      $a1, $zero, 0x2
    /* 8E788 8008DB88 2401FFFE */  addiu      $at, $zero, -0x2
  .L8008DB8C:
# PATCHED: # PATCHED: /* 8E78C 8008DB8C 54A10003 */  bnel       $a1, $at, D_8008DB9C
    nop
    nop
endlabel func_8008DB5C
