.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008AC30, 0x1E0

glabel func_8008AC30
    /* 8B830 8008AC30 AFBF0044 */  sw         $ra, 0x44($sp)
    /* 8B834 8008AC34 AFB20040 */  sw         $s2, 0x40($sp)
    /* 8B838 8008AC38 AFB1003C */  sw         $s1, 0x3C($sp)
    /* 8B83C 8008AC3C AFB00038 */  sw         $s0, 0x38($sp)
    /* 8B840 8008AC40 F7B60030 */  sdc1       $fs1, 0x30($sp)
    /* 8B844 8008AC44 F7B40028 */  sdc1       $fs0, 0x28($sp)
    /* 8B848 8008AC48 00808025 */  or         $s0, $a0, $zero
    /* 8B84C 8008AC4C 0C023082 */  jal        func_8008C208
    /* 8B850 8008AC50 8C920070 */   lw        $s2, 0x70($a0)
    /* 8B854 8008AC54 3C058019 */  lui        $a1, %hi(D_801927C0)
    /* 8B858 8008AC58 8CA527C0 */  lw         $a1, %lo(D_801927C0)($a1)
    /* 8B85C 8008AC5C 0C00168C */  jal        func_80005A30
    /* 8B860 8008AC60 24040004 */   addiu     $a0, $zero, 0x4
    /* 8B864 8008AC64 AE020024 */  sw         $v0, 0x24($s0)
    /* 8B868 8008AC68 94580002 */  lhu        $t8, 0x2($v0)
    /* 8B86C 8008AC6C 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 8B870 8008AC70 4481A000 */  mtc1       $at, $fs0
    /* 8B874 8008AC74 3C0E0600 */  lui        $t6, %hi(D_60015A8)
    /* 8B878 8008AC78 25CE15A8 */  addiu      $t6, $t6, %lo(D_60015A8)
    /* 8B87C 8008AC7C 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 8B880 8008AC80 241100C6 */  addiu      $s1, $zero, 0xC6
    /* 8B884 8008AC84 01C17825 */  or         $t7, $t6, $at
    /* 8B888 8008AC88 2409FFFF */  addiu      $t1, $zero, -0x1
    /* 8B88C 8008AC8C 37190800 */  ori        $t9, $t8, 0x800
    /* 8B890 8008AC90 AC4F003C */  sw         $t7, 0x3C($v0)
    /* 8B894 8008AC94 AC510040 */  sw         $s1, 0x40($v0)
    /* 8B898 8008AC98 A4590002 */  sh         $t9, 0x2($v0)
    /* 8B89C 8008AC9C AC490018 */  sw         $t1, 0x18($v0)
    /* 8B8A0 8008ACA0 A4400028 */  sh         $zero, 0x28($v0)
    /* 8B8A4 8008ACA4 A440002A */  sh         $zero, 0x2A($v0)
    /* 8B8A8 8008ACA8 00402025 */  or         $a0, $v0, $zero
    /* 8B8AC 8008ACAC 3C05C2FA */  lui        $a1, (0xC2FA0000 >> 16)
    /* 8B8B0 8008ACB0 3C0642B4 */  lui        $a2, (0x42B40000 >> 16)
    /* 8B8B4 8008ACB4 3C0741F0 */  lui        $a3, (0x41F00000 >> 16)
    /* 8B8B8 8008ACB8 E7B40018 */  swc1       $fs0, 0x18($sp)
    /* 8B8BC 8008ACBC E7B40014 */  swc1       $fs0, 0x14($sp)
    /* 8B8C0 8008ACC0 0C0231DD */  jal        func_8008C774
    /* 8B8C4 8008ACC4 E7B40010 */   swc1      $fs0, 0x10($sp)
    /* 8B8C8 8008ACC8 24040004 */  addiu      $a0, $zero, 0x4
    /* 8B8CC 8008ACCC 0C0016AF */  jal        func_80005ABC
    /* 8B8D0 8008ACD0 8E050024 */   lw        $a1, 0x24($s0)
    /* 8B8D4 8008ACD4 AE020034 */  sw         $v0, 0x34($s0)
    /* 8B8D8 8008ACD8 944C0002 */  lhu        $t4, 0x2($v0)
    /* 8B8DC 8008ACDC 3C0A0600 */  lui        $t2, %hi(D_6001830)
    /* 8B8E0 8008ACE0 254A1830 */  addiu      $t2, $t2, %lo(D_6001830)
    /* 8B8E4 8008ACE4 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* 8B8E8 8008ACE8 01415825 */  or         $t3, $t2, $at
    /* 8B8EC 8008ACEC 240EFFFF */  addiu      $t6, $zero, -0x1
    /* 8B8F0 8008ACF0 358D0800 */  ori        $t5, $t4, 0x800
    /* 8B8F4 8008ACF4 AC4B003C */  sw         $t3, 0x3C($v0)
    /* 8B8F8 8008ACF8 AC510040 */  sw         $s1, 0x40($v0)
    /* 8B8FC 8008ACFC A44D0002 */  sh         $t5, 0x2($v0)
    /* 8B900 8008AD00 AC4E0018 */  sw         $t6, 0x18($v0)
    /* 8B904 8008AD04 A4400028 */  sh         $zero, 0x28($v0)
    /* 8B908 8008AD08 A440002A */  sh         $zero, 0x2A($v0)
    /* 8B90C 8008AD0C E7B40018 */  swc1       $fs0, 0x18($sp)
    /* 8B910 8008AD10 E7B40014 */  swc1       $fs0, 0x14($sp)
    /* 8B914 8008AD14 E7B40010 */  swc1       $fs0, 0x10($sp)
    /* 8B918 8008AD18 00402025 */  or         $a0, $v0, $zero
    /* 8B91C 8008AD1C 3C054100 */  lui        $a1, (0x41000000 >> 16)
    /* 8B920 8008AD20 3C064120 */  lui        $a2, (0x41200000 >> 16)
    /* 8B924 8008AD24 0C0231DD */  jal        func_8008C774
    /* 8B928 8008AD28 3C0740A0 */   lui       $a3, (0x40A00000 >> 16)
    /* 8B92C 8008AD2C 24040004 */  addiu      $a0, $zero, 0x4
    /* 8B930 8008AD30 0C0016AF */  jal        func_80005ABC
    /* 8B934 8008AD34 8E050024 */   lw        $a1, 0x24($s0)
    /* 8B938 8008AD38 AE020038 */  sw         $v0, 0x38($s0)
    /* 8B93C 8008AD3C 94580002 */  lhu        $t8, 0x2($v0)
    /* 8B940 8008AD40 4480B000 */  mtc1       $zero, $fs1
    /* 8B944 8008AD44 3C0F0600 */  lui        $t7, %hi(D_60068E0)
    /* 8B948 8008AD48 25EF68E0 */  addiu      $t7, $t7, %lo(D_60068E0)
    /* 8B94C 8008AD4C 2409FFFF */  addiu      $t1, $zero, -0x1
    /* 8B950 8008AD50 37190800 */  ori        $t9, $t8, 0x800
    /* 8B954 8008AD54 AC4F003C */  sw         $t7, 0x3C($v0)
    /* 8B958 8008AD58 AC510040 */  sw         $s1, 0x40($v0)
    /* 8B95C 8008AD5C A4590002 */  sh         $t9, 0x2($v0)
    /* 8B960 8008AD60 AC490018 */  sw         $t1, 0x18($v0)
    /* 8B964 8008AD64 4405B000 */  mfc1       $a1, $fs1
    /* 8B968 8008AD68 4406B000 */  mfc1       $a2, $fs1
    /* 8B96C 8008AD6C AFA2004C */  sw         $v0, 0x4C($sp)
    /* 8B970 8008AD70 E7B40018 */  swc1       $fs0, 0x18($sp)
    /* 8B974 8008AD74 E7B40014 */  swc1       $fs0, 0x14($sp)
    /* 8B978 8008AD78 E7B40010 */  swc1       $fs0, 0x10($sp)
    /* 8B97C 8008AD7C 00402025 */  or         $a0, $v0, $zero
    /* 8B980 8008AD80 0C0231DD */  jal        func_8008C774
    /* 8B984 8008AD84 3C0740A0 */   lui       $a3, (0x40A00000 >> 16)
    /* 8B988 8008AD88 8FA8004C */  lw         $t0, 0x4C($sp)
    /* 8B98C 8008AD8C 864A0012 */  lh         $t2, 0x12($s2)
    /* 8B990 8008AD90 24040004 */  addiu      $a0, $zero, 0x4
    /* 8B994 8008AD94 A50A0060 */  sh         $t2, 0x60($t0)
    /* 8B998 8008AD98 0C0016AF */  jal        func_80005ABC
    /* 8B99C 8008AD9C 8E050024 */   lw        $a1, 0x24($s0)
    /* 8B9A0 8008ADA0 AE02003C */  sw         $v0, 0x3C($s0)
    /* 8B9A4 8008ADA4 944C0002 */  lhu        $t4, 0x2($v0)
    /* 8B9A8 8008ADA8 3C0B0600 */  lui        $t3, %hi(D_6006880)
    /* 8B9AC 8008ADAC 256B6880 */  addiu      $t3, $t3, %lo(D_6006880)
    /* 8B9B0 8008ADB0 240EFFFF */  addiu      $t6, $zero, -0x1
    /* 8B9B4 8008ADB4 358D0800 */  ori        $t5, $t4, 0x800
    /* 8B9B8 8008ADB8 AC4B003C */  sw         $t3, 0x3C($v0)
    /* 8B9BC 8008ADBC AC510040 */  sw         $s1, 0x40($v0)
    /* 8B9C0 8008ADC0 A44D0002 */  sh         $t5, 0x2($v0)
    /* 8B9C4 8008ADC4 AC4E0018 */  sw         $t6, 0x18($v0)
    /* 8B9C8 8008ADC8 4405B000 */  mfc1       $a1, $fs1
    /* 8B9CC 8008ADCC 4406B000 */  mfc1       $a2, $fs1
    /* 8B9D0 8008ADD0 AFA2004C */  sw         $v0, 0x4C($sp)
    /* 8B9D4 8008ADD4 E7B40018 */  swc1       $fs0, 0x18($sp)
    /* 8B9D8 8008ADD8 E7B40014 */  swc1       $fs0, 0x14($sp)
    /* 8B9DC 8008ADDC E7B40010 */  swc1       $fs0, 0x10($sp)
    /* 8B9E0 8008ADE0 00402025 */  or         $a0, $v0, $zero
    /* 8B9E4 8008ADE4 0C0231DD */  jal        func_8008C774
    /* 8B9E8 8008ADE8 3C0740E0 */   lui       $a3, (0x40E00000 >> 16)
    /* 8B9EC 8008ADEC 8FA8004C */  lw         $t0, 0x4C($sp)
    /* 8B9F0 8008ADF0 864F0010 */  lh         $t7, 0x10($s2)
    /* 8B9F4 8008ADF4 24040004 */  addiu      $a0, $zero, 0x4
    /* 8B9F8 8008ADF8 A50F0060 */  sh         $t7, 0x60($t0)
    /* 8B9FC 8008ADFC 0C0016AF */  jal        func_80005ABC
    /* 8BA00 8008AE00 8E050024 */   lw        $a1, 0x24($s0)
    /* 8BA04 8008AE04 AE020040 */  sw         $v0, 0x40($s0)
    /* 8BA08 8008AE08 94590002 */  lhu        $t9, 0x2($v0)
    /* 8BA0C 8008AE0C 3C180600 */  lui        $t8, (0x6000000 >> 16)
endlabel func_8008AC30
