.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching .L80083560, 0x4

glabel .L80083560
    /* 84160 80083560 0004C100 */  sll        $t8, $a0, 4
endlabel .L80083560

nonmatching D_80083564, 0x6C

glabel D_80083564
    jr $ra
    nop
  .L800835C4:
    jr $ra
    nop
endlabel D_80083564

nonmatching func_800835D0, 0x294

glabel func_800835D0
    jr $ra
    nop
  .L80083600:
    jr $ra
    nop
  .L8008361C:
    jr $ra
    nop
  .L80083624:
    jr $ra
    nop
  .L80083638:
    jr $ra
    nop
  .L80083678:
    jr $ra
    nop
  .L800836AC:
    jr $ra
    nop
  .L800836C8:
    jr $ra
    nop
  .L800836DC:
    jr $ra
    nop
  .L800836F4:
    jr $ra
    nop
  .L80083740:
    jr $ra
    nop
  .L80083760:
    jr $ra
    nop
  .L80083764:
    jr $ra
    nop
  .L80083780:
    jr $ra
    nop
  .L8008379C:
    jr $ra
    nop
  .L80083854:
    jr $ra
    nop
endlabel func_800835D0

nonmatching func_80083864, 0xA4

glabel func_80083864
    jr $ra
    nop
  .L8008387C:
    jr $ra
    nop
  .L80083898:
    jr $ra
    nop
  .L8008389C:
    jr $ra
    nop
  .L800838B0:
    jr $ra
    nop
  .L800838C4:
    jr $ra
    nop
  .L800838FC:
    jr $ra
    nop
endlabel func_80083864

nonmatching func_80083908, 0x9C

glabel func_80083908
    jr $ra
    nop
  .L80083920:
    jr $ra
    nop
  .L80083940:
    jr $ra
    nop
  .L80083944:
    jr $ra
    nop
  .L80083960:
    jr $ra
    nop
  .L80083998:
    jr $ra
    nop
endlabel func_80083908

nonmatching func_800839A4, 0x3C

glabel func_800839A4
    jr $ra
    nop
  .L800839C8:
    jr $ra
    nop
endlabel func_800839A4
