.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008C5A0, 0x130

glabel func_8008C5A0
    jr $ra
    nop
  .L8008C5BC:
    jr $ra
    nop
endlabel func_8008C5A0
