.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008A100, 0x4

glabel func_8008A100
    jr $ra
    nop
endlabel func_8008A100

nonmatching D_8008A104, 0x5C

glabel D_8008A104
    jr $ra
    nop
  .L8008A13C:
    jr $ra
    nop
  .L8008A154:
    jr $ra
    nop
endlabel D_8008A104
