.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80080E00, 0x4

glabel func_80080E00
    jr $ra
    nop
endlabel func_80080E00

nonmatching D_80080E04, 0x4

glabel D_80080E04
    jr $ra
    nop
endlabel D_80080E04

nonmatching D_80080E08, 0xB8

glabel D_80080E08
    jr $ra
    nop
  alabel D_80080E20
    jr $ra
    nop
  .L80080E38:
    jr $ra
    nop
  .L80080E54:
    jr $ra
    nop
  .L80080E6C:
    jr $ra
    nop
  .L80080E70:
    jr $ra
    nop
  .L80080E94:
    jr $ra
    nop
  .L80080EAC:
    jr $ra
    nop
  alabel D_80080EB8
    jr $ra
    nop
endlabel D_80080E08
