.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008C1B0, 0x24

glabel func_8008C1B0
    jr $ra
    nop
endlabel func_8008C1B0

nonmatching D_8008C1D4, 0xC

glabel D_8008C1D4
    jr $ra
    nop
endlabel D_8008C1D4
