.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80080DC0, 0x4

glabel func_80080DC0
    jr $ra
    nop
endlabel func_80080DC0

nonmatching func_80080DC4, 0x28

glabel func_80080DC4
    jr $ra
    nop
endlabel func_80080DC4

nonmatching D_80080DEC, 0x14

glabel D_80080DEC
    jr $ra
    nop
endlabel D_80080DEC
