.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008FC50, 0x40

glabel func_8008FC50
    jr $ra
    nop
  .L8008FC74:
    jr $ra
    nop
  .L8008FC8C:
    jr $ra
    nop
endlabel func_8008FC50
