.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800824F0, 0x40

glabel func_800824F0
    /* 830F0 800824F0 A500000A */  sh         $zero, 0xA($t0)
    /* 830F4 800824F4 90A90024 */  lbu        $t1, 0x24($a1)
    /* 830F8 800824F8 0049082A */  slt        $at, $v0, $t1
# PATCHED: # PATCHED: /* 830FC 800824FC 1420FFF7 */  bnez       $at, D_800824DC
    nop
    nop
    /* 83100 80082500 00000000 */   nop
  alabel D_80082504
# PATCHED: # PATCHED: /* 83104 80082504 10000011 */  b          D_8008254C
    nop
    nop
    /* 83108 80082508 A4C00010 */   sh        $zero, 0x10($a2)
    /* 8310C 8008250C 90AA0024 */  lbu        $t2, 0x24($a1)
  alabel D_80082510
    /* 83110 80082510 00001025 */  or         $v0, $zero, $zero
    /* 83114 80082514 2404000E */  addiu      $a0, $zero, 0xE
# PATCHED: # PATCHED: /* 83118 80082518 5940000C */  blezl      $t2, D_8008254C
    nop
    nop
    /* 8311C 8008251C A4C00002 */   sh        $zero, 0x2($a2)
  alabel D_80082520
    /* 83120 80082520 00440019 */  multu      $v0, $a0
    /* 83124 80082524 24420001 */  addiu      $v0, $v0, 0x1
    /* 83128 80082528 304200FF */  andi       $v0, $v0, 0xFF
    /* 8312C 8008252C 00005812 */  mflo       $t3
endlabel func_800824F0
