.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008C380, 0x50

glabel func_8008C380
    jr $ra
    nop
endlabel func_8008C380

nonmatching D_8008C3D0, 0x110

glabel D_8008C3D0
    jr $ra
    nop
  .L8008C440:
    jr $ra
    nop
  .L8008C444:
    jr $ra
    nop
  .L8008C4B4:
    jr $ra
    nop
  .L8008C4DC:
    jr $ra
    nop
endlabel D_8008C3D0
