.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8007FF20, 0x48

glabel func_8007FF20
    jr $ra
    nop
  .L8007FF5C:
    jr $ra
    nop
endlabel func_8007FF20

nonmatching D_8007FF68, 0x58

glabel D_8007FF68
    jr $ra
    nop
  .L8007FF74:
    jr $ra
    nop
endlabel D_8007FF68
