.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8000F500, 0x14

glabel func_8000F500
    jr $ra
    nop
endlabel func_8000F500

nonmatching D_8000F514, 0xAC

glabel D_8000F514
    jr $ra
    nop
  .L8000F52C:
    jr $ra
    nop
  alabel D_8000F544
    jr $ra
    nop
  .L8000F548:
    jr $ra
    nop
  alabel func_8000F560
    jr $ra
    nop
  alabel func_8000F584
    jr $ra
    nop
  alabel D_8000F5BC
    jr $ra
    nop
endlabel D_8000F514
