.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800107D0, 0x10

glabel func_800107D0
    jr $ra
    nop
endlabel func_800107D0

nonmatching D_800107E0, 0x8

glabel D_800107E0
    jr $ra
    nop
endlabel D_800107E0
    /* 113E8 800107E8 00000000 */  nop
    /* 113EC 800107EC 00000000 */  nop

nonmatching func_800107F0, 0x8

glabel func_800107F0
    jr $ra
    nop
endlabel func_800107F0

nonmatching func_800107F8, 0x30

glabel func_800107F8
    jr $ra
    nop
endlabel func_800107F8

nonmatching func_80010828, 0x48

glabel func_80010828
    jr $ra
    nop
  .L80010860:
    jr $ra
    nop
endlabel func_80010828

nonmatching func_80010870, 0x48

glabel func_80010870
    jr $ra
    nop
  .L800108A8:
    jr $ra
    nop
endlabel func_80010870

nonmatching func_800108B8, 0x48

glabel func_800108B8
    jr $ra
    nop
  .L800108F0:
    jr $ra
    nop
endlabel func_800108B8

nonmatching func_80010900, 0x48

glabel func_80010900
    jr $ra
    nop
  .L80010938:
    jr $ra
    nop
endlabel func_80010900

nonmatching func_80010948, 0x54

glabel func_80010948
    jr $ra
    nop
endlabel func_80010948

nonmatching func_8001099C, 0x54

glabel func_8001099C
    jr $ra
    nop
endlabel func_8001099C

nonmatching func_800109F0, 0x54

glabel func_800109F0
    jr $ra
    nop
endlabel func_800109F0

nonmatching func_80010A44, 0x54

glabel func_80010A44
    jr $ra
    nop
endlabel func_80010A44

nonmatching func_80010A98, 0x54

glabel func_80010A98
    jr $ra
    nop
endlabel func_80010A98

nonmatching func_80010AEC, 0x54

glabel func_80010AEC
    jr $ra
    nop
endlabel func_80010AEC

nonmatching func_80010B40, 0x44

glabel func_80010B40
    jr $ra
    nop
  .L80010B74:
    jr $ra
    nop
endlabel func_80010B40

nonmatching func_80010B84, 0xFC

glabel func_80010B84
    jr $ra
    nop
  .L80010BDC:
    jr $ra
    nop
  .L80010C24:
    jr $ra
    nop
  .L80010C3C:
    jr $ra
    nop
  .L80010C50:
    jr $ra
    nop
endlabel func_80010B84

nonmatching func_80010C80, 0xC8

glabel func_80010C80
    jr $ra
    nop
  .L80010CD4:
    jr $ra
    nop
  .L80010D04:
    jr $ra
    nop
  .L80010D1C:
    jr $ra
    nop
endlabel func_80010C80

nonmatching func_80010D48, 0x8C

glabel func_80010D48
    jr $ra
    nop
  .L80010D80:
    jr $ra
    nop
  .L80010DA0:
    jr $ra
    nop
  .L80010DAC:
    jr $ra
    nop
  .L80010DB8:
    jr $ra
    nop
endlabel func_80010D48

nonmatching func_80010DD4, 0xC0

glabel func_80010DD4
    jr $ra
    nop
  .L80010E1C:
    jr $ra
    nop
  .L80010E48:
    jr $ra
    nop
  .L80010E54:
    jr $ra
    nop
  .L80010E60:
    jr $ra
    nop
  .L80010E64:
    jr $ra
    nop
  .L80010E70:
    jr $ra
    nop
endlabel func_80010DD4
    /* 11A94 80010E94 00000000 */  nop
    /* 11A98 80010E98 00000000 */  nop
    /* 11A9C 80010E9C 00000000 */  nop

nonmatching func_80010EA0, 0x5C

glabel func_80010EA0
    jr $ra
    nop
endlabel func_80010EA0

nonmatching func_80010EFC, 0x164

glabel func_80010EFC
    jr $ra
    nop
  .L80010F48:
    jr $ra
    nop
  .L80010F6C:
    jr $ra
    nop
  .L80010F70:
    jr $ra
    nop
  .L80010F8C:
    jr $ra
    nop
  .L80010FF4:
    jr $ra
    nop
  .L80011008:
    jr $ra
    nop
  .L8001100C:
    jr $ra
    nop
  .L80011024:
    jr $ra
    nop
  .L80011050:
    jr $ra
    nop
endlabel func_80010EFC

nonmatching func_80011060, 0x1DC

glabel func_80011060
    jr $ra
    nop
  .L80011178:
    jr $ra
    nop
  .L80011190:
    jr $ra
    nop
  .L800111A8:
    jr $ra
    nop
  .L800111C4:
    jr $ra
    nop
  .L800111CC:
    jr $ra
    nop
  .L80011210:
    jr $ra
    nop
endlabel func_80011060

nonmatching func_8001123C, 0xD4

glabel func_8001123C
    jr $ra
    nop
  .L800112B0:
    jr $ra
    nop
  .L800112B4:
    jr $ra
    nop
endlabel func_8001123C
