.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80011B00, 0x30

glabel func_80011B00
    jr $ra
    nop
  .L80011B10:
    jr $ra
    nop
  .L80011B24:
    jr $ra
    nop
endlabel func_80011B00

nonmatching D_80011B30, 0xB4

glabel D_80011B30
    jr $ra
    nop
  .L80011B40:
    jr $ra
    nop
  .L80011B44:
    jr $ra
    nop
  .L80011B70:
    jr $ra
    nop
  .L80011B84:
    jr $ra
    nop
  .L80011BCC:
    jr $ra
    nop
endlabel D_80011B30

nonmatching D_80011BE4, 0x2C

glabel D_80011BE4
    jr $ra
    nop
endlabel D_80011BE4

nonmatching func_80011C10, 0xA8

glabel func_80011C10
    jr $ra
    nop
  .L80011C4C:
    jr $ra
    nop
  .L80011CA0:
    jr $ra
    nop
endlabel func_80011C10

nonmatching func_80011CB8, 0x48

glabel func_80011CB8
    jr $ra
    nop
  .L80011CF8:
    jr $ra
    nop
endlabel func_80011CB8
