.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80015A40, 0x48

glabel func_80015A40
    jr $ra
    nop
  .L80015A74:
    jr $ra
    nop
  .L80015A78:
    jr $ra
    nop
endlabel func_80015A40

nonmatching func_80015A88, 0x18

glabel func_80015A88
    jr $ra
    nop
endlabel func_80015A88
