.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80017830, 0xC

glabel func_80017830
    jr $ra
    nop
endlabel func_80017830

nonmatching func_8001783C, 0x94

glabel func_8001783C
    jr $ra
    nop
  .L800178AC:
    jr $ra
    nop
endlabel func_8001783C

nonmatching func_800178D0, 0xBC

glabel func_800178D0
    jr $ra
    nop
  .L8001795C:
    jr $ra
    nop
  .L80017964:
    jr $ra
    nop
  .L80017988:
    jr $ra
    nop
endlabel func_800178D0
    /* 1858C 8001798C 00000000 */  nop
