.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80018970, 0x48

glabel func_80018970
    /* 19570 80018970 AFB10018 */  sw         $s1, 0x18($sp)
    /* 19574 80018974 AFB00014 */  sw         $s0, 0x14($sp)
    /* 19578 80018978 8C900888 */  lw         $s0, 0x888($a0)
    /* 1957C 8001897C 00A08825 */  or         $s1, $a1, $zero
    /* 19580 80018980 52000009 */  beql       $s0, $zero, .L800189A8
    /* 19584 80018984 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 19588 80018988 8E040004 */  lw         $a0, 0x4($s0)
  .L8001898C:
    /* 1958C 8001898C 02202825 */  or         $a1, $s1, $zero
    /* 19590 80018990 0C0259D8 */  jal        func_80096760
    /* 19594 80018994 00003025 */   or        $a2, $zero, $zero
    /* 19598 80018998 8E100000 */  lw         $s0, 0x0($s0)
    /* 1959C 8001899C 5600FFFB */  bnel       $s0, $zero, .L8001898C
    /* 195A0 800189A0 8E040004 */   lw        $a0, 0x4($s0)
    /* 195A4 800189A4 8FBF001C */  lw         $ra, 0x1C($sp)
  .L800189A8:
    /* 195A8 800189A8 8FB00014 */  lw         $s0, 0x14($sp)
    /* 195AC 800189AC 8FB10018 */  lw         $s1, 0x18($sp)
    /* 195B0 800189B0 03E00008 */  jr         $ra
    /* 195B4 800189B4 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80018970

nonmatching func_800189B8, 0x54

glabel func_800189B8
    /* 195B8 800189B8 27BDFF98 */  addiu      $sp, $sp, -0x68
    /* 195BC 800189BC AFBE0038 */  sw         $fp, 0x38($sp)
    /* 195C0 800189C0 AFB70034 */  sw         $s7, 0x34($sp)
    /* 195C4 800189C4 AFB60030 */  sw         $s6, 0x30($sp)
    /* 195C8 800189C8 AFB5002C */  sw         $s5, 0x2C($sp)
    /* 195CC 800189CC AFB40028 */  sw         $s4, 0x28($sp)
    /* 195D0 800189D0 AFB20020 */  sw         $s2, 0x20($sp)
    /* 195D4 800189D4 AFB1001C */  sw         $s1, 0x1C($sp)
    /* 195D8 800189D8 00809025 */  or         $s2, $a0, $zero
    /* 195DC 800189DC AFBF003C */  sw         $ra, 0x3C($sp)
    /* 195E0 800189E0 AFB30024 */  sw         $s3, 0x24($sp)
    /* 195E4 800189E4 AFB00018 */  sw         $s0, 0x18($sp)
    /* 195E8 800189E8 AFA00064 */  sw         $zero, 0x64($sp)
    /* 195EC 800189EC AFA00060 */  sw         $zero, 0x60($sp)
    /* 195F0 800189F0 00008825 */  or         $s1, $zero, $zero
    /* 195F4 800189F4 27B40064 */  addiu      $s4, $sp, 0x64
    /* 195F8 800189F8 24950004 */  addiu      $s5, $a0, 0x4
    /* 195FC 800189FC 27B60060 */  addiu      $s6, $sp, 0x60
    /* 19600 80018A00 24170001 */  addiu      $s7, $zero, 0x1
    /* 19604 80018A04 241E0002 */  addiu      $fp, $zero, 0x2
    /* 19608 80018A08 02A02025 */  or         $a0, $s5, $zero
endlabel func_800189B8

nonmatching D_80018A0C, 0x14

glabel D_80018A0C
    /* 1960C 80018A0C 02C02825 */  or         $a1, $s6, $zero
    /* 19610 80018A10 0C025B38 */  jal        func_80096CE0
    /* 19614 80018A14 24060001 */   addiu     $a2, $zero, 0x1
    /* 19618 80018A18 0C029A78 */  jal        func_800A69E0
    /* 1961C 80018A1C 00000000 */   nop
endlabel D_80018A0C
