.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8001A250, 0xC

glabel func_8001A250
    jr $ra
    nop
endlabel func_8001A250

nonmatching func_8001A25C, 0xF4

glabel func_8001A25C
    jr $ra
    nop
  .L8001A2A4:
    jr $ra
    nop
  .L8001A2BC:
    jr $ra
    nop
  .L8001A310:
    jr $ra
    nop
  .L8001A314:
    jr $ra
    nop
endlabel func_8001A25C

nonmatching func_8001A350, 0x24

glabel func_8001A350
    jr $ra
    nop
endlabel func_8001A350

nonmatching func_8001A374, 0xC

glabel func_8001A374
    jr $ra
    nop
endlabel func_8001A374
