.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80002950, 0x9C

glabel func_80002950
    jr $ra
    nop
  .L800029B8:
    jr $ra
    nop
  .L800029DC:
    jr $ra
    nop
  .L800029E0:
    jr $ra
    nop
endlabel func_80002950

nonmatching func_800029EC, 0xA8

glabel func_800029EC
    jr $ra
    nop
  .L80002A04:
    jr $ra
    nop
  .L80002A1C:
    jr $ra
    nop
  .L80002A44:
    jr $ra
    nop
  .L80002A5C:
    jr $ra
    nop
  .L80002A78:
    jr $ra
    nop
  .L80002A80:
    jr $ra
    nop
  .L80002A84:
    jr $ra
    nop
endlabel func_800029EC

nonmatching func_80002A94, 0x70

glabel func_80002A94
    jr $ra
    nop
endlabel func_80002A94
    /* 3704 80002B04 00000000 */  nop
    /* 3708 80002B08 00000000 */  nop
    /* 370C 80002B0C 00000000 */  nop

nonmatching func_80002B10, 0x168

glabel func_80002B10
    jr $ra
    nop
  .L80002B70:
    jr $ra
    nop
  .L80002B7C:
    jr $ra
    nop
  .L80002B8C:
    jr $ra
    nop
  .L80002B9C:
    jr $ra
    nop
  .L80002BB0:
    jr $ra
    nop
  .L80002BB4:
    jr $ra
    nop
  .L80002BDC:
    jr $ra
    nop
  .L80002BF0:
    jr $ra
    nop
  .L80002C00:
    jr $ra
    nop
  .L80002C04:
    jr $ra
    nop
  .L80002C38:
    jr $ra
    nop
  .L80002C3C:
    jr $ra
    nop
endlabel func_80002B10

nonmatching func_80002C78, 0x68

glabel func_80002C78
    jr $ra
    nop
  .L80002CB0:
    jr $ra
    nop
  .L80002CCC:
    jr $ra
    nop
  .L80002CD0:
    jr $ra
    nop
endlabel func_80002C78

nonmatching func_80002CE0, 0x74

glabel func_80002CE0
    jr $ra
    nop
  .L80002D1C:
    jr $ra
    nop
  .L80002D38:
    jr $ra
    nop
endlabel func_80002CE0

nonmatching func_80002D54, 0x8

glabel func_80002D54
    jr $ra
    nop
endlabel func_80002D54

nonmatching func_80002D5C, 0xE0

glabel func_80002D5C
    jr $ra
    nop
  .L80002D78:
    jr $ra
    nop
  .L80002D9C:
    jr $ra
    nop
  .L80002DA0:
    jr $ra
    nop
  .L80002DBC:
    jr $ra
    nop
  .L80002DE0:
    jr $ra
    nop
  .L80002E04:
    jr $ra
    nop
  .L80002E30:
    jr $ra
    nop
endlabel func_80002D5C

nonmatching func_80002E3C, 0x11C

glabel func_80002E3C
    jr $ra
    nop
  .L80002EA0:
    jr $ra
    nop
  .L80002ECC:
    jr $ra
    nop
  .L80002EE8:
    jr $ra
    nop
  .L80002F00:
    jr $ra
    nop
  .L80002F0C:
    jr $ra
    nop
  .L80002F18:
    jr $ra
    nop
  .L80002F1C:
    jr $ra
    nop
  .L80002F24:
    jr $ra
    nop
  .L80002F2C:
    jr $ra
    nop
endlabel func_80002E3C
    /* 3B58 80002F58 00000000 */  nop
    /* 3B5C 80002F5C 00000000 */  nop

nonmatching func_80002F60, 0x98

glabel func_80002F60
    jr $ra
    nop
endlabel func_80002F60

nonmatching func_80002FF8, 0xB0

glabel func_80002FF8
    jr $ra
    nop
endlabel func_80002FF8

nonmatching func_800030A8, 0x100

glabel func_800030A8
    jr $ra
    nop
endlabel func_800030A8

nonmatching func_800031A8, 0x84

glabel func_800031A8
    jr $ra
    nop
  .L800031BC:
    jr $ra
    nop
  .L800031D0:
    jr $ra
    nop
  .L80003208:
    jr $ra
    nop
endlabel func_800031A8

nonmatching func_8000322C, 0x18C

glabel func_8000322C
    jr $ra
    nop
endlabel func_8000322C

nonmatching func_800033B8, 0x198

glabel func_800033B8
    jr $ra
    nop
endlabel func_800033B8

nonmatching func_80003550, 0x1EC

glabel func_80003550
    jr $ra
    nop
endlabel func_80003550

nonmatching func_8000373C, 0x200

glabel func_8000373C
    jr $ra
    nop
endlabel func_8000373C

nonmatching func_8000393C, 0x50

glabel func_8000393C
    jr $ra
    nop
endlabel func_8000393C

nonmatching func_8000398C, 0x1B8

glabel func_8000398C
    jr $ra
    nop
  .L800039E4:
    jr $ra
    nop
  .L80003A54:
    jr $ra
    nop
  .L80003AEC:
    jr $ra
    nop
  .L80003B00:
    jr $ra
    nop
endlabel func_8000398C

nonmatching func_80003B44, 0x16C

glabel func_80003B44
    jr $ra
    nop
  .L80003BB0:
    jr $ra
    nop
  .L80003BBC:
    jr $ra
    nop
  .L80003C04:
    jr $ra
    nop
  .L80003C18:
    jr $ra
    nop
  .L80003C3C:
    jr $ra
    nop
  .L80003C40:
    jr $ra
    nop
  .L80003C54:
    jr $ra
    nop
  .L80003C68:
    jr $ra
    nop
  .L80003C80:
    jr $ra
    nop
endlabel func_80003B44

nonmatching func_80003CB0, 0x108

glabel func_80003CB0
    jr $ra
    nop
  .L80003D00:
    jr $ra
    nop
  .L80003D70:
    jr $ra
    nop
endlabel func_80003CB0

nonmatching func_80003DB8, 0x7C

glabel func_80003DB8
    jr $ra
    nop
  .L80003DE8:
    jr $ra
    nop
endlabel func_80003DB8

nonmatching func_80003E34, 0x18C

glabel func_80003E34
    jr $ra
    nop
  .L80003F00:
    jr $ra
    nop
endlabel func_80003E34
