.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800445C0, 0x4

glabel func_800445C0
    jr $ra
    nop
endlabel func_800445C0

nonmatching D_800445C4, 0x4

glabel D_800445C4
    jr $ra
    nop
endlabel D_800445C4

nonmatching D_800445C8, 0x10

glabel D_800445C8
    jr $ra
    nop
endlabel D_800445C8

nonmatching func_800445D8, 0x1A0

glabel func_800445D8
    jr $ra
    nop
  .L80044604:
    jr $ra
    nop
  .L80044628:
    jr $ra
    nop
  .L80044640:
    jr $ra
    nop
  .L80044654:
    jr $ra
    nop
  .L80044670:
    jr $ra
    nop
  .L80044678:
    jr $ra
    nop
  .L8004468C:
    jr $ra
    nop
  .L800446A0:
    jr $ra
    nop
  .L800446B4:
    jr $ra
    nop
  .L800446D0:
    jr $ra
    nop
  .L800446E0:
    jr $ra
    nop
  .L80044750:
    jr $ra
    nop
  .L80044764:
    jr $ra
    nop
  .L80044768:
    jr $ra
    nop
endlabel func_800445D8
    /* 45378 80044778 00000000 */  nop
    /* 4537C 8004477C 00000000 */  nop

nonmatching func_80044780, 0x48

glabel func_80044780
    jr $ra
    nop
  .L800447B0:
    jr $ra
    nop
  .L800447B8:
    jr $ra
    nop
  .L800447BC:
    jr $ra
    nop
endlabel func_80044780

nonmatching func_800447C8, 0x40

glabel func_800447C8
    jr $ra
    nop
  .L800447F0:
    jr $ra
    nop
  .L800447FC:
    jr $ra
    nop
endlabel func_800447C8

nonmatching func_80044808, 0xF4

glabel func_80044808
    jr $ra
    nop
  .L80044854:
    jr $ra
    nop
  .L800448BC:
    jr $ra
    nop
  .L800448E8:
    jr $ra
    nop
endlabel func_80044808

nonmatching func_800448FC, 0x228

glabel func_800448FC
    jr $ra
    nop
  .L80044960:
    jr $ra
    nop
  .L800449B4:
    jr $ra
    nop
  .L80044A30:
    jr $ra
    nop
  .L80044A48:
    jr $ra
    nop
  .L80044A74:
    jr $ra
    nop
  .L80044A88:
    jr $ra
    nop
  .L80044AA0:
    jr $ra
    nop
  .L80044AE0:
    jr $ra
    nop
  .L80044AF4:
    jr $ra
    nop
  .L80044AF8:
    jr $ra
    nop
endlabel func_800448FC

nonmatching func_80044B24, 0x74

glabel func_80044B24
    jr $ra
    nop
  .L80044B30:
    jr $ra
    nop
  .L80044B44:
    jr $ra
    nop
  .L80044B58:
    jr $ra
    nop
  .L80044B6C:
    jr $ra
    nop
  .L80044B84:
    jr $ra
    nop
endlabel func_80044B24

nonmatching func_80044B98, 0x40

glabel func_80044B98
    jr $ra
    nop
  .L80044BC0:
    jr $ra
    nop
  .L80044BCC:
    jr $ra
    nop
endlabel func_80044B98

nonmatching func_80044BD8, 0xE8

glabel func_80044BD8
    jr $ra
    nop
  .L80044C24:
    jr $ra
    nop
  .L80044C88:
    jr $ra
    nop
  .L80044CB4:
    jr $ra
    nop
endlabel func_80044BD8
