.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80046EA0, 0x3C

glabel func_80046EA0
    /* 47AA0 80046EA0 C4A60000 */  lwc1       $ft1, 0x0($a1)
    /* 47AA4 80046EA4 C4840000 */  lwc1       $ft0, 0x0($a0)
    /* 47AA8 80046EA8 C4AA0008 */  lwc1       $ft3, 0x8($a1)
    /* 47AAC 80046EAC C4880008 */  lwc1       $ft2, 0x8($a0)
    /* 47AB0 80046EB0 46062001 */  sub.s      $fv0, $ft0, $ft1
    /* 47AB4 80046EB4 460A4081 */  sub.s      $fv1, $ft2, $ft3
    /* 47AB8 80046EB8 46000402 */  mul.s      $ft4, $fv0, $fv0
    /* 47ABC 80046EBC 00000000 */  nop
    /* 47AC0 80046EC0 46021482 */  mul.s      $ft5, $fv1, $fv1
    /* 47AC4 80046EC4 0C028078 */  jal        func_800A01E0
    /* 47AC8 80046EC8 46128300 */   add.s     $fa0, $ft4, $ft5
    /* 47ACC 80046ECC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 47AD0 80046ED0 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 47AD4 80046ED4 03E00008 */  jr         $ra
    /* 47AD8 80046ED8 00000000 */   nop
endlabel func_80046EA0

nonmatching func_80046EDC, 0x40

glabel func_80046EDC
    /* 47ADC 80046EDC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 47AE0 80046EE0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 47AE4 80046EE4 C4820000 */  lwc1       $fv1, 0x0($a0)
    /* 47AE8 80046EE8 C48E0004 */  lwc1       $fa1, 0x4($a0)
    /* 47AEC 80046EEC C4800008 */  lwc1       $fv0, 0x8($a0)
    /* 47AF0 80046EF0 46021102 */  mul.s      $ft0, $fv1, $fv1
    /* 47AF4 80046EF4 00000000 */  nop
    /* 47AF8 80046EF8 460E7182 */  mul.s      $ft1, $fa1, $fa1
    /* 47AFC 80046EFC 46062200 */  add.s      $ft2, $ft0, $ft1
    /* 47B00 80046F00 46000282 */  mul.s      $ft3, $fv0, $fv0
    /* 47B04 80046F04 0C028078 */  jal        func_800A01E0
    /* 47B08 80046F08 46085300 */   add.s     $fa0, $ft3, $ft2
    /* 47B0C 80046F0C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 47B10 80046F10 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 47B14 80046F14 03E00008 */  jr         $ra
    /* 47B18 80046F18 00000000 */   nop
endlabel func_80046EDC

nonmatching func_80046F1C, 0x40

glabel func_80046F1C
    /* 47B1C 80046F1C 00801825 */  or         $v1, $a0, $zero
    /* 47B20 80046F20 24040003 */  addiu      $a0, $zero, 0x3
    /* 47B24 80046F24 00001025 */  or         $v0, $zero, $zero
    /* 47B28 80046F28 00C03825 */  or         $a3, $a2, $zero
    /* 47B2C 80046F2C 00A04025 */  or         $t0, $a1, $zero
  .L80046F30:
    /* 47B30 80046F30 C4E40000 */  lwc1       $ft0, 0x0($a3)
    /* 47B34 80046F34 C5060000 */  lwc1       $ft1, 0x0($t0)
    /* 47B38 80046F38 24420001 */  addiu      $v0, $v0, 0x1
    /* 47B3C 80046F3C 24630004 */  addiu      $v1, $v1, 0x4
    /* 47B40 80046F40 46062200 */  add.s      $ft2, $ft0, $ft1
    /* 47B44 80046F44 24E70004 */  addiu      $a3, $a3, 0x4
    /* 47B48 80046F48 25080004 */  addiu      $t0, $t0, 0x4
    /* 47B4C 80046F4C 1444FFF8 */  bne        $v0, $a0, .L80046F30
    /* 47B50 80046F50 E468FFFC */   swc1      $ft2, -0x4($v1)
    /* 47B54 80046F54 03E00008 */  jr         $ra
    /* 47B58 80046F58 00000000 */   nop
endlabel func_80046F1C

nonmatching func_80046F5C, 0x40

glabel func_80046F5C
    /* 47B5C 80046F5C 00801825 */  or         $v1, $a0, $zero
    /* 47B60 80046F60 24040003 */  addiu      $a0, $zero, 0x3
    /* 47B64 80046F64 00001025 */  or         $v0, $zero, $zero
    /* 47B68 80046F68 00A03825 */  or         $a3, $a1, $zero
    /* 47B6C 80046F6C 00C04025 */  or         $t0, $a2, $zero
  .L80046F70:
    /* 47B70 80046F70 C4E40000 */  lwc1       $ft0, 0x0($a3)
    /* 47B74 80046F74 C5060000 */  lwc1       $ft1, 0x0($t0)
    /* 47B78 80046F78 24420001 */  addiu      $v0, $v0, 0x1
    /* 47B7C 80046F7C 24630004 */  addiu      $v1, $v1, 0x4
    /* 47B80 80046F80 46062201 */  sub.s      $ft2, $ft0, $ft1
    /* 47B84 80046F84 24E70004 */  addiu      $a3, $a3, 0x4
    /* 47B88 80046F88 25080004 */  addiu      $t0, $t0, 0x4
    /* 47B8C 80046F8C 1444FFF8 */  bne        $v0, $a0, .L80046F70
    /* 47B90 80046F90 E468FFFC */   swc1      $ft2, -0x4($v1)
    /* 47B94 80046F94 03E00008 */  jr         $ra
    /* 47B98 80046F98 00000000 */   nop
endlabel func_80046F5C

nonmatching func_80046F9C, 0x30

glabel func_80046F9C
    /* 47B9C 80046F9C 00801825 */  or         $v1, $a0, $zero
    /* 47BA0 80046FA0 24040003 */  addiu      $a0, $zero, 0x3
    /* 47BA4 80046FA4 00001025 */  or         $v0, $zero, $zero
    /* 47BA8 80046FA8 00A03025 */  or         $a2, $a1, $zero
  .L80046FAC:
    /* 47BAC 80046FAC C4C40000 */  lwc1       $ft0, 0x0($a2)
    /* 47BB0 80046FB0 24420001 */  addiu      $v0, $v0, 0x1
    /* 47BB4 80046FB4 24630004 */  addiu      $v1, $v1, 0x4
    /* 47BB8 80046FB8 24C60004 */  addiu      $a2, $a2, 0x4
    /* 47BBC 80046FBC 1444FFFB */  bne        $v0, $a0, .L80046FAC
    /* 47BC0 80046FC0 E464FFFC */   swc1      $ft0, -0x4($v1)
    /* 47BC4 80046FC4 03E00008 */  jr         $ra
    /* 47BC8 80046FC8 00000000 */   nop
endlabel func_80046F9C

nonmatching func_80046FCC, 0x18

glabel func_80046FCC
    /* 47BCC 80046FCC 44800000 */  mtc1       $zero, $fv0
    /* 47BD0 80046FD0 00000000 */  nop
    /* 47BD4 80046FD4 E4800008 */  swc1       $fv0, 0x8($a0)
    /* 47BD8 80046FD8 E4800004 */  swc1       $fv0, 0x4($a0)
    /* 47BDC 80046FDC 03E00008 */  jr         $ra
    /* 47BE0 80046FE0 E4800000 */   swc1      $fv0, 0x0($a0)
endlabel func_80046FCC

nonmatching func_80046FE4, 0xB4

glabel func_80046FE4
    /* 47BE4 80046FE4 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 47BE8 80046FE8 AFA60030 */  sw         $a2, 0x30($sp)
    /* 47BEC 80046FEC 00063400 */  sll        $a2, $a2, 16
    /* 47BF0 80046FF0 00063403 */  sra        $a2, $a2, 16
    /* 47BF4 80046FF4 AFA40028 */  sw         $a0, 0x28($sp)
    /* 47BF8 80046FF8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 47BFC 80046FFC 30C4FFFF */  andi       $a0, $a2, 0xFFFF
    /* 47C00 80047000 AFA4001C */  sw         $a0, 0x1C($sp)
    /* 47C04 80047004 0C025CCC */  jal        func_80097330
    /* 47C08 80047008 AFA5002C */   sw        $a1, 0x2C($sp)
    /* 47C0C 8004700C 44822000 */  mtc1       $v0, $ft0
    /* 47C10 80047010 3C014700 */  lui        $at, (0x47000000 >> 16)
    /* 47C14 80047014 44814000 */  mtc1       $at, $ft2
    /* 47C18 80047018 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 47C1C 8004701C 8FA4001C */  lw         $a0, 0x1C($sp)
    /* 47C20 80047020 46083083 */  div.s      $fv1, $ft1, $ft2
    /* 47C24 80047024 0C028E94 */  jal        func_800A3A50
    /* 47C28 80047028 E7A20024 */   swc1      $fv1, 0x24($sp)
    /* 47C2C 8004702C 44825000 */  mtc1       $v0, $ft3
    /* 47C30 80047030 3C014700 */  lui        $at, (0x47000000 >> 16)
    /* 47C34 80047034 44819000 */  mtc1       $at, $ft5
    /* 47C38 80047038 46805420 */  cvt.s.w    $ft4, $ft3
    /* 47C3C 8004703C 8FA5002C */  lw         $a1, 0x2C($sp)
    /* 47C40 80047040 C7A20024 */  lwc1       $fv1, 0x24($sp)
    /* 47C44 80047044 8FA30028 */  lw         $v1, 0x28($sp)
    /* 47C48 80047048 C4A40000 */  lwc1       $ft0, 0x0($a1)
    /* 47C4C 8004704C C4A80008 */  lwc1       $ft2, 0x8($a1)
    /* 47C50 80047050 46128003 */  div.s      $fv0, $ft4, $ft5
    /* 47C54 80047054 00601025 */  or         $v0, $v1, $zero
    /* 47C58 80047058 46002182 */  mul.s      $ft1, $ft0, $fv0
    /* 47C5C 8004705C 00000000 */  nop
    /* 47C60 80047060 46024282 */  mul.s      $ft3, $ft2, $fv1
    /* 47C64 80047064 460A3401 */  sub.s      $ft4, $ft1, $ft3
    /* 47C68 80047068 E4700000 */  swc1       $ft4, 0x0($v1)
    /* 47C6C 8004706C C4B20008 */  lwc1       $ft5, 0x8($a1)
    /* 47C70 80047070 C4A80000 */  lwc1       $ft2, 0x0($a1)
    /* 47C74 80047074 46009102 */  mul.s      $ft0, $ft5, $fv0
    /* 47C78 80047078 00000000 */  nop
    /* 47C7C 8004707C 46024182 */  mul.s      $ft1, $ft2, $fv1
    /* 47C80 80047080 46062280 */  add.s      $ft3, $ft0, $ft1
    /* 47C84 80047084 E46A0008 */  swc1       $ft3, 0x8($v1)
    /* 47C88 80047088 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 47C8C 8004708C 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 47C90 80047090 03E00008 */  jr         $ra
    /* 47C94 80047094 00000000 */   nop
endlabel func_80046FE4

nonmatching func_80047098, 0xB4

glabel func_80047098
    /* 47C98 80047098 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 47C9C 8004709C AFA60030 */  sw         $a2, 0x30($sp)
    /* 47CA0 800470A0 00063400 */  sll        $a2, $a2, 16
    /* 47CA4 800470A4 00063403 */  sra        $a2, $a2, 16
    /* 47CA8 800470A8 AFA40028 */  sw         $a0, 0x28($sp)
    /* 47CAC 800470AC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 47CB0 800470B0 30C4FFFF */  andi       $a0, $a2, 0xFFFF
    /* 47CB4 800470B4 AFA4001C */  sw         $a0, 0x1C($sp)
    /* 47CB8 800470B8 0C025CCC */  jal        func_80097330
    /* 47CBC 800470BC AFA5002C */   sw        $a1, 0x2C($sp)
    /* 47CC0 800470C0 44822000 */  mtc1       $v0, $ft0
    /* 47CC4 800470C4 3C014700 */  lui        $at, (0x47000000 >> 16)
    /* 47CC8 800470C8 44814000 */  mtc1       $at, $ft2
    /* 47CCC 800470CC 468021A0 */  cvt.s.w    $ft1, $ft0
    /* 47CD0 800470D0 8FA4001C */  lw         $a0, 0x1C($sp)
    /* 47CD4 800470D4 46083083 */  div.s      $fv1, $ft1, $ft2
    /* 47CD8 800470D8 0C028E94 */  jal        func_800A3A50
    /* 47CDC 800470DC E7A20024 */   swc1      $fv1, 0x24($sp)
    /* 47CE0 800470E0 44825000 */  mtc1       $v0, $ft3
    /* 47CE4 800470E4 3C014700 */  lui        $at, (0x47000000 >> 16)
    /* 47CE8 800470E8 44819000 */  mtc1       $at, $ft5
    /* 47CEC 800470EC 46805420 */  cvt.s.w    $ft4, $ft3
    /* 47CF0 800470F0 8FA5002C */  lw         $a1, 0x2C($sp)
    /* 47CF4 800470F4 C7A20024 */  lwc1       $fv1, 0x24($sp)
    /* 47CF8 800470F8 8FA30028 */  lw         $v1, 0x28($sp)
    /* 47CFC 800470FC C4A40000 */  lwc1       $ft0, 0x0($a1)
    /* 47D00 80047100 C4A80004 */  lwc1       $ft2, 0x4($a1)
    /* 47D04 80047104 46128003 */  div.s      $fv0, $ft4, $ft5
    /* 47D08 80047108 00601025 */  or         $v0, $v1, $zero
    /* 47D0C 8004710C 46002182 */  mul.s      $ft1, $ft0, $fv0
    /* 47D10 80047110 00000000 */  nop
    /* 47D14 80047114 46024282 */  mul.s      $ft3, $ft2, $fv1
    /* 47D18 80047118 460A3401 */  sub.s      $ft4, $ft1, $ft3
    /* 47D1C 8004711C E4700000 */  swc1       $ft4, 0x0($v1)
    /* 47D20 80047120 C4B20004 */  lwc1       $ft5, 0x4($a1)
    /* 47D24 80047124 C4A80000 */  lwc1       $ft2, 0x0($a1)
    /* 47D28 80047128 46009102 */  mul.s      $ft0, $ft5, $fv0
    /* 47D2C 8004712C 00000000 */  nop
    /* 47D30 80047130 46024182 */  mul.s      $ft1, $ft2, $fv1
    /* 47D34 80047134 46062280 */  add.s      $ft3, $ft0, $ft1
    /* 47D38 80047138 E46A0004 */  swc1       $ft3, 0x4($v1)
    /* 47D3C 8004713C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 47D40 80047140 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 47D44 80047144 03E00008 */  jr         $ra
    /* 47D48 80047148 00000000 */   nop
endlabel func_80047098

nonmatching func_8004714C, 0x30

glabel func_8004714C
    /* 47D4C 8004714C C4840000 */  lwc1       $ft0, 0x0($a0)
    /* 47D50 80047150 C4A60000 */  lwc1       $ft1, 0x0($a1)
    /* 47D54 80047154 C48A0008 */  lwc1       $ft3, 0x8($a0)
    /* 47D58 80047158 C4B00008 */  lwc1       $ft4, 0x8($a1)
    /* 47D5C 8004715C 46062202 */  mul.s      $ft2, $ft0, $ft1
    /* 47D60 80047160 C4A60004 */  lwc1       $ft1, 0x4($a1)
    /* 47D64 80047164 46105482 */  mul.s      $ft5, $ft3, $ft4
    /* 47D68 80047168 C48A0004 */  lwc1       $ft3, 0x4($a0)
    /* 47D6C 8004716C 460A3402 */  mul.s      $ft4, $ft1, $ft3
    /* 47D70 80047170 46124100 */  add.s      $ft0, $ft2, $ft5
    /* 47D74 80047174 03E00008 */  jr         $ra
    /* 47D78 80047178 46048000 */   add.s     $fv0, $ft4, $ft0
endlabel func_8004714C

nonmatching func_8004717C, 0x70

glabel func_8004717C
    /* 47D7C 8004717C C4840004 */  lwc1       $ft0, 0x4($a0)
    /* 47D80 80047180 C4A60008 */  lwc1       $ft1, 0x8($a1)
    /* 47D84 80047184 C4AA0004 */  lwc1       $ft3, 0x4($a1)
    /* 47D88 80047188 C4900008 */  lwc1       $ft4, 0x8($a0)
    /* 47D8C 8004718C 46062202 */  mul.s      $ft2, $ft0, $ft1
    /* 47D90 80047190 00C01025 */  or         $v0, $a2, $zero
    /* 47D94 80047194 46105482 */  mul.s      $ft5, $ft3, $ft4
    /* 47D98 80047198 46124101 */  sub.s      $ft0, $ft2, $ft5
    /* 47D9C 8004719C E4C40000 */  swc1       $ft0, 0x0($a2)
    /* 47DA0 800471A0 C4AA0000 */  lwc1       $ft3, 0x0($a1)
    /* 47DA4 800471A4 C4860008 */  lwc1       $ft1, 0x8($a0)
    /* 47DA8 800471A8 C4920000 */  lwc1       $ft5, 0x0($a0)
    /* 47DAC 800471AC C4A80008 */  lwc1       $ft2, 0x8($a1)
    /* 47DB0 800471B0 460A3402 */  mul.s      $ft4, $ft1, $ft3
    /* 47DB4 800471B4 00000000 */  nop
    /* 47DB8 800471B8 46124102 */  mul.s      $ft0, $ft2, $ft5
    /* 47DBC 800471BC 46048181 */  sub.s      $ft1, $ft4, $ft0
    /* 47DC0 800471C0 E4C60004 */  swc1       $ft1, 0x4($a2)
    /* 47DC4 800471C4 C4A80004 */  lwc1       $ft2, 0x4($a1)
    /* 47DC8 800471C8 C48A0000 */  lwc1       $ft3, 0x0($a0)
    /* 47DCC 800471CC C4840004 */  lwc1       $ft0, 0x4($a0)
    /* 47DD0 800471D0 C4B00000 */  lwc1       $ft4, 0x0($a1)
    /* 47DD4 800471D4 46085482 */  mul.s      $ft5, $ft3, $ft2
    /* 47DD8 800471D8 00000000 */  nop
    /* 47DDC 800471DC 46048182 */  mul.s      $ft1, $ft4, $ft0
    /* 47DE0 800471E0 46069281 */  sub.s      $ft3, $ft5, $ft1
    /* 47DE4 800471E4 03E00008 */  jr         $ra
    /* 47DE8 800471E8 E4CA0008 */   swc1      $ft3, 0x8($a2)
endlabel func_8004717C

nonmatching func_800471EC, 0xAC

glabel func_800471EC
    /* 47DEC 800471EC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 47DF0 800471F0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 47DF4 800471F4 C4820000 */  lwc1       $fv1, 0x0($a0)
    /* 47DF8 800471F8 C48E0004 */  lwc1       $fa1, 0x4($a0)
    /* 47DFC 800471FC C4800008 */  lwc1       $fv0, 0x8($a0)
    /* 47E00 80047200 46021102 */  mul.s      $ft0, $fv1, $fv1
    /* 47E04 80047204 AFA40018 */  sw         $a0, 0x18($sp)
    /* 47E08 80047208 460E7182 */  mul.s      $ft1, $fa1, $fa1
    /* 47E0C 8004720C 46062200 */  add.s      $ft2, $ft0, $ft1
    /* 47E10 80047210 46000282 */  mul.s      $ft3, $fv0, $fv0
    /* 47E14 80047214 0C028078 */  jal        func_800A01E0
    /* 47E18 80047218 46085300 */   add.s     $fa0, $ft3, $ft2
    /* 47E1C 8004721C 44808000 */  mtc1       $zero, $ft4
    /* 47E20 80047220 8FA40018 */  lw         $a0, 0x18($sp)
    /* 47E24 80047224 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 47E28 80047228 46100032 */  c.eq.s     $fv0, $ft4
    /* 47E2C 8004722C 00000000 */  nop
    /* 47E30 80047230 45030010 */  bc1tl      .L80047274
    /* 47E34 80047234 44800000 */   mtc1      $zero, $fv0
    /* 47E38 80047238 44819000 */  mtc1       $at, $ft5
    /* 47E3C 8004723C C4840000 */  lwc1       $ft0, 0x0($a0)
    /* 47E40 80047240 C48A0004 */  lwc1       $ft3, 0x4($a0)
    /* 47E44 80047244 46009083 */  div.s      $fv1, $ft5, $fv0
    /* 47E48 80047248 C4900008 */  lwc1       $ft4, 0x8($a0)
    /* 47E4C 8004724C 46022182 */  mul.s      $ft1, $ft0, $fv1
    /* 47E50 80047250 00000000 */  nop
    /* 47E54 80047254 46025202 */  mul.s      $ft2, $ft3, $fv1
    /* 47E58 80047258 00000000 */  nop
    /* 47E5C 8004725C 46028482 */  mul.s      $ft5, $ft4, $fv1
    /* 47E60 80047260 E4860000 */  swc1       $ft1, 0x0($a0)
    /* 47E64 80047264 E4880004 */  swc1       $ft2, 0x4($a0)
    /* 47E68 80047268 10000006 */  b          .L80047284
    /* 47E6C 8004726C E4920008 */   swc1      $ft5, 0x8($a0)
    /* 47E70 80047270 44800000 */  mtc1       $zero, $fv0
  .L80047274:
    /* 47E74 80047274 00000000 */  nop
    /* 47E78 80047278 E4800008 */  swc1       $fv0, 0x8($a0)
    /* 47E7C 8004727C E4800004 */  swc1       $fv0, 0x4($a0)
    /* 47E80 80047280 E4800000 */  swc1       $fv0, 0x0($a0)
  .L80047284:
    /* 47E84 80047284 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 47E88 80047288 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 47E8C 8004728C 00801025 */  or         $v0, $a0, $zero
    /* 47E90 80047290 03E00008 */  jr         $ra
    /* 47E94 80047294 00000000 */   nop
endlabel func_800471EC

nonmatching func_80047298, 0x4C

glabel func_80047298
    /* 47E98 80047298 44856000 */  mtc1       $a1, $fa0
    /* 47E9C 8004729C 24050003 */  addiu      $a1, $zero, 0x3
    /* 47EA0 800472A0 00001025 */  or         $v0, $zero, $zero
    /* 47EA4 800472A4 00801825 */  or         $v1, $a0, $zero
    /* 47EA8 800472A8 C4700000 */  lwc1       $ft4, 0x0($v1)
    /* 47EAC 800472AC 24420001 */  addiu      $v0, $v0, 0x1
    /* 47EB0 800472B0 460C8482 */  mul.s      $ft5, $ft4, $fa0
    /* 47EB4 800472B4 50450008 */  beql       $v0, $a1, .L800472D8
    /* 47EB8 800472B8 E4720000 */   swc1      $ft5, 0x0($v1)
  .L800472BC:
    /* 47EBC 800472BC C4700004 */  lwc1       $ft4, 0x4($v1)
    /* 47EC0 800472C0 24420001 */  addiu      $v0, $v0, 0x1
    /* 47EC4 800472C4 E4720000 */  swc1       $ft5, 0x0($v1)
    /* 47EC8 800472C8 460C8482 */  mul.s      $ft5, $ft4, $fa0
    /* 47ECC 800472CC 1445FFFB */  bne        $v0, $a1, .L800472BC
    /* 47ED0 800472D0 24630004 */   addiu     $v1, $v1, 0x4
    /* 47ED4 800472D4 E4720000 */  swc1       $ft5, 0x0($v1)
  .L800472D8:
    /* 47ED8 800472D8 24630004 */  addiu      $v1, $v1, 0x4
    /* 47EDC 800472DC 03E00008 */  jr         $ra
    /* 47EE0 800472E0 00801025 */   or        $v0, $a0, $zero
endlabel func_80047298

nonmatching func_800472E4, 0xE4

glabel func_800472E4
    /* 47EE4 800472E4 C4A00004 */  lwc1       $fv0, 0x4($a1)
    /* 47EE8 800472E8 C4A20008 */  lwc1       $fv1, 0x8($a1)
    /* 47EEC 800472EC C4C40004 */  lwc1       $ft0, 0x4($a2)
    /* 47EF0 800472F0 C4880008 */  lwc1       $ft2, 0x8($a0)
    /* 47EF4 800472F4 C4920004 */  lwc1       $ft5, 0x4($a0)
    /* 47EF8 800472F8 46002181 */  sub.s      $ft1, $ft0, $fv0
    /* 47EFC 800472FC 00E01025 */  or         $v0, $a3, $zero
    /* 47F00 80047300 46081281 */  sub.s      $ft3, $fv1, $ft2
    /* 47F04 80047304 C4C80008 */  lwc1       $ft2, 0x8($a2)
    /* 47F08 80047308 46120101 */  sub.s      $ft0, $fv0, $ft5
    /* 47F0C 8004730C 460A3402 */  mul.s      $ft4, $ft1, $ft3
    /* 47F10 80047310 46024181 */  sub.s      $ft1, $ft2, $fv1
    /* 47F14 80047314 46062282 */  mul.s      $ft3, $ft0, $ft1
    /* 47F18 80047318 460A8481 */  sub.s      $ft5, $ft4, $ft3
    /* 47F1C 8004731C E4F20000 */  swc1       $ft5, 0x0($a3)
    /* 47F20 80047320 C4860000 */  lwc1       $ft1, 0x0($a0)
    /* 47F24 80047324 C4AC0000 */  lwc1       $fa0, 0x0($a1)
    /* 47F28 80047328 C4C80008 */  lwc1       $ft2, 0x8($a2)
    /* 47F2C 8004732C C4A20008 */  lwc1       $fv1, 0x8($a1)
    /* 47F30 80047330 46066401 */  sub.s      $ft4, $fa0, $ft1
    /* 47F34 80047334 C4C60000 */  lwc1       $ft1, 0x0($a2)
    /* 47F38 80047338 C4920008 */  lwc1       $ft5, 0x8($a0)
    /* 47F3C 8004733C 46024101 */  sub.s      $ft0, $ft2, $fv1
    /* 47F40 80047340 46121201 */  sub.s      $ft2, $fv1, $ft5
    /* 47F44 80047344 46102282 */  mul.s      $ft3, $ft0, $ft4
    /* 47F48 80047348 460C3101 */  sub.s      $ft0, $ft1, $fa0
    /* 47F4C 8004734C 46044402 */  mul.s      $ft4, $ft2, $ft0
    /* 47F50 80047350 46105481 */  sub.s      $ft5, $ft3, $ft4
    /* 47F54 80047354 E4F20004 */  swc1       $ft5, 0x4($a3)
    /* 47F58 80047358 C4840004 */  lwc1       $ft0, 0x4($a0)
    /* 47F5C 8004735C C4C60000 */  lwc1       $ft1, 0x0($a2)
    /* 47F60 80047360 C4A00004 */  lwc1       $fv0, 0x4($a1)
    /* 47F64 80047364 C4AC0000 */  lwc1       $fa0, 0x0($a1)
    /* 47F68 80047368 C4920000 */  lwc1       $ft5, 0x0($a0)
    /* 47F6C 8004736C 46040281 */  sub.s      $ft3, $fv0, $ft0
    /* 47F70 80047370 C4C40004 */  lwc1       $ft0, 0x4($a2)
    /* 47F74 80047374 460C3201 */  sub.s      $ft2, $ft1, $fa0
    /* 47F78 80047378 46126181 */  sub.s      $ft1, $fa0, $ft5
    /* 47F7C 8004737C 460A4402 */  mul.s      $ft4, $ft2, $ft3
    /* 47F80 80047380 46002201 */  sub.s      $ft2, $ft0, $fv0
    /* 47F84 80047384 C4E40000 */  lwc1       $ft0, 0x0($a3)
    /* 47F88 80047388 46083282 */  mul.s      $ft3, $ft1, $ft2
    /* 47F8C 8004738C 460A8481 */  sub.s      $ft5, $ft4, $ft3
    /* 47F90 80047390 E4F20008 */  swc1       $ft5, 0x8($a3)
    /* 47F94 80047394 C4860000 */  lwc1       $ft1, 0x0($a0)
    /* 47F98 80047398 C48A0008 */  lwc1       $ft3, 0x8($a0)
    /* 47F9C 8004739C C4F00008 */  lwc1       $ft4, 0x8($a3)
    /* 47FA0 800473A0 46062202 */  mul.s      $ft2, $ft0, $ft1
    /* 47FA4 800473A4 C4860004 */  lwc1       $ft1, 0x4($a0)
    /* 47FA8 800473A8 460A8482 */  mul.s      $ft5, $ft4, $ft3
    /* 47FAC 800473AC C4F00004 */  lwc1       $ft4, 0x4($a3)
    /* 47FB0 800473B0 46103282 */  mul.s      $ft3, $ft1, $ft4
    /* 47FB4 800473B4 46124100 */  add.s      $ft0, $ft2, $ft5
    /* 47FB8 800473B8 46045200 */  add.s      $ft2, $ft3, $ft0
    /* 47FBC 800473BC 46004487 */  neg.s      $ft5, $ft2
    /* 47FC0 800473C0 03E00008 */  jr         $ra
    /* 47FC4 800473C4 E4F2000C */   swc1      $ft5, 0xC($a3)
endlabel func_800472E4

nonmatching func_800473C8, 0x8

glabel func_800473C8
    /* 47FC8 800473C8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 47FCC 800473CC AFBF0014 */  sw         $ra, 0x14($sp)
endlabel func_800473C8
