.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800473D0, 0x17C

glabel func_800473D0
    jr $ra
    nop
  .L800474D0:
    jr $ra
    nop
endlabel func_800473D0

nonmatching func_8004754C, 0x3C

glabel func_8004754C
    jr $ra
    nop
endlabel func_8004754C

nonmatching func_80047588, 0x8C

glabel func_80047588
    jr $ra
    nop
  .L800475B4:
    jr $ra
    nop
  .L800475F4:
    jr $ra
    nop
  .L80047604:
    jr $ra
    nop
endlabel func_80047588
    /* 48214 80047614 00000000 */  nop
    /* 48218 80047618 00000000 */  nop
    /* 4821C 8004761C 00000000 */  nop

nonmatching func_80047620, 0x100

glabel func_80047620
    jr $ra
    nop
  .L800476F8:
    jr $ra
    nop
  .L8004770C:
    jr $ra
    nop
  .L80047710:
    jr $ra
    nop
endlabel func_80047620

nonmatching func_80047720, 0x80

glabel func_80047720
    jr $ra
    nop
  .L80047758:
    jr $ra
    nop
endlabel func_80047720
