.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80049710, 0x4C

glabel func_80049710
    /* 4A310 80049710 8FA5029C */  lw         $a1, 0x29C($sp)
    /* 4A314 80049714 4600503E */  c.le.s     $ft3, $fv0
    /* 4A318 80049718 00000000 */  nop
# PATCHED: # PATCHED: /* 4A31C 8004971C 4502000F */  bc1fl      D_8004975C
    nop
    nop
    /* 4A320 80049720 C7B000F8 */   lwc1      $ft4, 0xF8($sp)
    /* 4A324 80049724 C4A40014 */  lwc1       $ft0, 0x14($a1)
    /* 4A328 80049728 C61200C4 */  lwc1       $ft5, 0xC4($s0)
    /* 4A32C 8004972C C4A80010 */  lwc1       $ft2, 0x10($a1)
    /* 4A330 80049730 C7A600F8 */  lwc1       $ft1, 0xF8($sp)
    /* 4A334 80049734 46122002 */  mul.s      $fv0, $ft0, $ft5
    /* 4A338 80049738 C7A40100 */  lwc1       $ft0, 0x100($sp)
    /* 4A33C 8004973C 46004402 */  mul.s      $ft4, $ft2, $fv0
    /* 4A340 80049740 46103281 */  sub.s      $ft3, $ft1, $ft4
    /* 4A344 80049744 E7AA00F8 */  swc1       $ft3, 0xF8($sp)
    /* 4A348 80049748 C4B20018 */  lwc1       $ft5, 0x18($a1)
    /* 4A34C 8004974C 46009202 */  mul.s      $ft2, $ft5, $fv0
    /* 4A350 80049750 46082181 */  sub.s      $ft1, $ft0, $ft2
    /* 4A354 80049754 E7A60100 */  swc1       $ft1, 0x100($sp)
    /* 4A358 80049758 C7B000F8 */  lwc1       $ft4, 0xF8($sp)
endlabel func_80049710

nonmatching D_8004975C, 0x14

glabel D_8004975C
    /* 4A35C 8004975C E6300050 */  swc1       $ft4, 0x50($s1)
    /* 4A360 80049760 C7AA0100 */  lwc1       $ft3, 0x100($sp)
# PATCHED: # PATCHED: /* 4A364 80049764 10000012 */  b          D_800497B0
    nop
    nop
    /* 4A368 80049768 E62A0058 */   swc1      $ft3, 0x58($s1)
    /* 4A36C 8004976C 920F00A5 */  lbu        $t7, 0xA5($s0)
endlabel D_8004975C

nonmatching D_80049770, 0x40

glabel D_80049770
    /* 4A370 80049770 31ECFF7F */  andi       $t4, $t7, 0xFF7F
    /* 4A374 80049774 A20C00A5 */  sb         $t4, 0xA5($s0)
    /* 4A378 80049778 358B0008 */  ori        $t3, $t4, 0x8
    /* 4A37C 8004977C A20B00A5 */  sb         $t3, 0xA5($s0)
    /* 4A380 80049780 C6320050 */  lwc1       $ft5, 0x50($s1)
    /* 4A384 80049784 C7A400E0 */  lwc1       $ft0, 0xE0($sp)
    /* 4A388 80049788 C6260054 */  lwc1       $ft1, 0x54($s1)
    /* 4A38C 8004978C 46049200 */  add.s      $ft2, $ft5, $ft0
    /* 4A390 80049790 C6320058 */  lwc1       $ft5, 0x58($s1)
    /* 4A394 80049794 E6280050 */  swc1       $ft2, 0x50($s1)
    /* 4A398 80049798 C7B000E4 */  lwc1       $ft4, 0xE4($sp)
    /* 4A39C 8004979C 46103280 */  add.s      $ft3, $ft1, $ft4
    /* 4A3A0 800497A0 E62A0054 */  swc1       $ft3, 0x54($s1)
    /* 4A3A4 800497A4 C7A400E8 */  lwc1       $ft0, 0xE8($sp)
    /* 4A3A8 800497A8 46049200 */  add.s      $ft2, $ft5, $ft0
    /* 4A3AC 800497AC E6280058 */  swc1       $ft2, 0x58($s1)
endlabel D_80049770

nonmatching D_800497B0, 0x4

glabel D_800497B0
    /* 4A3B0 800497B0 960A00A8 */  lhu        $t2, 0xA8($s0)
endlabel D_800497B0

nonmatching D_800497B4, 0x28

glabel D_800497B4
    /* 4A3B4 800497B4 31580001 */  andi       $t8, $t2, 0x1
    /* 4A3B8 800497B8 57000005 */  bnel       $t8, $zero, .L800497D0
    /* 4A3BC 800497BC 87B900D6 */   lh        $t9, 0xD6($sp)
    /* 4A3C0 800497C0 44803000 */  mtc1       $zero, $ft1
    /* 4A3C4 800497C4 00000000 */  nop
    /* 4A3C8 800497C8 E60600BC */  swc1       $ft1, 0xBC($s0)
    /* 4A3CC 800497CC 87B900D6 */  lh         $t9, 0xD6($sp)
  .L800497D0:
    /* 4A3D0 800497D0 44998000 */  mtc1       $t9, $ft4
    /* 4A3D4 800497D4 00000000 */  nop
    /* 4A3D8 800497D8 46808020 */  cvt.s.w    $fv0, $ft4
endlabel D_800497B4

nonmatching D_800497DC, 0x14

glabel D_800497DC
    /* 4A3DC 800497DC 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 4A3E0 800497E0 8FB0001C */  lw         $s0, 0x1C($sp)
    /* 4A3E4 800497E4 8FB10020 */  lw         $s1, 0x20($sp)
    /* 4A3E8 800497E8 03E00008 */  jr         $ra
    /* 4A3EC 800497EC 27BD02A8 */   addiu     $sp, $sp, 0x2A8
endlabel D_800497DC

nonmatching func_800497F0, 0x4F0

glabel func_800497F0
    /* 4A3F0 800497F0 27BDFE08 */  addiu      $sp, $sp, -0x1F8
    /* 4A3F4 800497F4 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 4A3F8 800497F8 AFB00020 */  sw         $s0, 0x20($sp)
    /* 4A3FC 800497FC AFA401F8 */  sw         $a0, 0x1F8($sp)
    /* 4A400 80049800 AFA501FC */  sw         $a1, 0x1FC($sp)
    /* 4A404 80049804 44806000 */  mtc1       $zero, $fa0
    /* 4A408 80049808 8CE30024 */  lw         $v1, 0x24($a3)
    /* 4A40C 8004980C 00C08025 */  or         $s0, $a2, $zero
    /* 4A410 80049810 00C02825 */  or         $a1, $a2, $zero
    /* 4A414 80049814 24C40094 */  addiu      $a0, $a2, 0x94
    /* 4A418 80049818 00E03025 */  or         $a2, $a3, $zero
    /* 4A41C 8004981C E7AC0054 */  swc1       $fa0, 0x54($sp)
    /* 4A420 80049820 0C012268 */  jal        func_800489A0
    /* 4A424 80049824 AFA301F0 */   sw        $v1, 0x1F0($sp)
    /* 4A428 80049828 920E00AB */  lbu        $t6, 0xAB($s0)
    /* 4A42C 8004982C 921800A8 */  lbu        $t8, 0xA8($s0)
    /* 4A430 80049830 920800AA */  lbu        $t0, 0xAA($s0)
    /* 4A434 80049834 8FA301F0 */  lw         $v1, 0x1F0($sp)
    /* 4A438 80049838 44806000 */  mtc1       $zero, $fa0
    /* 4A43C 8004983C 31CFFFFB */  andi       $t7, $t6, 0xFFFB
    /* 4A440 80049840 3319FFFB */  andi       $t9, $t8, 0xFFFB
    /* 4A444 80049844 31090001 */  andi       $t1, $t0, 0x1
    /* 4A448 80049848 A20F00AB */  sb         $t7, 0xAB($s0)
    /* 4A44C 8004984C 1520001B */  bnez       $t1, .L800498BC
    /* 4A450 80049850 A21900A8 */   sb        $t9, 0xA8($s0)
    /* 4A454 80049854 8E0200A8 */  lw         $v0, 0xA8($s0)
    /* 4A458 80049858 000258C0 */  sll        $t3, $v0, 3
    /* 4A45C 8004985C 05600017 */  bltz       $t3, .L800498BC
    /* 4A460 80049860 00026C40 */   sll       $t5, $v0, 17
    /* 4A464 80049864 05A00015 */  bltz       $t5, .L800498BC
    /* 4A468 80049868 00027C80 */   sll       $t7, $v0, 18
    /* 4A46C 8004986C 05E00013 */  bltz       $t7, .L800498BC
    /* 4A470 80049870 0002C840 */   sll       $t9, $v0, 1
    /* 4A474 80049874 07200011 */  bltz       $t9, .L800498BC
    /* 4A478 80049878 00024900 */   sll       $t1, $v0, 4
    /* 4A47C 8004987C 05220010 */  bltzl      $t1, .L800498C0
    /* 4A480 80049880 8E0C00A4 */   lw        $t4, 0xA4($s0)
    /* 4A484 80049884 44808000 */  mtc1       $zero, $ft4
    /* 4A488 80049888 C6040098 */  lwc1       $ft0, 0x98($s0)
    /* 4A48C 8004988C 00025E80 */  sll        $t3, $v0, 26
    /* 4A490 80049890 46048032 */  c.eq.s     $ft4, $ft0
    /* 4A494 80049894 00000000 */  nop
    /* 4A498 80049898 45020009 */  bc1fl      .L800498C0
    /* 4A49C 8004989C 8E0C00A4 */   lw        $t4, 0xA4($s0)
    /* 4A4A0 800498A0 05620007 */  bltzl      $t3, .L800498C0
    /* 4A4A4 800498A4 8E0C00A4 */   lw        $t4, 0xA4($s0)
    /* 4A4A8 800498A8 C60600C0 */  lwc1       $ft1, 0xC0($s0)
    /* 4A4AC 800498AC 4606803C */  c.lt.s     $ft4, $ft1
    /* 4A4B0 800498B0 00000000 */  nop
    /* 4A4B4 800498B4 45030006 */  bc1tl      .L800498D0
    /* 4A4B8 800498B8 920F00A5 */   lbu       $t7, 0xA5($s0)
  .L800498BC:
    /* 4A4BC 800498BC 8E0C00A4 */  lw         $t4, 0xA4($s0)
  .L800498C0:
    /* 4A4C0 800498C0 000C7240 */  sll        $t6, $t4, 9
    /* 4A4C4 800498C4 05C3000B */  bgezl      $t6, .L800498F4
    /* 4A4C8 800498C8 920C00A8 */   lbu       $t4, 0xA8($s0)
    /* 4A4CC 800498CC 920F00A5 */  lbu        $t7, 0xA5($s0)
  .L800498D0:
    /* 4A4D0 800498D0 31F8FFBF */  andi       $t8, $t7, 0xFFBF
    /* 4A4D4 800498D4 A21800A5 */  sb         $t8, 0xA5($s0)
    /* 4A4D8 800498D8 8E1900A4 */  lw         $t9, 0xA4($s0)
    /* 4A4DC 800498DC 00194940 */  sll        $t1, $t9, 5
    /* 4A4E0 800498E0 05220004 */  bltzl      $t1, .L800498F4
    /* 4A4E4 800498E4 920C00A8 */   lbu       $t4, 0xA8($s0)
    /* 4A4E8 800498E8 100000F8 */  b          .L80049CCC
    /* 4A4EC 800498EC 46006006 */   mov.s     $fv0, $fa0
    /* 4A4F0 800498F0 920C00A8 */  lbu        $t4, 0xA8($s0)
  .L800498F4:
    /* 4A4F4 800498F4 920A00A4 */  lbu        $t2, 0xA4($s0)
    /* 4A4F8 800498F8 C60800C8 */  lwc1       $ft2, 0xC8($s0)
    /* 4A4FC 800498FC 318EFFBF */  andi       $t6, $t4, 0xFFBF
    /* 4A500 80049900 31D800DF */  andi       $t8, $t6, 0xDF
    /* 4A504 80049904 A20E00A8 */  sb         $t6, 0xA8($s0)
    /* 4A508 80049908 330800EF */  andi       $t0, $t8, 0xEF
    /* 4A50C 8004990C A21800A8 */  sb         $t8, 0xA8($s0)
    /* 4A510 80049910 A20800A8 */  sb         $t0, 0xA8($s0)
    /* 4A514 80049914 310900F7 */  andi       $t1, $t0, 0xF7
    /* 4A518 80049918 314BFFFB */  andi       $t3, $t2, 0xFFFB
    /* 4A51C 8004991C A20B00A4 */  sb         $t3, 0xA4($s0)
    /* 4A520 80049920 A20900A8 */  sb         $t1, 0xA8($s0)
    /* 4A524 80049924 E60800C0 */  swc1       $ft2, 0xC0($s0)
    /* 4A528 80049928 C46A0050 */  lwc1       $ft3, 0x50($v1)
    /* 4A52C 8004992C C6120094 */  lwc1       $ft5, 0x94($s0)
    /* 4A530 80049930 3C01BF80 */  lui        $at, (0xBF800000 >> 16)
    /* 4A534 80049934 44810000 */  mtc1       $at, $fv0
    /* 4A538 80049938 46125100 */  add.s      $ft0, $ft3, $ft5
    /* 4A53C 8004993C 3C0140C0 */  lui        $at, (0x40C00000 >> 16)
    /* 4A540 80049940 27A40058 */  addiu      $a0, $sp, 0x58
    /* 4A544 80049944 E7A40058 */  swc1       $ft0, 0x58($sp)
    /* 4A548 80049948 C6080098 */  lwc1       $ft2, 0x98($s0)
    /* 4A54C 8004994C C4660054 */  lwc1       $ft1, 0x54($v1)
    /* 4A550 80049950 46083280 */  add.s      $ft3, $ft1, $ft2
    /* 4A554 80049954 E7AA005C */  swc1       $ft3, 0x5C($sp)
    /* 4A558 80049958 C604009C */  lwc1       $ft0, 0x9C($s0)
    /* 4A55C 8004995C C4720058 */  lwc1       $ft5, 0x58($v1)
    /* 4A560 80049960 46049180 */  add.s      $ft1, $ft5, $ft0
    /* 4A564 80049964 E7A60060 */  swc1       $ft1, 0x60($sp)
    /* 4A568 80049968 8E0A00A4 */  lw         $t2, 0xA4($s0)
    /* 4A56C 8004996C 000A6040 */  sll        $t4, $t2, 1
    /* 4A570 80049970 05820006 */  bltzl      $t4, .L8004998C
    /* 4A574 80049974 46006006 */   mov.s     $fv0, $fa0
    /* 4A578 80049978 8E0D00A8 */  lw         $t5, 0xA8($s0)
    /* 4A57C 8004997C 000D7C80 */  sll        $t7, $t5, 18
    /* 4A580 80049980 05E30003 */  bgezl      $t7, .L80049990
    /* 4A584 80049984 920300A4 */   lbu       $v1, 0xA4($s0)
    /* 4A588 80049988 46006006 */  mov.s      $fv0, $fa0
  .L8004998C:
    /* 4A58C 8004998C 920300A4 */  lbu        $v1, 0xA4($s0)
  .L80049990:
    /* 4A590 80049990 30620001 */  andi       $v0, $v1, 0x1
    /* 4A594 80049994 54400006 */  bnel       $v0, $zero, .L800499B0
    /* 4A598 80049998 44810000 */   mtc1      $at, $fv0
    /* 4A59C 8004999C 8E1800A8 */  lw         $t8, 0xA8($s0)
    /* 4A5A0 800499A0 00184440 */  sll        $t0, $t8, 17
    /* 4A5A4 800499A4 05030009 */  bgezl      $t0, .L800499CC
    /* 4A5A8 800499A8 C60200C8 */   lwc1      $fv1, 0xC8($s0)
    /* 4A5AC 800499AC 44810000 */  mtc1       $at, $fv0
  .L800499B0:
    /* 4A5B0 800499B0 50400006 */  beql       $v0, $zero, .L800499CC
    /* 4A5B4 800499B4 C60200C8 */   lwc1      $fv1, 0xC8($s0)
    /* 4A5B8 800499B8 920A00A5 */  lbu        $t2, 0xA5($s0)
    /* 4A5BC 800499BC 920300A4 */  lbu        $v1, 0xA4($s0)
    /* 4A5C0 800499C0 354B0010 */  ori        $t3, $t2, 0x10
    /* 4A5C4 800499C4 A20B00A5 */  sb         $t3, 0xA5($s0)
    /* 4A5C8 800499C8 C60200C8 */  lwc1       $fv1, 0xC8($s0)
  .L800499CC:
    /* 4A5CC 800499CC 306CFFBF */  andi       $t4, $v1, 0xFFBF
    /* 4A5D0 800499D0 A20C00A4 */  sb         $t4, 0xA4($s0)
    /* 4A5D4 800499D4 46021200 */  add.s      $ft2, $fv1, $fv1
    /* 4A5D8 800499D8 8E0600CC */  lw         $a2, 0xCC($s0)
    /* 4A5DC 800499DC 44070000 */  mfc1       $a3, $fv0
    /* 4A5E0 800499E0 27AD0068 */  addiu      $t5, $sp, 0x68
    /* 4A5E4 800499E4 44054000 */  mfc1       $a1, $ft2
    /* 4A5E8 800499E8 0C00FDCB */  jal        func_8003F72C
    /* 4A5EC 800499EC AFAD0010 */   sw        $t5, 0x10($sp)
    /* 4A5F0 800499F0 920F00AB */  lbu        $t7, 0xAB($s0)
    /* 4A5F4 800499F4 44806000 */  mtc1       $zero, $fa0
    /* 4A5F8 800499F8 44808000 */  mtc1       $zero, $ft4
    /* 4A5FC 800499FC 35F80004 */  ori        $t8, $t7, 0x4
    /* 4A600 80049A00 A21800AB */  sb         $t8, 0xAB($s0)
    /* 4A604 80049A04 8E1900A8 */  lw         $t9, 0xA8($s0)
    /* 4A608 80049A08 001947C2 */  srl        $t0, $t9, 31
    /* 4A60C 80049A0C 550000AF */  bnel       $t0, $zero, .L80049CCC
    /* 4A610 80049A10 C7A00054 */   lwc1      $fv0, 0x54($sp)
    /* 4A614 80049A14 8FA90068 */  lw         $t1, 0x68($sp)
    /* 4A618 80049A18 E7AC004C */  swc1       $fa0, 0x4C($sp)
    /* 4A61C 80049A1C E7AC0050 */  swc1       $fa0, 0x50($sp)
    /* 4A620 80049A20 312A8000 */  andi       $t2, $t1, 0x8000
    /* 4A624 80049A24 514000A9 */  beql       $t2, $zero, .L80049CCC
    /* 4A628 80049A28 C7A00054 */   lwc1      $fv0, 0x54($sp)
    /* 4A62C 80049A2C 920C00A8 */  lbu        $t4, 0xA8($s0)
    /* 4A630 80049A30 358D0008 */  ori        $t5, $t4, 0x8
    /* 4A634 80049A34 A20D00A8 */  sb         $t5, 0xA8($s0)
    /* 4A638 80049A38 C7AA0074 */  lwc1       $ft3, 0x74($sp)
    /* 4A63C 80049A3C E7AA0054 */  swc1       $ft3, 0x54($sp)
    /* 4A640 80049A40 A60000B2 */  sh         $zero, 0xB2($s0)
    /* 4A644 80049A44 860E00B2 */  lh         $t6, 0xB2($s0)
    /* 4A648 80049A48 A60E00B0 */  sh         $t6, 0xB0($s0)
    /* 4A64C 80049A4C C7B2007C */  lwc1       $ft5, 0x7C($sp)
    /* 4A650 80049A50 C7A00084 */  lwc1       $fv0, 0x84($sp)
    /* 4A654 80049A54 46109032 */  c.eq.s     $ft5, $ft4
    /* 4A658 80049A58 00000000 */  nop
    /* 4A65C 80049A5C 45020006 */  bc1fl      .L80049A78
    /* 4A660 80049A60 C7A00084 */   lwc1      $fv0, 0x84($sp)
    /* 4A664 80049A64 46100032 */  c.eq.s     $fv0, $ft4
    /* 4A668 80049A68 00000000 */  nop
    /* 4A66C 80049A6C 45030015 */  bc1tl      .L80049AC4
    /* 4A670 80049A70 8FB80068 */   lw        $t8, 0x68($sp)
    /* 4A674 80049A74 C7A00084 */  lwc1       $fv0, 0x84($sp)
  .L80049A78:
    /* 4A678 80049A78 C7A4007C */  lwc1       $ft0, 0x7C($sp)
    /* 4A67C 80049A7C C7AE007C */  lwc1       $fa1, 0x7C($sp)
    /* 4A680 80049A80 46100032 */  c.eq.s     $fv0, $ft4
    /* 4A684 80049A84 00000000 */  nop
    /* 4A688 80049A88 45000005 */  bc1f       .L80049AA0
    /* 4A68C 80049A8C 00000000 */   nop
    /* 4A690 80049A90 46102032 */  c.eq.s     $ft0, $ft4
    /* 4A694 80049A94 00000000 */  nop
    /* 4A698 80049A98 45030007 */  bc1tl      .L80049AB8
    /* 4A69C 80049A9C A60000B0 */   sh        $zero, 0xB0($s0)
  .L80049AA0:
    /* 4A6A0 80049AA0 0C00131A */  jal        func_80004C68
    /* 4A6A4 80049AA4 46000307 */   neg.s     $fa0, $fv0
    /* 4A6A8 80049AA8 44808000 */  mtc1       $zero, $ft4
    /* 4A6AC 80049AAC 10000002 */  b          .L80049AB8
    /* 4A6B0 80049AB0 A60200B0 */   sh        $v0, 0xB0($s0)
    /* 4A6B4 80049AB4 A60000B0 */  sh         $zero, 0xB0($s0)
  .L80049AB8:
    /* 4A6B8 80049AB8 860F00B0 */  lh         $t7, 0xB0($s0)
    /* 4A6BC 80049ABC A60F00B2 */  sh         $t7, 0xB2($s0)
    /* 4A6C0 80049AC0 8FB80068 */  lw         $t8, 0x68($sp)
  .L80049AC4:
    /* 4A6C4 80049AC4 C7A600D4 */  lwc1       $ft1, 0xD4($sp)
    /* 4A6C8 80049AC8 33190800 */  andi       $t9, $t8, 0x800
    /* 4A6CC 80049ACC 5320001C */  beql       $t9, $zero, .L80049B40
    /* 4A6D0 80049AD0 87A501FA */   lh        $a1, 0x1FA($sp)
    /* 4A6D4 80049AD4 C60800C8 */  lwc1       $ft2, 0xC8($s0)
    /* 4A6D8 80049AD8 C7AA007C */  lwc1       $ft3, 0x7C($sp)
    /* 4A6DC 80049ADC C7B200DC */  lwc1       $ft5, 0xDC($sp)
    /* 4A6E0 80049AE0 4608303C */  c.lt.s     $ft1, $ft2
    /* 4A6E4 80049AE4 C7A600E4 */  lwc1       $ft1, 0xE4($sp)
    /* 4A6E8 80049AE8 45020015 */  bc1fl      .L80049B40
    /* 4A6EC 80049AEC 87A501FA */   lh        $a1, 0x1FA($sp)
    /* 4A6F0 80049AF0 46125380 */  add.s      $fa1, $ft3, $ft5
    /* 4A6F4 80049AF4 E7B20050 */  swc1       $ft5, 0x50($sp)
    /* 4A6F8 80049AF8 E7A6004C */  swc1       $ft1, 0x4C($sp)
    /* 4A6FC 80049AFC 920900A8 */  lbu        $t1, 0xA8($s0)
    /* 4A700 80049B00 46107032 */  c.eq.s     $fa1, $ft4
    /* 4A704 80049B04 C7A40084 */  lwc1       $ft0, 0x84($sp)
    /* 4A708 80049B08 352A0020 */  ori        $t2, $t1, 0x20
    /* 4A70C 80049B0C A20A00A8 */  sb         $t2, 0xA8($s0)
    /* 4A710 80049B10 45000005 */  bc1f       .L80049B28
    /* 4A714 80049B14 46062000 */   add.s     $fv0, $ft0, $ft1
    /* 4A718 80049B18 46100032 */  c.eq.s     $fv0, $ft4
    /* 4A71C 80049B1C 00000000 */  nop
    /* 4A720 80049B20 45030006 */  bc1tl      .L80049B3C
    /* 4A724 80049B24 A60000B0 */   sh        $zero, 0xB0($s0)
  .L80049B28:
    /* 4A728 80049B28 0C00131A */  jal        func_80004C68
    /* 4A72C 80049B2C 46000307 */   neg.s     $fa0, $fv0
    /* 4A730 80049B30 10000002 */  b          .L80049B3C
    /* 4A734 80049B34 A60200B0 */   sh        $v0, 0xB0($s0)
    /* 4A738 80049B38 A60000B0 */  sh         $zero, 0xB0($s0)
  .L80049B3C:
    /* 4A73C 80049B3C 87A501FA */  lh         $a1, 0x1FA($sp)
  .L80049B40:
    /* 4A740 80049B40 860200B0 */  lh         $v0, 0xB0($s0)
    /* 4A744 80049B44 87B901FE */  lh         $t9, 0x1FE($sp)
    /* 4A748 80049B48 34038001 */  ori        $v1, $zero, 0x8001
    /* 4A74C 80049B4C 00A25823 */  subu       $t3, $a1, $v0
    /* 4A750 80049B50 256C4000 */  addiu      $t4, $t3, 0x4000
    /* 4A754 80049B54 318DFFFF */  andi       $t5, $t4, 0xFFFF
    /* 4A758 80049B58 01A3082A */  slt        $at, $t5, $v1
    /* 4A75C 80049B5C 14200006 */  bnez       $at, .L80049B78
    /* 4A760 80049B60 03224023 */   subu      $t0, $t9, $v0
    /* 4A764 80049B64 920F00A8 */  lbu        $t7, 0xA8($s0)
    /* 4A768 80049B68 860200B0 */  lh         $v0, 0xB0($s0)
    /* 4A76C 80049B6C 35F80010 */  ori        $t8, $t7, 0x10
    /* 4A770 80049B70 1000000A */  b          .L80049B9C
    /* 4A774 80049B74 A21800A8 */   sb        $t8, 0xA8($s0)
  .L80049B78:
    /* 4A778 80049B78 25094000 */  addiu      $t1, $t0, 0x4000
    /* 4A77C 80049B7C 312AFFFF */  andi       $t2, $t1, 0xFFFF
    /* 4A780 80049B80 0143082A */  slt        $at, $t2, $v1
    /* 4A784 80049B84 54200006 */  bnel       $at, $zero, .L80049BA0
    /* 4A788 80049B88 920E00A8 */   lbu       $t6, 0xA8($s0)
    /* 4A78C 80049B8C 920C00A8 */  lbu        $t4, 0xA8($s0)
    /* 4A790 80049B90 860200B0 */  lh         $v0, 0xB0($s0)
    /* 4A794 80049B94 358D0010 */  ori        $t5, $t4, 0x10
    /* 4A798 80049B98 A20D00A8 */  sb         $t5, 0xA8($s0)
  .L80049B9C:
    /* 4A79C 80049B9C 920E00A8 */  lbu        $t6, 0xA8($s0)
  .L80049BA0:
    /* 4A7A0 80049BA0 00452023 */  subu       $a0, $v0, $a1
    /* 4A7A4 80049BA4 00042400 */  sll        $a0, $a0, 16
    /* 4A7A8 80049BA8 31CFFFFB */  andi       $t7, $t6, 0xFFFB
    /* 4A7AC 80049BAC A20F00A8 */  sb         $t7, 0xA8($s0)
    /* 4A7B0 80049BB0 0C012AA6 */  jal        func_8004AA98
    /* 4A7B4 80049BB4 00042403 */   sra       $a0, $a0, 16
    /* 4A7B8 80049BB8 44808000 */  mtc1       $zero, $ft4
    /* 4A7BC 80049BBC 24010002 */  addiu      $at, $zero, 0x2
    /* 4A7C0 80049BC0 54410006 */  bnel       $v0, $at, .L80049BDC
    /* 4A7C4 80049BC4 920900AA */   lbu       $t1, 0xAA($s0)
    /* 4A7C8 80049BC8 921900A8 */  lbu        $t9, 0xA8($s0)
    /* 4A7CC 80049BCC 37280004 */  ori        $t0, $t9, 0x4
    /* 4A7D0 80049BD0 10000004 */  b          .L80049BE4
    /* 4A7D4 80049BD4 A20800A8 */   sb        $t0, 0xA8($s0)
    /* 4A7D8 80049BD8 920900AA */  lbu        $t1, 0xAA($s0)
  .L80049BDC:
    /* 4A7DC 80049BDC 312AFF7F */  andi       $t2, $t1, 0xFF7F
    /* 4A7E0 80049BE0 A20A00AA */  sb         $t2, 0xAA($s0)
  .L80049BE4:
    /* 4A7E4 80049BE4 C60200C8 */  lwc1       $fv1, 0xC8($s0)
    /* 4A7E8 80049BE8 C7A80074 */  lwc1       $ft2, 0x74($sp)
    /* 4A7EC 80049BEC 4602403C */  c.lt.s     $ft2, $fv1
    /* 4A7F0 80049BF0 00000000 */  nop
    /* 4A7F4 80049BF4 45020031 */  bc1fl      .L80049CBC
    /* 4A7F8 80049BF8 921800AB */   lbu       $t8, 0xAB($s0)
    /* 4A7FC 80049BFC 46081001 */  sub.s      $fv0, $fv1, $ft2
    /* 4A800 80049C00 C7A4007C */  lwc1       $ft0, 0x7C($sp)
    /* 4A804 80049C04 C60A0094 */  lwc1       $ft3, 0x94($s0)
    /* 4A808 80049C08 C608009C */  lwc1       $ft2, 0x9C($s0)
    /* 4A80C 80049C0C 46002482 */  mul.s      $ft5, $ft0, $fv0
    /* 4A810 80049C10 920C00A8 */  lbu        $t4, 0xA8($s0)
    /* 4A814 80049C14 358D0040 */  ori        $t5, $t4, 0x40
    /* 4A818 80049C18 46125180 */  add.s      $ft1, $ft3, $ft5
    /* 4A81C 80049C1C E6060094 */  swc1       $ft1, 0x94($s0)
    /* 4A820 80049C20 C7A40084 */  lwc1       $ft0, 0x84($sp)
    /* 4A824 80049C24 46002282 */  mul.s      $ft3, $ft0, $fv0
    /* 4A828 80049C28 C6040094 */  lwc1       $ft0, 0x94($s0)
    /* 4A82C 80049C2C 460A4480 */  add.s      $ft5, $ft2, $ft3
    /* 4A830 80049C30 E612009C */  swc1       $ft5, 0x9C($s0)
    /* 4A834 80049C34 C7A600D4 */  lwc1       $ft1, 0xD4($sp)
    /* 4A838 80049C38 C7A80050 */  lwc1       $ft2, 0x50($sp)
    /* 4A83C 80049C3C 46061001 */  sub.s      $fv0, $fv1, $ft1
    /* 4A840 80049C40 C606009C */  lwc1       $ft1, 0x9C($s0)
    /* 4A844 80049C44 46004282 */  mul.s      $ft3, $ft2, $fv0
    /* 4A848 80049C48 460A2480 */  add.s      $ft5, $ft0, $ft3
    /* 4A84C 80049C4C E6120094 */  swc1       $ft5, 0x94($s0)
    /* 4A850 80049C50 C7A8004C */  lwc1       $ft2, 0x4C($sp)
    /* 4A854 80049C54 A20D00A8 */  sb         $t5, 0xA8($s0)
    /* 4A858 80049C58 8E0E00A8 */  lw         $t6, 0xA8($s0)
    /* 4A85C 80049C5C 46004102 */  mul.s      $ft0, $ft2, $fv0
    /* 4A860 80049C60 E61000C0 */  swc1       $ft4, 0xC0($s0)
    /* 4A864 80049C64 000EC080 */  sll        $t8, $t6, 2
    /* 4A868 80049C68 46043280 */  add.s      $ft3, $ft1, $ft0
    /* 4A86C 80049C6C 0701000E */  bgez       $t8, .L80049CA8
    /* 4A870 80049C70 E60A009C */   swc1      $ft3, 0x9C($s0)
    /* 4A874 80049C74 920800A4 */  lbu        $t0, 0xA4($s0)
    /* 4A878 80049C78 860200B6 */  lh         $v0, 0xB6($s0)
    /* 4A87C 80049C7C 35090040 */  ori        $t1, $t0, 0x40
    /* 4A880 80049C80 28410010 */  slti       $at, $v0, 0x10
    /* 4A884 80049C84 10200004 */  beqz       $at, .L80049C98
    /* 4A888 80049C88 A20900A4 */   sb        $t1, 0xA4($s0)
    /* 4A88C 80049C8C 244A0001 */  addiu      $t2, $v0, 0x1
    /* 4A890 80049C90 1000000D */  b          .L80049CC8
    /* 4A894 80049C94 A60A00B6 */   sh        $t2, 0xB6($s0)
  .L80049C98:
    /* 4A898 80049C98 920C00AB */  lbu        $t4, 0xAB($s0)
    /* 4A89C 80049C9C 358D0080 */  ori        $t5, $t4, 0x80
    /* 4A8A0 80049CA0 10000009 */  b          .L80049CC8
    /* 4A8A4 80049CA4 A20D00AB */   sb        $t5, 0xAB($s0)
  .L80049CA8:
    /* 4A8A8 80049CA8 920E00AB */  lbu        $t6, 0xAB($s0)
    /* 4A8AC 80049CAC 31CFFF7F */  andi       $t7, $t6, 0xFF7F
    /* 4A8B0 80049CB0 10000005 */  b          .L80049CC8
    /* 4A8B4 80049CB4 A20F00AB */   sb        $t7, 0xAB($s0)
    /* 4A8B8 80049CB8 921800AB */  lbu        $t8, 0xAB($s0)
  .L80049CBC:
    /* 4A8BC 80049CBC A60000B6 */  sh         $zero, 0xB6($s0)
    /* 4A8C0 80049CC0 3319FF7F */  andi       $t9, $t8, 0xFF7F
    /* 4A8C4 80049CC4 A21900AB */  sb         $t9, 0xAB($s0)
  .L80049CC8:
    /* 4A8C8 80049CC8 C7A00054 */  lwc1       $fv0, 0x54($sp)
  .L80049CCC:
    /* 4A8CC 80049CCC 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 4A8D0 80049CD0 8FB00020 */  lw         $s0, 0x20($sp)
    /* 4A8D4 80049CD4 27BD01F8 */  addiu      $sp, $sp, 0x1F8
    /* 4A8D8 80049CD8 03E00008 */  jr         $ra
    /* 4A8DC 80049CDC 00000000 */   nop
endlabel func_800497F0

nonmatching func_80049CE0, 0xAC

glabel func_80049CE0
    /* 4A8E0 80049CE0 24010003 */  addiu      $at, $zero, 0x3
    /* 4A8E4 80049CE4 0081001A */  div        $zero, $a0, $at
    /* 4A8E8 80049CE8 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 4A8EC 80049CEC 00001010 */  mfhi       $v0
    /* 4A8F0 80049CF0 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 4A8F4 80049CF4 AFA50024 */  sw         $a1, 0x24($sp)
    /* 4A8F8 80049CF8 AFA60028 */  sw         $a2, 0x28($sp)
    /* 4A8FC 80049CFC 10400009 */  beqz       $v0, .L80049D24
    /* 4A900 80049D00 AFA7002C */   sw        $a3, 0x2C($sp)
    /* 4A904 80049D04 24010001 */  addiu      $at, $zero, 0x1
    /* 4A908 80049D08 1041000C */  beq        $v0, $at, .L80049D3C
    /* 4A90C 80049D0C 8FA40024 */   lw        $a0, 0x24($sp)
    /* 4A910 80049D10 24010002 */  addiu      $at, $zero, 0x2
    /* 4A914 80049D14 10410015 */  beq        $v0, $at, .L80049D6C
    /* 4A918 80049D18 8FA40024 */   lw        $a0, 0x24($sp)
    /* 4A91C 80049D1C 10000017 */  b          .L80049D7C
    /* 4A920 80049D20 8FAF002C */   lw        $t7, 0x2C($sp)
  .L80049D24:
    /* 4A924 80049D24 8FA40024 */  lw         $a0, 0x24($sp)
    /* 4A928 80049D28 8FA50028 */  lw         $a1, 0x28($sp)
    /* 4A92C 80049D2C 0C00FC07 */  jal        func_8003F01C
    /* 4A930 80049D30 8FA6002C */   lw        $a2, 0x2C($sp)
    /* 4A934 80049D34 10000011 */  b          .L80049D7C
    /* 4A938 80049D38 8FAF002C */   lw        $t7, 0x2C($sp)
  .L80049D3C:
    /* 4A93C 80049D3C 8FAE002C */  lw         $t6, 0x2C($sp)
    /* 4A940 80049D40 3C198004 */  lui        $t9, %hi(func_8003F44C)
    /* 4A944 80049D44 2739F44C */  addiu      $t9, $t9, %lo(func_8003F44C)
    /* 4A948 80049D48 3C063C23 */  lui        $a2, (0x3C23D70A >> 16)
    /* 4A94C 80049D4C 3C07BC23 */  lui        $a3, (0xBC23D70A >> 16)
    /* 4A950 80049D50 34E7D70A */  ori        $a3, $a3, (0xBC23D70A & 0xFFFF)
    /* 4A954 80049D54 34C6D70A */  ori        $a2, $a2, (0x3C23D70A & 0xFFFF)
    /* 4A958 80049D58 8FA50028 */  lw         $a1, 0x28($sp)
    /* 4A95C 80049D5C 0320F809 */  jalr       $t9
    /* 4A960 80049D60 AFAE0010 */   sw        $t6, 0x10($sp)
    /* 4A964 80049D64 10000005 */  b          .L80049D7C
    /* 4A968 80049D68 8FAF002C */   lw        $t7, 0x2C($sp)
  .L80049D6C:
    /* 4A96C 80049D6C 8FA50028 */  lw         $a1, 0x28($sp)
    /* 4A970 80049D70 0C00FC8B */  jal        func_8003F22C
    /* 4A974 80049D74 8FA6002C */   lw        $a2, 0x2C($sp)
    /* 4A978 80049D78 8FAF002C */  lw         $t7, 0x2C($sp)
  .L80049D7C:
    /* 4A97C 80049D7C 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 4A980 80049D80 8DE20000 */  lw         $v0, 0x0($t7)
    /* 4A984 80049D84 03E00008 */  jr         $ra
    /* 4A988 80049D88 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_80049CE0

nonmatching func_80049D8C, 0x2C

glabel func_80049D8C
    /* 4A98C 80049D8C 00802825 */  or         $a1, $a0, $zero
    /* 4A990 80049D90 3C04801D */  lui        $a0, %hi(D_801CAC20)
    /* 4A994 80049D94 8C84AC20 */  lw         $a0, %lo(D_801CAC20)($a0)
    /* 4A998 80049D98 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 4A99C 80049D9C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4A9A0 80049DA0 0C01276E */  jal        func_80049DB8
    /* 4A9A4 80049DA4 24840050 */   addiu     $a0, $a0, 0x50
    /* 4A9A8 80049DA8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4A9AC 80049DAC 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 4A9B0 80049DB0 03E00008 */  jr         $ra
    /* 4A9B4 80049DB4 00000000 */   nop
endlabel func_80049D8C

nonmatching func_80049DB8, 0xE4

glabel func_80049DB8
    /* 4A9B8 80049DB8 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 4A9BC 80049DBC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4A9C0 80049DC0 8CA20024 */  lw         $v0, 0x24($a1)
    /* 4A9C4 80049DC4 C4840000 */  lwc1       $ft0, 0x0($a0)
    /* 4A9C8 80049DC8 C4880008 */  lwc1       $ft2, 0x8($a0)
    /* 4A9CC 80049DCC C4460050 */  lwc1       $ft1, 0x50($v0)
    /* 4A9D0 80049DD0 C44A0058 */  lwc1       $ft3, 0x58($v0)
    /* 4A9D4 80049DD4 46062081 */  sub.s      $fv1, $ft0, $ft1
    /* 4A9D8 80049DD8 460A4401 */  sub.s      $ft4, $ft2, $ft3
    /* 4A9DC 80049DDC 46021482 */  mul.s      $ft5, $fv1, $fv1
    /* 4A9E0 80049DE0 E7A2001C */  swc1       $fv1, 0x1C($sp)
    /* 4A9E4 80049DE4 46108102 */  mul.s      $ft0, $ft4, $ft4
    /* 4A9E8 80049DE8 E7B00018 */  swc1       $ft4, 0x18($sp)
    /* 4A9EC 80049DEC 0C028078 */  jal        func_800A01E0
    /* 4A9F0 80049DF0 46049300 */   add.s     $fa0, $ft5, $ft0
    /* 4A9F4 80049DF4 44807000 */  mtc1       $zero, $fa1
    /* 4A9F8 80049DF8 C7A2001C */  lwc1       $fv1, 0x1C($sp)
    /* 4A9FC 80049DFC C7B00018 */  lwc1       $ft4, 0x18($sp)
    /* 4AA00 80049E00 460E0032 */  c.eq.s     $fv0, $fa1
    /* 4AA04 80049E04 3C013F80 */  lui        $at, (0x3F800000 >> 16)
    /* 4AA08 80049E08 4503000A */  bc1tl      .L80049E34
    /* 4AA0C 80049E0C 44801000 */   mtc1      $zero, $fv1
    /* 4AA10 80049E10 44813000 */  mtc1       $at, $ft1
    /* 4AA14 80049E14 00000000 */  nop
    /* 4AA18 80049E18 46003303 */  div.s      $fa0, $ft1, $fv0
    /* 4AA1C 80049E1C 460C1082 */  mul.s      $fv1, $fv1, $fa0
    /* 4AA20 80049E20 00000000 */  nop
    /* 4AA24 80049E24 460C8402 */  mul.s      $ft4, $ft4, $fa0
    /* 4AA28 80049E28 10000004 */  b          .L80049E3C
    /* 4AA2C 80049E2C 00000000 */   nop
    /* 4AA30 80049E30 44801000 */  mtc1       $zero, $fv1
  .L80049E34:
    /* 4AA34 80049E34 00000000 */  nop
    /* 4AA38 80049E38 46001406 */  mov.s      $ft4, $fv1
  .L80049E3C:
    /* 4AA3C 80049E3C 460E1032 */  c.eq.s     $fv1, $fa1
    /* 4AA40 80049E40 3C014120 */  lui        $at, (0x41200000 >> 16)
    /* 4AA44 80049E44 45020006 */  bc1fl      .L80049E60
    /* 4AA48 80049E48 44810000 */   mtc1      $at, $fv0
    /* 4AA4C 80049E4C 460E8032 */  c.eq.s     $ft4, $fa1
    /* 4AA50 80049E50 00001825 */  or         $v1, $zero, $zero
    /* 4AA54 80049E54 4501000C */  bc1t       .L80049E88
    /* 4AA58 80049E58 00000000 */   nop
    /* 4AA5C 80049E5C 44810000 */  mtc1       $at, $fv0
  .L80049E60:
    /* 4AA60 80049E60 46008207 */  neg.s      $ft2, $ft4
    /* 4AA64 80049E64 3C198000 */  lui        $t9, %hi(func_80004C68)
    /* 4AA68 80049E68 46004302 */  mul.s      $fa0, $ft2, $fv0
    /* 4AA6C 80049E6C 27394C68 */  addiu      $t9, $t9, %lo(func_80004C68)
    /* 4AA70 80049E70 46001382 */  mul.s      $fa1, $fv1, $fv0
    /* 4AA74 80049E74 0320F809 */  jalr       $t9
    /* 4AA78 80049E78 00000000 */   nop
    /* 4AA7C 80049E7C 00021C00 */  sll        $v1, $v0, 16
    /* 4AA80 80049E80 10000001 */  b          .L80049E88
    /* 4AA84 80049E84 00031C03 */   sra       $v1, $v1, 16
  .L80049E88:
    /* 4AA88 80049E88 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4AA8C 80049E8C 00031400 */  sll        $v0, $v1, 16
    /* 4AA90 80049E90 00021403 */  sra        $v0, $v0, 16
    /* 4AA94 80049E94 03E00008 */  jr         $ra
    /* 4AA98 80049E98 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_80049DB8

nonmatching func_80049E9C, 0x104

glabel func_80049E9C
    /* 4AA9C 80049E9C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 4AAA0 80049EA0 AFA70024 */  sw         $a3, 0x24($sp)
    /* 4AAA4 80049EA4 00A03825 */  or         $a3, $a1, $zero
    /* 4AAA8 80049EA8 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4AAAC 80049EAC AFA40018 */  sw         $a0, 0x18($sp)
    /* 4AAB0 80049EB0 10C0001F */  beqz       $a2, .L80049F30
    /* 4AAB4 80049EB4 AFA5001C */   sw        $a1, 0x1C($sp)
    /* 4AAB8 80049EB8 84CE0000 */  lh         $t6, 0x0($a2)
    /* 4AABC 80049EBC 24010100 */  addiu      $at, $zero, 0x100
    /* 4AAC0 80049EC0 3C0C801D */  lui        $t4, %hi(D_801CAC1C)
    /* 4AAC4 80049EC4 31CF07FF */  andi       $t7, $t6, 0x7FF
    /* 4AAC8 80049EC8 15E10012 */  bne        $t7, $at, .L80049F14
    /* 4AACC 80049ECC 00000000 */   nop
    /* 4AAD0 80049ED0 8CD80060 */  lw         $t8, 0x60($a2)
    /* 4AAD4 80049ED4 3C08801D */  lui        $t0, %hi(D_801CAC1C)
    /* 4AAD8 80049ED8 0018C800 */  sll        $t9, $t8, 0
    /* 4AADC 80049EDC 07210006 */  bgez       $t9, .L80049EF8
    /* 4AAE0 80049EE0 00000000 */   nop
    /* 4AAE4 80049EE4 8CC30040 */  lw         $v1, 0x40($a2)
    /* 4AAE8 80049EE8 10600003 */  beqz       $v1, .L80049EF8
    /* 4AAEC 80049EEC 00000000 */   nop
    /* 4AAF0 80049EF0 10000016 */  b          .L80049F4C
    /* 4AAF4 80049EF4 00601025 */   or        $v0, $v1, $zero
  .L80049EF8:
    /* 4AAF8 80049EF8 8D08AC1C */  lw         $t0, %lo(D_801CAC1C)($t0)
    /* 4AAFC 80049EFC 8D090024 */  lw         $t1, 0x24($t0)
    /* 4AB00 80049F00 8D2A0014 */  lw         $t2, 0x14($t1)
    /* 4AB04 80049F04 8D4B0014 */  lw         $t3, 0x14($t2)
    /* 4AB08 80049F08 8D620014 */  lw         $v0, 0x14($t3)
    /* 4AB0C 80049F0C 1000000F */  b          .L80049F4C
    /* 4AB10 80049F10 244200A8 */   addiu     $v0, $v0, 0xA8
  .L80049F14:
    /* 4AB14 80049F14 8D8CAC1C */  lw         $t4, %lo(D_801CAC1C)($t4)
    /* 4AB18 80049F18 8D8D0024 */  lw         $t5, 0x24($t4)
    /* 4AB1C 80049F1C 8DAE0014 */  lw         $t6, 0x14($t5)
    /* 4AB20 80049F20 8DCF0014 */  lw         $t7, 0x14($t6)
    /* 4AB24 80049F24 8DE20014 */  lw         $v0, 0x14($t7)
    /* 4AB28 80049F28 10000008 */  b          .L80049F4C
    /* 4AB2C 80049F2C 244200A8 */   addiu     $v0, $v0, 0xA8
  .L80049F30:
    /* 4AB30 80049F30 3C18801D */  lui        $t8, %hi(D_801CAC1C)
    /* 4AB34 80049F34 8F18AC1C */  lw         $t8, %lo(D_801CAC1C)($t8)
    /* 4AB38 80049F38 8F190024 */  lw         $t9, 0x24($t8)
    /* 4AB3C 80049F3C 8F280014 */  lw         $t0, 0x14($t9)
    /* 4AB40 80049F40 8D090014 */  lw         $t1, 0x14($t0)
    /* 4AB44 80049F44 8D220014 */  lw         $v0, 0x14($t1)
    /* 4AB48 80049F48 244200A8 */  addiu      $v0, $v0, 0xA8
  .L80049F4C:
    /* 4AB4C 80049F4C C4440000 */  lwc1       $ft0, 0x0($v0)
    /* 4AB50 80049F50 3C0A801D */  lui        $t2, %hi(D_801CAC1C)
    /* 4AB54 80049F54 3C198001 */  lui        $t9, %hi(func_80013B9C)
    /* 4AB58 80049F58 E4E40000 */  swc1       $ft0, 0x0($a3)
    /* 4AB5C 80049F5C C4460004 */  lwc1       $ft1, 0x4($v0)
    /* 4AB60 80049F60 27393B9C */  addiu      $t9, $t9, %lo(func_80013B9C)
    /* 4AB64 80049F64 E4E60004 */  swc1       $ft1, 0x4($a3)
    /* 4AB68 80049F68 C4480008 */  lwc1       $ft2, 0x8($v0)
    /* 4AB6C 80049F6C E4E80008 */  swc1       $ft2, 0x8($a3)
    /* 4AB70 80049F70 8D4AAC1C */  lw         $t2, %lo(D_801CAC1C)($t2)
    /* 4AB74 80049F74 8FA50018 */  lw         $a1, 0x18($sp)
    /* 4AB78 80049F78 8D4B0024 */  lw         $t3, 0x24($t2)
    /* 4AB7C 80049F7C 8D6C0014 */  lw         $t4, 0x14($t3)
    /* 4AB80 80049F80 8D8D0014 */  lw         $t5, 0x14($t4)
    /* 4AB84 80049F84 8DA40014 */  lw         $a0, 0x14($t5)
    /* 4AB88 80049F88 0320F809 */  jalr       $t9
    /* 4AB8C 80049F8C 248400A8 */   addiu     $a0, $a0, 0xA8
    /* 4AB90 80049F90 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4AB94 80049F94 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 4AB98 80049F98 03E00008 */  jr         $ra
    /* 4AB9C 80049F9C 00000000 */   nop
endlabel func_80049E9C

nonmatching func_80049FA0, 0x98

glabel func_80049FA0
    /* 4ABA0 80049FA0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 4ABA4 80049FA4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4ABA8 80049FA8 AFA40018 */  sw         $a0, 0x18($sp)
    /* 4ABAC 80049FAC AFA5001C */  sw         $a1, 0x1C($sp)
    /* 4ABB0 80049FB0 0C012826 */  jal        func_8004A098
    /* 4ABB4 80049FB4 AFA60020 */   sw        $a2, 0x20($sp)
    /* 4ABB8 80049FB8 8FB9001C */  lw         $t9, 0x1C($sp)
    /* 4ABBC 80049FBC C44A00AC */  lwc1       $ft3, 0xAC($v0)
    /* 4ABC0 80049FC0 8FAF0020 */  lw         $t7, 0x20($sp)
    /* 4ABC4 80049FC4 C72800AC */  lwc1       $ft2, 0xAC($t9)
    /* 4ABC8 80049FC8 3C013F00 */  lui        $at, (0x3F000000 >> 16)
    /* 4ABCC 80049FCC 8FAE0018 */  lw         $t6, 0x18($sp)
    /* 4ABD0 80049FD0 460A4081 */  sub.s      $fv1, $ft2, $ft3
    /* 4ABD4 80049FD4 44818000 */  mtc1       $at, $ft4
    /* 4ABD8 80049FD8 8DF80024 */  lw         $t8, 0x24($t7)
    /* 4ABDC 80049FDC C5C400AC */  lwc1       $ft0, 0xAC($t6)
    /* 4ABE0 80049FE0 46101482 */  mul.s      $ft5, $fv1, $ft4
    /* 4ABE4 80049FE4 C70600AC */  lwc1       $ft1, 0xAC($t8)
    /* 4ABE8 80049FE8 3C01800C */  lui        $at, %hi(D_800BEDDC)
    /* 4ABEC 80049FEC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4ABF0 80049FF0 46062001 */  sub.s      $fv0, $ft0, $ft1
    /* 4ABF4 80049FF4 4612003E */  c.le.s     $fv0, $ft5
    /* 4ABF8 80049FF8 00000000 */  nop
    /* 4ABFC 80049FFC 45000003 */  bc1f       .L8004A00C
    /* 4AC00 8004A000 00000000 */   nop
    /* 4AC04 8004A004 1000000A */  b          .L8004A030
    /* 4AC08 8004A008 24020002 */   addiu     $v0, $zero, 0x2
  .L8004A00C:
    /* 4AC0C 8004A00C C424EDDC */  lwc1       $ft0, %lo(D_800BEDDC)($at)
    /* 4AC10 8004A010 00001025 */  or         $v0, $zero, $zero
    /* 4AC14 8004A014 46041182 */  mul.s      $ft1, $fv1, $ft0
    /* 4AC18 8004A018 4600303C */  c.lt.s     $ft1, $fv0
    /* 4AC1C 8004A01C 00000000 */  nop
    /* 4AC20 8004A020 45000003 */  bc1f       .L8004A030
    /* 4AC24 8004A024 00000000 */   nop
    /* 4AC28 8004A028 10000001 */  b          .L8004A030
    /* 4AC2C 8004A02C 24020001 */   addiu     $v0, $zero, 0x1
  .L8004A030:
    /* 4AC30 8004A030 03E00008 */  jr         $ra
    /* 4AC34 8004A034 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_80049FA0

nonmatching func_8004A038, 0x60

glabel func_8004A038
    /* 4AC38 8004A038 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 4AC3C 8004A03C AFB00018 */  sw         $s0, 0x18($sp)
    /* 4AC40 8004A040 00808025 */  or         $s0, $a0, $zero
    /* 4AC44 8004A044 1080000F */  beqz       $a0, .L8004A084
    /* 4AC48 8004A048 AFBF001C */   sw        $ra, 0x1C($sp)
    /* 4AC4C 8004A04C 960E0002 */  lhu        $t6, 0x2($s0)
  .L8004A050:
    /* 4AC50 8004A050 8E040014 */  lw         $a0, 0x14($s0)
    /* 4AC54 8004A054 39CF4000 */  xori       $t7, $t6, 0x4000
    /* 4AC58 8004A058 10800003 */  beqz       $a0, .L8004A068
    /* 4AC5C 8004A05C A60F0002 */   sh        $t7, 0x2($s0)
    /* 4AC60 8004A060 0C01280E */  jal        func_8004A038
    /* 4AC64 8004A064 00000000 */   nop
  .L8004A068:
    /* 4AC68 8004A068 86180000 */  lh         $t8, 0x0($s0)
    /* 4AC6C 8004A06C 33190800 */  andi       $t9, $t8, 0x800
    /* 4AC70 8004A070 57200005 */  bnel       $t9, $zero, .L8004A088
    /* 4AC74 8004A074 8FBF001C */   lw        $ra, 0x1C($sp)
    /* 4AC78 8004A078 8E100010 */  lw         $s0, 0x10($s0)
    /* 4AC7C 8004A07C 5600FFF4 */  bnel       $s0, $zero, .L8004A050
    /* 4AC80 8004A080 960E0002 */   lhu       $t6, 0x2($s0)
  .L8004A084:
    /* 4AC84 8004A084 8FBF001C */  lw         $ra, 0x1C($sp)
  .L8004A088:
    /* 4AC88 8004A088 8FB00018 */  lw         $s0, 0x18($sp)
    /* 4AC8C 8004A08C 27BD0020 */  addiu      $sp, $sp, 0x20
    /* 4AC90 8004A090 03E00008 */  jr         $ra
    /* 4AC94 8004A094 00000000 */   nop
endlabel func_8004A038

nonmatching func_8004A098, 0x6C

glabel func_8004A098
    /* 4AC98 8004A098 8C830008 */  lw         $v1, 0x8($a0)
    /* 4AC9C 8004A09C 00801025 */  or         $v0, $a0, $zero
    /* 4ACA0 8004A0A0 5060000F */  beql       $v1, $zero, .L8004A0E0
    /* 4ACA4 8004A0A4 8C430008 */   lw        $v1, 0x8($v0)
    /* 4ACA8 8004A0A8 846E0000 */  lh         $t6, 0x0($v1)
    /* 4ACAC 8004A0AC 31CF1000 */  andi       $t7, $t6, 0x1000
    /* 4ACB0 8004A0B0 55E0000B */  bnel       $t7, $zero, .L8004A0E0
    /* 4ACB4 8004A0B4 8C430008 */   lw        $v1, 0x8($v0)
    /* 4ACB8 8004A0B8 8C830008 */  lw         $v1, 0x8($a0)
    /* 4ACBC 8004A0BC 00601025 */  or         $v0, $v1, $zero
  .L8004A0C0:
    /* 4ACC0 8004A0C0 8C630008 */  lw         $v1, 0x8($v1)
    /* 4ACC4 8004A0C4 50600006 */  beql       $v1, $zero, .L8004A0E0
    /* 4ACC8 8004A0C8 8C430008 */   lw        $v1, 0x8($v0)
    /* 4ACCC 8004A0CC 84780000 */  lh         $t8, 0x0($v1)
    /* 4ACD0 8004A0D0 33191000 */  andi       $t9, $t8, 0x1000
    /* 4ACD4 8004A0D4 5320FFFA */  beql       $t9, $zero, .L8004A0C0
    /* 4ACD8 8004A0D8 00601025 */   or        $v0, $v1, $zero
    /* 4ACDC 8004A0DC 8C430008 */  lw         $v1, 0x8($v0)
  .L8004A0E0:
    /* 4ACE0 8004A0E0 00001025 */  or         $v0, $zero, $zero
    /* 4ACE4 8004A0E4 84680000 */  lh         $t0, 0x0($v1)
    /* 4ACE8 8004A0E8 31091000 */  andi       $t1, $t0, 0x1000
    /* 4ACEC 8004A0EC 11200003 */  beqz       $t1, .L8004A0FC
    /* 4ACF0 8004A0F0 00000000 */   nop
    /* 4ACF4 8004A0F4 03E00008 */  jr         $ra
    /* 4ACF8 8004A0F8 00601025 */   or        $v0, $v1, $zero
  .L8004A0FC:
    /* 4ACFC 8004A0FC 03E00008 */  jr         $ra
    /* 4AD00 8004A100 00000000 */   nop
endlabel func_8004A098

nonmatching func_8004A104, 0x58

glabel func_8004A104
    /* 4AD04 8004A104 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 4AD08 8004A108 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4AD0C 8004A10C 8CA20024 */  lw         $v0, 0x24($a1)
    /* 4AD10 8004A110 C4840000 */  lwc1       $ft0, 0x0($a0)
    /* 4AD14 8004A114 C4460050 */  lwc1       $ft1, 0x50($v0)
    /* 4AD18 8004A118 46062201 */  sub.s      $ft2, $ft0, $ft1
    /* 4AD1C 8004A11C E7A80018 */  swc1       $ft2, 0x18($sp)
    /* 4AD20 8004A120 C48A0008 */  lwc1       $ft3, 0x8($a0)
    /* 4AD24 8004A124 C4500058 */  lwc1       $ft4, 0x58($v0)
    /* 4AD28 8004A128 C7A80018 */  lwc1       $ft2, 0x18($sp)
    /* 4AD2C 8004A12C 46105481 */  sub.s      $ft5, $ft3, $ft4
    /* 4AD30 8004A130 E7B20020 */  swc1       $ft5, 0x20($sp)
    /* 4AD34 8004A134 C7A40020 */  lwc1       $ft0, 0x20($sp)
    /* 4AD38 8004A138 46042182 */  mul.s      $ft1, $ft0, $ft0
    /* 4AD3C 8004A13C 00000000 */  nop
    /* 4AD40 8004A140 46084282 */  mul.s      $ft3, $ft2, $ft2
    /* 4AD44 8004A144 0C028078 */  jal        func_800A01E0
    /* 4AD48 8004A148 460A3300 */   add.s     $fa0, $ft1, $ft3
    /* 4AD4C 8004A14C 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4AD50 8004A150 27BD0028 */  addiu      $sp, $sp, 0x28
    /* 4AD54 8004A154 03E00008 */  jr         $ra
    /* 4AD58 8004A158 00000000 */   nop
endlabel func_8004A104

nonmatching func_8004A15C, 0x2C

glabel func_8004A15C
    /* 4AD5C 8004A15C 00802825 */  or         $a1, $a0, $zero
    /* 4AD60 8004A160 3C04801D */  lui        $a0, %hi(D_801CAC20)
    /* 4AD64 8004A164 8C84AC20 */  lw         $a0, %lo(D_801CAC20)($a0)
    /* 4AD68 8004A168 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 4AD6C 8004A16C AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4AD70 8004A170 0C012841 */  jal        func_8004A104
    /* 4AD74 8004A174 24840050 */   addiu     $a0, $a0, 0x50
    /* 4AD78 8004A178 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 4AD7C 8004A17C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 4AD80 8004A180 03E00008 */  jr         $ra
    /* 4AD84 8004A184 00000000 */   nop
endlabel func_8004A15C

nonmatching func_8004A188, 0x28

glabel func_8004A188
    /* 4AD88 8004A188 3C02801D */  lui        $v0, %hi(D_801CAC20)
    /* 4AD8C 8004A18C 8C42AC20 */  lw         $v0, %lo(D_801CAC20)($v0)
    /* 4AD90 8004A190 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 4AD94 8004A194 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 4AD98 8004A198 C4860000 */  lwc1       $ft1, 0x0($a0)
    /* 4AD9C 8004A19C C4440050 */  lwc1       $ft0, 0x50($v0)
    /* 4ADA0 8004A1A0 C48A0008 */  lwc1       $ft3, 0x8($a0)
    /* 4ADA4 8004A1A4 C4480058 */  lwc1       $ft2, 0x58($v0)
    /* 4ADA8 8004A1A8 46062001 */  sub.s      $fv0, $ft0, $ft1
    /* 4ADAC 8004A1AC 460A4081 */  sub.s      $fv1, $ft2, $ft3
endlabel func_8004A188
