.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8004A1B0, 0x44

glabel func_8004A1B0
    jr $ra
    nop
  .L8004A1EC:
    jr $ra
    nop
endlabel func_8004A1B0

nonmatching func_8004A1F4, 0x2C0

glabel func_8004A1F4
    jr $ra
    nop
  .L8004A21C:
    jr $ra
    nop
  .L8004A24C:
    jr $ra
    nop
  .L8004A25C:
    jr $ra
    nop
  .L8004A27C:
    jr $ra
    nop
  .L8004A3B4:
    jr $ra
    nop
  .L8004A3B8:
    jr $ra
    nop
  .L8004A41C:
    jr $ra
    nop
  .L8004A45C:
    jr $ra
    nop
  .L8004A4A0:
    jr $ra
    nop
  .L8004A4A4:
    jr $ra
    nop
endlabel func_8004A1F4

nonmatching func_8004A4B4, 0x1B8

glabel func_8004A4B4
    jr $ra
    nop
  .L8004A504:
    jr $ra
    nop
  .L8004A56C:
    jr $ra
    nop
  .L8004A588:
    jr $ra
    nop
  .L8004A5A0:
    jr $ra
    nop
  .L8004A5F4:
    jr $ra
    nop
  .L8004A610:
    jr $ra
    nop
  .L8004A620:
    jr $ra
    nop
  .L8004A640:
    jr $ra
    nop
  .L8004A658:
    jr $ra
    nop
  .L8004A65C:
    jr $ra
    nop
endlabel func_8004A4B4

nonmatching func_8004A66C, 0x70

glabel func_8004A66C
    jr $ra
    nop
  .L8004A6CC:
    jr $ra
    nop
  .L8004A6D0:
    jr $ra
    nop
endlabel func_8004A66C

nonmatching func_8004A6DC, 0x50

glabel func_8004A6DC
    jr $ra
    nop
  .L8004A710:
    jr $ra
    nop
endlabel func_8004A6DC

nonmatching func_8004A72C, 0x128

glabel func_8004A72C
    jr $ra
    nop
  .L8004A840:
    jr $ra
    nop
endlabel func_8004A72C

nonmatching func_8004A854, 0x50

glabel func_8004A854
    jr $ra
    nop
endlabel func_8004A854

nonmatching func_8004A8A4, 0x174

glabel func_8004A8A4
    jr $ra
    nop
  .L8004A8D4:
    jr $ra
    nop
  .L8004A964:
    jr $ra
    nop
  .L8004A988:
    jr $ra
    nop
  .L8004A9EC:
    jr $ra
    nop
  .L8004A9F4:
    jr $ra
    nop
  .L8004AA0C:
    jr $ra
    nop
endlabel func_8004A8A4

nonmatching func_8004AA18, 0x18

glabel func_8004AA18
    jr $ra
    nop
endlabel func_8004AA18
