.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80003FC0, 0xA4

glabel func_80003FC0
    jr $ra
    nop
endlabel func_80003FC0

nonmatching D_80004064, 0x14

glabel D_80004064
    jr $ra
    nop
endlabel D_80004064

nonmatching func_80004078, 0x108

glabel func_80004078
    jr $ra
    nop
  .L80004144:
    jr $ra
    nop
endlabel func_80004078
