.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8004C870, 0x4

glabel func_8004C870
    jr $ra
    nop
endlabel func_8004C870

nonmatching D_8004C874, 0x30

glabel D_8004C874
    jr $ra
    nop
endlabel D_8004C874

nonmatching D_8004C8A4, 0x4C

glabel D_8004C8A4
    jr $ra
    nop
endlabel D_8004C8A4

nonmatching D_8004C8F0, 0x4

glabel D_8004C8F0
    jr $ra
    nop
endlabel D_8004C8F0

nonmatching D_8004C8F4, 0x10

glabel D_8004C8F4
    jr $ra
    nop
endlabel D_8004C8F4

nonmatching func_8004C904, 0x550

glabel func_8004C904
    jr $ra
    nop
  .L8004C978:
    jr $ra
    nop
  .L8004C9A8:
    jr $ra
    nop
  .L8004C9D0:
    jr $ra
    nop
  .L8004C9E8:
    jr $ra
    nop
  .L8004CA04:
    jr $ra
    nop
  .L8004CA20:
    jr $ra
    nop
  .L8004CA3C:
    jr $ra
    nop
  .L8004CA58:
    jr $ra
    nop
  .L8004CA70:
    jr $ra
    nop
  .L8004CA94:
    jr $ra
    nop
  .L8004CAB4:
    jr $ra
    nop
  .L8004CAD4:
    jr $ra
    nop
  .L8004CAF4:
    jr $ra
    nop
  .L8004CB14:
    jr $ra
    nop
  .L8004CB34:
    jr $ra
    nop
  .L8004CB50:
    jr $ra
    nop
  .L8004CBB4:
    jr $ra
    nop
  .L8004CC10:
    jr $ra
    nop
  .L8004CC4C:
    jr $ra
    nop
  .L8004CC64:
    jr $ra
    nop
  .L8004CC68:
    jr $ra
    nop
  .L8004CCA0:
    jr $ra
    nop
  .L8004CCEC:
    jr $ra
    nop
  .L8004CCFC:
    jr $ra
    nop
  .L8004CD18:
    jr $ra
    nop
  .L8004CD1C:
    jr $ra
    nop
  .L8004CD78:
    jr $ra
    nop
  .L8004CD9C:
    jr $ra
    nop
  .L8004CDAC:
    jr $ra
    nop
  .L8004CDB0:
    jr $ra
    nop
  .L8004CE24:
    jr $ra
    nop
endlabel func_8004C904
    /* 4DA54 8004CE54 00000000 */  nop
    /* 4DA58 8004CE58 00000000 */  nop
    /* 4DA5C 8004CE5C 00000000 */  nop

nonmatching func_8004CE60, 0x70

glabel func_8004CE60
    jr $ra
    nop
endlabel func_8004CE60

nonmatching func_8004CED0, 0x50

glabel func_8004CED0
    jr $ra
    nop
  .L8004CEF4:
    jr $ra
    nop
endlabel func_8004CED0
