.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80051B10, 0x8

glabel func_80051B10
# PATCHED: # PATCHED: /* 52710 80051B10 100000AB */  b          D_80051DC0
    nop
    nop
    /* 52714 80051B14 00402025 */   or        $a0, $v0, $zero
endlabel func_80051B10

nonmatching D_80051B18, 0x1F8

glabel D_80051B18
    jr $ra
    nop
  .L80051C0C:
    jr $ra
    nop
  .L80051C10:
    jr $ra
    nop
  .L80051C24:
    jr $ra
    nop
  .L80051C28:
    jr $ra
    nop
  .L80051C38:
    jr $ra
    nop
  .L80051C3C:
    jr $ra
    nop
  .L80051CA0:
    jr $ra
    nop
endlabel D_80051B18
