.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80052150, 0x64

glabel func_80052150
    jr $ra
    nop
  .L80052190:
    jr $ra
    nop
endlabel func_80052150

nonmatching D_800521B4, 0x10

glabel D_800521B4
    jr $ra
    nop
  .L800521B8:
    jr $ra
    nop
endlabel D_800521B4

nonmatching func_800521C4, 0x2C8

glabel func_800521C4
    jr $ra
    nop
  .L8005226C:
    jr $ra
    nop
  .L800522E4:
    jr $ra
    nop
  .L8005230C:
    jr $ra
    nop
  .L80052338:
    jr $ra
    nop
  .L8005235C:
    jr $ra
    nop
  .L80052394:
    jr $ra
    nop
  .L800523B8:
    jr $ra
    nop
  .L800523BC:
    jr $ra
    nop
  .L800523C0:
    jr $ra
    nop
  .L800523EC:
    jr $ra
    nop
  .L80052470:
    jr $ra
    nop
  .L8005247C:
    jr $ra
    nop
endlabel func_800521C4
    /* 5308C 8005248C 00000000 */  nop

nonmatching func_80052490, 0x2D8

glabel func_80052490
    jr $ra
    nop
  .L800525E8:
    jr $ra
    nop
  .L80052614:
    jr $ra
    nop
  .L80052624:
    jr $ra
    nop
  .L80052628:
    jr $ra
    nop
  .L80052684:
    jr $ra
    nop
endlabel func_80052490

nonmatching func_80052768, 0x3D0

glabel func_80052768
    jr $ra
    nop
  .L800528C8:
    jr $ra
    nop
  .L800528F0:
    jr $ra
    nop
  .L80052900:
    jr $ra
    nop
  .L80052904:
    jr $ra
    nop
  .L80052980:
    jr $ra
    nop
endlabel func_80052768
    /* 53738 80052B38 00000000 */  nop
    /* 5373C 80052B3C 00000000 */  nop

nonmatching func_80052B40, 0x224

glabel func_80052B40
    jr $ra
    nop
  .L80052C9C:
    jr $ra
    nop
  .L80052CA8:
    jr $ra
    nop
  .L80052CB4:
    jr $ra
    nop
  .L80052D04:
    jr $ra
    nop
  .L80052D08:
    jr $ra
    nop
  .L80052D58:
    jr $ra
    nop
endlabel func_80052B40

nonmatching func_80052D64, 0x240

glabel func_80052D64
    jr $ra
    nop
  .L80052F98:
    jr $ra
    nop
endlabel func_80052D64

nonmatching func_80052FA4, 0x88

glabel func_80052FA4
    jr $ra
    nop
  .L80052FDC:
    jr $ra
    nop
  .L80053014:
    jr $ra
    nop
endlabel func_80052FA4

nonmatching func_8005302C, 0x9C

glabel func_8005302C
    jr $ra
    nop
  .L80053080:
    jr $ra
    nop
  .L800530A0:
    jr $ra
    nop
endlabel func_8005302C

nonmatching func_800530C8, 0xB0

glabel func_800530C8
    jr $ra
    nop
  .L8005311C:
    jr $ra
    nop
  .L80053150:
    jr $ra
    nop
endlabel func_800530C8

nonmatching func_80053178, 0xF8

glabel func_80053178
    jr $ra
    nop
  .L800531B4:
    jr $ra
    nop
  .L80053238:
    jr $ra
    nop
  .L80053258:
    jr $ra
    nop
  .L8005325C:
    jr $ra
    nop
endlabel func_80053178

nonmatching func_80053270, 0x74

glabel func_80053270
    jr $ra
    nop
  .L800532A4:
    jr $ra
    nop
  .L800532DC:
    jr $ra
    nop
endlabel func_80053270

nonmatching func_800532E4, 0xAC

glabel func_800532E4
    jr $ra
    nop
endlabel func_800532E4

nonmatching func_80053390, 0xAC

glabel func_80053390
    jr $ra
    nop
endlabel func_80053390

nonmatching func_8005343C, 0x30

glabel func_8005343C
    jr $ra
    nop
endlabel func_8005343C

nonmatching func_8005346C, 0xEC

glabel func_8005346C
    jr $ra
    nop
  .L800534D0:
    jr $ra
    nop
  .L800534F8:
    jr $ra
    nop
  .L80053510:
    jr $ra
    nop
endlabel func_8005346C

nonmatching func_80053558, 0x34

glabel func_80053558
    jr $ra
    nop
endlabel func_80053558

nonmatching func_8005358C, 0xDC

glabel func_8005358C
    jr $ra
    nop
endlabel func_8005358C

nonmatching func_80053668, 0x12C

glabel func_80053668
    jr $ra
    nop
  .L800536F0:
    jr $ra
    nop
  .L80053770:
    jr $ra
    nop
endlabel func_80053668

nonmatching func_80053794, 0x6C

glabel func_80053794
    jr $ra
    nop
endlabel func_80053794

nonmatching func_80053800, 0x140

glabel func_80053800
    jr $ra
    nop
  .L80053868:
    jr $ra
    nop
  .L8005386C:
    jr $ra
    nop
endlabel func_80053800

nonmatching func_80053940, 0x2C

glabel func_80053940
    jr $ra
    nop
endlabel func_80053940

nonmatching func_8005396C, 0x48

glabel func_8005396C
    jr $ra
    nop
  .L800539A4:
    jr $ra
    nop
endlabel func_8005396C

nonmatching func_800539B4, 0x30

glabel func_800539B4
    jr $ra
    nop
  .L800539DC:
    jr $ra
    nop
endlabel func_800539B4

nonmatching func_800539E4, 0x28

glabel func_800539E4
    jr $ra
    nop
  .L80053A04:
    jr $ra
    nop
endlabel func_800539E4

nonmatching func_80053A0C, 0xF4

glabel func_80053A0C
    jr $ra
    nop
endlabel func_80053A0C

nonmatching func_80053B00, 0x48

glabel func_80053B00
    jr $ra
    nop
endlabel func_80053B00

nonmatching func_80053B48, 0xBC

glabel func_80053B48
    jr $ra
    nop
endlabel func_80053B48

nonmatching func_80053C04, 0x44

glabel func_80053C04
    jr $ra
    nop
endlabel func_80053C04

nonmatching func_80053C48, 0x214

glabel func_80053C48
    jr $ra
    nop
  .L80053E50:
    jr $ra
    nop
endlabel func_80053C48

nonmatching func_80053E5C, 0x154

glabel func_80053E5C
    jr $ra
    nop
  .L80053EE0:
    jr $ra
    nop
  .L80053EFC:
    jr $ra
    nop
  .L80053F18:
    jr $ra
    nop
  .L80053F24:
    jr $ra
    nop
  .L80053F5C:
    jr $ra
    nop
  .L80053F68:
    jr $ra
    nop
  .L80053F84:
    jr $ra
    nop
endlabel func_80053E5C

nonmatching func_80053FB0, 0x120

glabel func_80053FB0
    jr $ra
    nop
  .L80054034:
    jr $ra
    nop
  .L80054050:
    jr $ra
    nop
  .L8005406C:
    jr $ra
    nop
  .L80054078:
    jr $ra
    nop
  .L800540AC:
    jr $ra
    nop
endlabel func_80053FB0

nonmatching func_800540D0, 0x94

glabel func_800540D0
    jr $ra
    nop
  .L80054120:
    jr $ra
    nop
  .L80054140:
    jr $ra
    nop
endlabel func_800540D0

nonmatching func_80054164, 0x54

glabel func_80054164
    jr $ra
    nop
endlabel func_80054164

nonmatching func_800541B8, 0x68

glabel func_800541B8
    jr $ra
    nop
endlabel func_800541B8

nonmatching func_80054220, 0x50

glabel func_80054220
    jr $ra
    nop
  .L8005425C:
    jr $ra
    nop
endlabel func_80054220
