.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800546F0, 0x1E0

glabel func_800546F0
    jr $ra
    nop
endlabel func_800546F0
