.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80055AD0, 0x490

glabel func_80055AD0
    jr $ra
    nop
  .L80055B40:
    jr $ra
    nop
  .L80055BBC:
    jr $ra
    nop
  .L80055BF8:
    jr $ra
    nop
  .L80055C40:
    jr $ra
    nop
  alabel D_80055D10
    jr $ra
    nop
  .L80055D94:
    jr $ra
    nop
  .L80055E14:
    jr $ra
    nop
  .L80055E80:
    jr $ra
    nop
  .L80055E8C:
    jr $ra
    nop
  .L80055E98:
    jr $ra
    nop
  .L80055ED4:
    jr $ra
    nop
  .L80055F40:
    jr $ra
    nop
  .L80055F4C:
    jr $ra
    nop
  .L80055F58:
    jr $ra
    nop
endlabel func_80055AD0
