.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8005AA20, 0x2C

glabel func_8005AA20
    jr $ra
    nop
endlabel func_8005AA20

nonmatching D_8005AA4C, 0x58

glabel D_8005AA4C
    jr $ra
    nop
  .L8005AA78:
    jr $ra
    nop
  .L8005AA98:
    jr $ra
    nop
  .L8005AAA0:
    jr $ra
    nop
endlabel D_8005AA4C

nonmatching D_8005AAA4, 0x14

glabel D_8005AAA4
    jr $ra
    nop
endlabel D_8005AAA4

nonmatching func_8005AAB8, 0x70

glabel func_8005AAB8
    jr $ra
    nop
  .L8005AAEC:
    jr $ra
    nop
  .L8005AB08:
    jr $ra
    nop
  .L8005AB14:
    jr $ra
    nop
endlabel func_8005AAB8

nonmatching func_8005AB28, 0xB8

glabel func_8005AB28
    jr $ra
    nop
  .L8005AB4C:
    jr $ra
    nop
  .L8005AB84:
    jr $ra
    nop
  .L8005ABB8:
    jr $ra
    nop
endlabel func_8005AB28
