.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8006B4B0, 0x50

glabel func_8006B4B0
    jr $ra
    nop
endlabel func_8006B4B0

nonmatching func_8006B500, 0x388

glabel func_8006B500
    jr $ra
    nop
  .L8006B5EC:
    jr $ra
    nop
  .L8006B5F8:
    jr $ra
    nop
  .L8006B6E4:
    jr $ra
    nop
  .L8006B77C:
    jr $ra
    nop
  .L8006B794:
    jr $ra
    nop
  .L8006B850:
    jr $ra
    nop
endlabel func_8006B500

nonmatching func_8006B888, 0x284

glabel func_8006B888
    jr $ra
    nop
  .L8006B928:
    jr $ra
    nop
  .L8006B934:
    jr $ra
    nop
  .L8006BA74:
    jr $ra
    nop
  .L8006BA98:
    jr $ra
    nop
  .L8006BAD4:
    jr $ra
    nop
endlabel func_8006B888

nonmatching func_8006BB0C, 0x1F4

glabel func_8006BB0C
    jr $ra
    nop
  .L8006BB78:
    jr $ra
    nop
  .L8006BC70:
    jr $ra
    nop
  .L8006BCAC:
    jr $ra
    nop
  .L8006BCC0:
    jr $ra
    nop
  .L8006BCD0:
    jr $ra
    nop
endlabel func_8006BB0C

nonmatching func_8006BD00, 0x4C

glabel func_8006BD00
    jr $ra
    nop
  .L8006BD38:
    jr $ra
    nop
endlabel func_8006BD00

nonmatching func_8006BD4C, 0x1F4

glabel func_8006BD4C
    jr $ra
    nop
  .L8006BDA8:
    jr $ra
    nop
  .L8006BDB0:
    jr $ra
    nop
  .L8006BE38:
    jr $ra
    nop
endlabel func_8006BD4C
