.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80071B00, 0xC

glabel func_80071B00
    jr $ra
    nop
endlabel func_80071B00

nonmatching D_80071B0C, 0x28

glabel D_80071B0C
    jr $ra
    nop
  .L80071B28:
    jr $ra
    nop
endlabel D_80071B0C

nonmatching func_80071B34, 0x7C

glabel func_80071B34
    jr $ra
    nop
  .L80071BA4:
    jr $ra
    nop
endlabel func_80071B34

nonmatching func_80071BB0, 0x5D8

glabel func_80071BB0
    jr $ra
    nop
  .L80071CC4:
    jr $ra
    nop
  .L80071CDC:
    jr $ra
    nop
  .L80071D8C:
    jr $ra
    nop
  .L80071DB4:
    jr $ra
    nop
  .L80071DE0:
    jr $ra
    nop
  .L80071DE4:
    jr $ra
    nop
  .L80071E2C:
    jr $ra
    nop
  .L80071E80:
    jr $ra
    nop
  .L80071ECC:
    jr $ra
    nop
  .L80071ED0:
    jr $ra
    nop
  .L80071EF4:
    jr $ra
    nop
  .L80071F7C:
    jr $ra
    nop
  .L8007208C:
    jr $ra
    nop
  .L80072174:
    jr $ra
    nop
  .L80072178:
    jr $ra
    nop
endlabel func_80071BB0

nonmatching func_80072188, 0x8

glabel func_80072188
    jr $ra
    nop
endlabel func_80072188
