.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80072190, 0x10

glabel func_80072190
    /* 72D90 80072190 AFBF004C */  sw         $ra, 0x4C($sp)
    /* 72D94 80072194 2739D384 */  addiu      $t9, $t9, -0x2C7C
    /* 72D98 80072198 AFB40048 */  sw         $s4, 0x48($sp)
    /* 72D9C 8007219C AFB30044 */  sw         $s3, 0x44($sp)
endlabel func_80072190
