.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800721A0, 0x10

glabel func_800721A0
    /* 72DA0 800721A0 AFB20040 */  sw         $s2, 0x40($sp)
    /* 72DA4 800721A4 AFB1003C */  sw         $s1, 0x3C($sp)
    /* 72DA8 800721A8 AFB00038 */  sw         $s0, 0x38($sp)
    /* 72DAC 800721AC F7BA0030 */  sdc1       $fs3, 0x30($sp)
endlabel func_800721A0
