.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800721A0, 0x10

glabel func_800721A0
    jr $ra
    nop
endlabel func_800721A0
