.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8007D480, 0x200

glabel func_8007D480
    jr $ra
    nop
  .L8007D4D0:
    jr $ra
    nop
  .L8007D4EC:
    jr $ra
    nop
  .L8007D500:
    jr $ra
    nop
  .L8007D62C:
    jr $ra
    nop
endlabel func_8007D480

nonmatching func_8007D680, 0x148

glabel func_8007D680
    jr $ra
    nop
  .L8007D738:
    jr $ra
    nop
  .L8007D7B8:
    jr $ra
    nop
endlabel func_8007D680

nonmatching func_8007D7C8, 0x124

glabel func_8007D7C8
    jr $ra
    nop
  .L8007D830:
    jr $ra
    nop
  .L8007D8D4:
    jr $ra
    nop
  .L8007D8D8:
    jr $ra
    nop
endlabel func_8007D7C8

nonmatching func_8007D8EC, 0x80

glabel func_8007D8EC
    jr $ra
    nop
  .L8007D958:
    jr $ra
    nop
endlabel func_8007D8EC

nonmatching func_8007D96C, 0x80

glabel func_8007D96C
    jr $ra
    nop
  .L8007D9D8:
    jr $ra
    nop
endlabel func_8007D96C
    /* 7E5EC 8007D9EC 00000000 */  nop

nonmatching func_8007D9F0, 0x70

glabel func_8007D9F0
    jr $ra
    nop
endlabel func_8007D9F0

nonmatching func_8007DA60, 0x2C0

glabel func_8007DA60
    jr $ra
    nop
  .L8007DA94:
    jr $ra
    nop
  .L8007DA98:
    jr $ra
    nop
  .L8007DAC4:
    jr $ra
    nop
  .L8007DAE0:
    jr $ra
    nop
  .L8007DB00:
    jr $ra
    nop
  .L8007DB34:
    jr $ra
    nop
  .L8007DB5C:
    jr $ra
    nop
  .L8007DC0C:
    jr $ra
    nop
  .L8007DC30:
    jr $ra
    nop
  .L8007DC4C:
    jr $ra
    nop
  .L8007DC74:
    jr $ra
    nop
  .L8007DCA0:
    jr $ra
    nop
  .L8007DCC8:
    jr $ra
    nop
  .L8007DCF0:
    jr $ra
    nop
  .L8007DCF8:
    jr $ra
    nop
  .L8007DD10:
    jr $ra
    nop
endlabel func_8007DA60

nonmatching func_8007DD20, 0x260

glabel func_8007DD20
    jr $ra
    nop
  .L8007DD74:
    jr $ra
    nop
  .L8007DD8C:
    jr $ra
    nop
  .L8007DDA0:
    jr $ra
    nop
  .L8007DDA4:
    jr $ra
    nop
  .L8007DDC8:
    jr $ra
    nop
  .L8007DDEC:
    jr $ra
    nop
  .L8007DDFC:
    jr $ra
    nop
  .L8007DE08:
    jr $ra
    nop
  .L8007DE40:
    jr $ra
    nop
  .L8007DE4C:
    jr $ra
    nop
  .L8007DE70:
    jr $ra
    nop
  .L8007DECC:
    jr $ra
    nop
  .L8007DEE8:
    jr $ra
    nop
  .L8007DF08:
    jr $ra
    nop
  .L8007DF20:
    jr $ra
    nop
  .L8007DF44:
    jr $ra
    nop
  .L8007DF48:
    jr $ra
    nop
  .L8007DF70:
    jr $ra
    nop
  .L8007DF74:
    jr $ra
    nop
endlabel func_8007DD20

nonmatching func_8007DF80, 0x590

glabel func_8007DF80
    jr $ra
    nop
  .L8007DFBC:
    jr $ra
    nop
  .L8007DFC0:
    jr $ra
    nop
  .L8007E004:
    jr $ra
    nop
  .L8007E034:
    jr $ra
    nop
  .L8007E054:
    jr $ra
    nop
  .L8007E084:
    jr $ra
    nop
  .L8007E0A0:
    jr $ra
    nop
  .L8007E0DC:
    jr $ra
    nop
  .L8007E0F8:
    jr $ra
    nop
  .L8007E118:
    jr $ra
    nop
  .L8007E12C:
    jr $ra
    nop
  .L8007E14C:
    jr $ra
    nop
  .L8007E174:
    jr $ra
    nop
  .L8007E188:
    jr $ra
    nop
  .L8007E1A8:
    jr $ra
    nop
  .L8007E1D8:
    jr $ra
    nop
  .L8007E1F4:
    jr $ra
    nop
  .L8007E218:
    jr $ra
    nop
  .L8007E290:
    jr $ra
    nop
  .L8007E2C4:
    jr $ra
    nop
  .L8007E314:
    jr $ra
    nop
  .L8007E33C:
    jr $ra
    nop
  .L8007E350:
    jr $ra
    nop
  .L8007E364:
    jr $ra
    nop
  .L8007E3C0:
    jr $ra
    nop
  .L8007E3EC:
    jr $ra
    nop
  .L8007E438:
    jr $ra
    nop
  .L8007E460:
    jr $ra
    nop
  .L8007E474:
    jr $ra
    nop
  .L8007E488:
    jr $ra
    nop
  .L8007E4C4:
    jr $ra
    nop
  .L8007E4D8:
    jr $ra
    nop
  .L8007E4FC:
    jr $ra
    nop
endlabel func_8007DF80

nonmatching func_8007E510, 0x170

glabel func_8007E510
    jr $ra
    nop
  .L8007E56C:
    jr $ra
    nop
  .L8007E58C:
    jr $ra
    nop
  .L8007E598:
    jr $ra
    nop
  .L8007E638:
    jr $ra
    nop
  .L8007E65C:
    jr $ra
    nop
  .L8007E674:
    jr $ra
    nop
endlabel func_8007E510

nonmatching func_8007E680, 0x274

glabel func_8007E680
    jr $ra
    nop
  .L8007E6C4:
    jr $ra
    nop
  .L8007E6C8:
    jr $ra
    nop
  .L8007E700:
    jr $ra
    nop
  .L8007E704:
    jr $ra
    nop
  .L8007E7C8:
    jr $ra
    nop
  .L8007E7E0:
    jr $ra
    nop
  .L8007E7F8:
    jr $ra
    nop
  .L8007E818:
    jr $ra
    nop
  .L8007E820:
    jr $ra
    nop
  .L8007E8D4:
    jr $ra
    nop
  .L8007E8E4:
    jr $ra
    nop
endlabel func_8007E680

nonmatching func_8007E8F4, 0x400

glabel func_8007E8F4
    jr $ra
    nop
  .L8007E94C:
    jr $ra
    nop
  .L8007E964:
    jr $ra
    nop
  .L8007E98C:
    jr $ra
    nop
  .L8007E9A0:
    jr $ra
    nop
  .L8007EA50:
    jr $ra
    nop
  .L8007EA64:
    jr $ra
    nop
  .L8007EAC0:
    jr $ra
    nop
  .L8007EAC4:
    jr $ra
    nop
  .L8007EAE8:
    jr $ra
    nop
  .L8007EB14:
    jr $ra
    nop
  .L8007EB34:
    jr $ra
    nop
  .L8007EB4C:
    jr $ra
    nop
  .L8007EB64:
    jr $ra
    nop
  .L8007EB90:
    jr $ra
    nop
  .L8007EB98:
    jr $ra
    nop
  .L8007EBA8:
    jr $ra
    nop
  .L8007EBBC:
    jr $ra
    nop
  .L8007EBDC:
    jr $ra
    nop
  .L8007EBE0:
    jr $ra
    nop
  .L8007EC28:
    jr $ra
    nop
  .L8007EC60:
    jr $ra
    nop
  .L8007EC64:
    jr $ra
    nop
  .L8007EC68:
    jr $ra
    nop
  .L8007EC88:
    jr $ra
    nop
  .L8007ECC0:
    jr $ra
    nop
  .L8007ECE0:
    jr $ra
    nop
endlabel func_8007E8F4

nonmatching func_8007ECF4, 0xCC

glabel func_8007ECF4
    jr $ra
    nop
  .L8007ED28:
    jr $ra
    nop
  .L8007ED40:
    jr $ra
    nop
  .L8007ED48:
    jr $ra
    nop
  .L8007ED6C:
    jr $ra
    nop
  .L8007ED80:
    jr $ra
    nop
  .L8007ED9C:
    jr $ra
    nop
  .L8007EDA4:
    jr $ra
    nop
  .L8007EDA8:
    jr $ra
    nop
endlabel func_8007ECF4

nonmatching func_8007EDC0, 0x19C

glabel func_8007EDC0
    jr $ra
    nop
  .L8007EE14:
    jr $ra
    nop
  .L8007EE40:
    jr $ra
    nop
  .L8007EE60:
    jr $ra
    nop
  .L8007EE84:
    jr $ra
    nop
  .L8007EE8C:
    jr $ra
    nop
  .L8007EEB4:
    jr $ra
    nop
  .L8007EEDC:
    jr $ra
    nop
  .L8007EF18:
    jr $ra
    nop
  .L8007EF48:
    jr $ra
    nop
  .L8007EF4C:
    jr $ra
    nop
endlabel func_8007EDC0

nonmatching func_8007EF5C, 0x134

glabel func_8007EF5C
    jr $ra
    nop
  .L8007EF9C:
    jr $ra
    nop
  .L8007EFF8:
    jr $ra
    nop
  .L8007F000:
    jr $ra
    nop
  .L8007F008:
    jr $ra
    nop
  .L8007F028:
    jr $ra
    nop
  .L8007F084:
    jr $ra
    nop
endlabel func_8007EF5C

nonmatching func_8007F090, 0xA8

glabel func_8007F090
    jr $ra
    nop
  .L8007F0C8:
    jr $ra
    nop
  .L8007F0E8:
    jr $ra
    nop
  .L8007F124:
    jr $ra
    nop
  .L8007F134:
    jr $ra
    nop
endlabel func_8007F090

nonmatching D_8007F138, 0xCC

glabel D_8007F138
    jr $ra
    nop
  .L8007F14C:
    jr $ra
    nop
  .L8007F178:
    jr $ra
    nop
  .L8007F180:
    jr $ra
    nop
  .L8007F1A0:
    jr $ra
    nop
  .L8007F1AC:
    jr $ra
    nop
  .L8007F1D4:
    jr $ra
    nop
  .L8007F1E0:
    jr $ra
    nop
  .L8007F1E8:
    jr $ra
    nop
  .L8007F1F8:
    jr $ra
    nop
  .L8007F1FC:
    jr $ra
    nop
endlabel D_8007F138

nonmatching D_8007F204, 0xDC

glabel D_8007F204
    jr $ra
    nop
  .L8007F210:
    jr $ra
    nop
  .L8007F23C:
    jr $ra
    nop
  .L8007F258:
    jr $ra
    nop
  .L8007F278:
    jr $ra
    nop
  .L8007F288:
    jr $ra
    nop
  .L8007F2B8:
    jr $ra
    nop
  .L8007F2D4:
    jr $ra
    nop
  .L8007F2DC:
    jr $ra
    nop
endlabel D_8007F204
