.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80142CA0, 0x7C

glabel func_80142CA0
    /* C5D90 80142CA0 94830016 */  lhu        $v1, 0x16($a0)
    /* C5D94 80142CA4 00002825 */  or         $a1, $zero, $zero
    /* C5D98 80142CA8 14400005 */  bnez       $v0, .L80142CC0
    /* C5D9C 80142CAC 0062082A */   slt       $at, $v1, $v0
    /* C5DA0 80142CB0 14600003 */  bnez       $v1, .L80142CC0
    /* C5DA4 80142CB4 00000000 */   nop
    /* C5DA8 80142CB8 03E00008 */  jr         $ra
    /* C5DAC 80142CBC 24020001 */   addiu     $v0, $zero, 0x1
  .L80142CC0:
    /* C5DB0 80142CC0 1420000A */  bnez       $at, .L80142CEC
    /* C5DB4 80142CC4 3C04801D */   lui       $a0, %hi(D_801CAB20)
    /* C5DB8 80142CC8 3C04801D */  lui        $a0, %hi(D_801CAB20)
    /* C5DBC 80142CCC 8484AB20 */  lh         $a0, %lo(D_801CAB20)($a0)
    /* C5DC0 80142CD0 0082082A */  slt        $at, $a0, $v0
    /* C5DC4 80142CD4 1420000F */  bnez       $at, .L80142D14
    /* C5DC8 80142CD8 0083082A */   slt       $at, $a0, $v1
    /* C5DCC 80142CDC 1020000D */  beqz       $at, .L80142D14
    /* C5DD0 80142CE0 00000000 */   nop
    /* C5DD4 80142CE4 03E00008 */  jr         $ra
    /* C5DD8 80142CE8 24020001 */   addiu     $v0, $zero, 0x1
  .L80142CEC:
    /* C5DDC 80142CEC 8484AB20 */  lh         $a0, %lo(D_801CAB20)($a0)
    /* C5DE0 80142CF0 0082082A */  slt        $at, $a0, $v0
    /* C5DE4 80142CF4 54200004 */  bnel       $at, $zero, .L80142D08
    /* C5DE8 80142CF8 0064082A */   slt       $at, $v1, $a0
    /* C5DEC 80142CFC 03E00008 */  jr         $ra
    /* C5DF0 80142D00 24020001 */   addiu     $v0, $zero, 0x1
    /* C5DF4 80142D04 0064082A */  slt        $at, $v1, $a0
  .L80142D08:
    /* C5DF8 80142D08 14200002 */  bnez       $at, .L80142D14
    /* C5DFC 80142D0C 00000000 */   nop
    /* C5E00 80142D10 24050001 */  addiu      $a1, $zero, 0x1
  .L80142D14:
    /* C5E04 80142D14 03E00008 */  jr         $ra
    /* C5E08 80142D18 00A01025 */   or        $v0, $a1, $zero
endlabel func_80142CA0

nonmatching func_80142D1C, 0x30

glabel func_80142D1C
    /* C5E0C 80142D1C 948E0016 */  lhu        $t6, 0x16($a0)
    /* C5E10 80142D20 94980014 */  lhu        $t8, 0x14($a0)
    /* C5E14 80142D24 24020001 */  addiu      $v0, $zero, 0x1
    /* C5E18 80142D28 01C57821 */  addu       $t7, $t6, $a1
    /* C5E1C 80142D2C 27190001 */  addiu      $t9, $t8, 0x1
    /* C5E20 80142D30 01F9082A */  slt        $at, $t7, $t9
    /* C5E24 80142D34 14200003 */  bnez       $at, .L80142D44
    /* C5E28 80142D38 00000000 */   nop
    /* C5E2C 80142D3C 03E00008 */  jr         $ra
    /* C5E30 80142D40 00001025 */   or        $v0, $zero, $zero
  .L80142D44:
    /* C5E34 80142D44 03E00008 */  jr         $ra
  alabel D_80142D48
    /* C5E38 80142D48 00000000 */   nop
endlabel func_80142D1C

nonmatching func_80142D4C, 0x13C

glabel func_80142D4C
    /* C5E3C 80142D4C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* C5E40 80142D50 AFBF0014 */  sw         $ra, 0x14($sp)
    /* C5E44 80142D54 8C820034 */  lw         $v0, 0x34($a0)
    /* C5E48 80142D58 00803825 */  or         $a3, $a0, $zero
    /* C5E4C 80142D5C 8C430014 */  lw         $v1, 0x14($v0)
    /* C5E50 80142D60 8C66000C */  lw         $a2, 0xC($v1)
    /* C5E54 80142D64 10C00011 */  beqz       $a2, .L80142DAC
    /* C5E58 80142D68 00000000 */   nop
    /* C5E5C 80142D6C 10C0000B */  beqz       $a2, .L80142D9C
    /* C5E60 80142D70 00001825 */   or        $v1, $zero, $zero
    /* C5E64 80142D74 3C198000 */  lui        $t9, %hi(func_800048A0)
    /* C5E68 80142D78 273948A0 */  addiu      $t9, $t9, %lo(func_800048A0)
    /* C5E6C 80142D7C 3C04801D */  lui        $a0, %hi(D_801CAA60)
    /* C5E70 80142D80 2484AA60 */  addiu      $a0, $a0, %lo(D_801CAA60)
    /* C5E74 80142D84 00C02825 */  or         $a1, $a2, $zero
    /* C5E78 80142D88 0320F809 */  jalr       $t9
    /* C5E7C 80142D8C AFA70018 */   sw        $a3, 0x18($sp)
    /* C5E80 80142D90 8FA70018 */  lw         $a3, 0x18($sp)
    /* C5E84 80142D94 10000001 */  b          .L80142D9C
    /* C5E88 80142D98 00401825 */   or        $v1, $v0, $zero
  .L80142D9C:
    /* C5E8C 80142D9C 10600003 */  beqz       $v1, .L80142DAC
    /* C5E90 80142DA0 00000000 */   nop
    /* C5E94 80142DA4 10000034 */  b          .L80142E78
    /* C5E98 80142DA8 24020001 */   addiu     $v0, $zero, 0x1
  .L80142DAC:
    /* C5E9C 80142DAC 3C03801D */  lui        $v1, %hi(D_801C82C0)
    /* C5EA0 80142DB0 246382C0 */  addiu      $v1, $v1, %lo(D_801C82C0)
    /* C5EA4 80142DB4 846E28D0 */  lh         $t6, 0x28D0($v1)
    /* C5EA8 80142DB8 3C0F8019 */  lui        $t7, %hi(D_8018EC20)
    /* C5EAC 80142DBC 24020032 */  addiu      $v0, $zero, 0x32
    /* C5EB0 80142DC0 01EE7821 */  addu       $t7, $t7, $t6
    /* C5EB4 80142DC4 91EFEC20 */  lbu        $t7, %lo(D_8018EC20)($t7)
    /* C5EB8 80142DC8 25F8FFFF */  addiu      $t8, $t7, -0x1
    /* C5EBC 80142DCC 2F010006 */  sltiu      $at, $t8, 0x6
    /* C5EC0 80142DD0 10200012 */  beqz       $at, .L80142E1C
  alabel func_80142DD4
    /* C5EC4 80142DD4 0018C080 */   sll       $t8, $t8, 2
    /* C5EC8 80142DD8 3C01801A */  lui        $at, %hi(jtbl_80198120)
  alabel func_80142DDC
    /* C5ECC 80142DDC 00380821 */  addu       $at, $at, $t8
    /* C5ED0 80142DE0 8C388120 */  lw         $t8, %lo(jtbl_80198120)($at)
    /* C5ED4 80142DE4 03000008 */  jr         $t8
    /* C5ED8 80142DE8 00000000 */   nop
    /* C5EDC 80142DEC 1000000B */  b          .L80142E1C
    /* C5EE0 80142DF0 2402001E */   addiu     $v0, $zero, 0x1E
    /* C5EE4 80142DF4 10000009 */  b          .L80142E1C
    /* C5EE8 80142DF8 24020028 */   addiu     $v0, $zero, 0x28
    /* C5EEC 80142DFC 10000007 */  b          .L80142E1C
    /* C5EF0 80142E00 24020032 */   addiu     $v0, $zero, 0x32
    /* C5EF4 80142E04 10000005 */  b          .L80142E1C
    /* C5EF8 80142E08 24020064 */   addiu     $v0, $zero, 0x64
    /* C5EFC 80142E0C 10000003 */  b          .L80142E1C
    /* C5F00 80142E10 240200C8 */   addiu     $v0, $zero, 0xC8
    /* C5F04 80142E14 10000001 */  b          .L80142E1C
    /* C5F08 80142E18 2402012C */   addiu     $v0, $zero, 0x12C
  .L80142E1C:
    /* C5F0C 80142E1C 44822000 */  mtc1       $v0, $ft0
    /* C5F10 80142E20 3C014024 */  lui        $at, (0x40240000 >> 16)
    /* C5F14 80142E24 44815800 */  mtc1       $at, $ft3f
    /* C5F18 80142E28 468021A0 */  cvt.s.w    $ft1, $ft0
    /* C5F1C 80142E2C 44805000 */  mtc1       $zero, $ft3
    /* C5F20 80142E30 3C013FE8 */  lui        $at, (0x3FE80000 >> 16)
    /* C5F24 80142E34 44819800 */  mtc1       $at, $ft5f
    /* C5F28 80142E38 44809000 */  mtc1       $zero, $ft5
    /* C5F2C 80142E3C 8C642960 */  lw         $a0, 0x2960($v1)
    /* C5F30 80142E40 46003221 */  cvt.d.s    $ft2, $ft1
    /* C5F34 80142E44 8CE50024 */  lw         $a1, 0x24($a3)
    /* C5F38 80142E48 462A4402 */  mul.d      $ft4, $ft2, $ft3
    /* C5F3C 80142E4C 00000000 */  nop
    /* C5F40 80142E50 46328102 */  mul.d      $ft0, $ft4, $ft5
    /* C5F44 80142E54 462021A0 */  cvt.s.d    $ft1, $ft0
    /* C5F48 80142E58 44063000 */  mfc1       $a2, $ft1
    /* C5F4C 80142E5C 0C051687 */  jal        func_80145A1C
    /* C5F50 80142E60 00000000 */   nop
    /* C5F54 80142E64 50400004 */  beql       $v0, $zero, .L80142E78
  alabel func_80142E68
    /* C5F58 80142E68 24020001 */   addiu     $v0, $zero, 0x1
    /* C5F5C 80142E6C 10000002 */  b          .L80142E78
    /* C5F60 80142E70 00001025 */   or        $v0, $zero, $zero
    /* C5F64 80142E74 24020001 */  addiu      $v0, $zero, 0x1
  .L80142E78:
    /* C5F68 80142E78 8FBF0014 */  lw         $ra, 0x14($sp)
  alabel func_80142E7C
    /* C5F6C 80142E7C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* C5F70 80142E80 03E00008 */  jr         $ra
    /* C5F74 80142E84 00000000 */   nop
endlabel func_80142D4C

nonmatching func_80142E88, 0x8

glabel func_80142E88
    /* C5F78 80142E88 27BDFF30 */  addiu      $sp, $sp, -0xD0
    /* C5F7C 80142E8C 8FAE00E0 */  lw         $t6, 0xE0($sp)
endlabel func_80142E88

nonmatching func_80142E90, 0xC

glabel func_80142E90
    /* C5F80 80142E90 AFBE0068 */  sw         $fp, 0x68($sp)
    /* C5F84 80142E94 AFB60060 */  sw         $s6, 0x60($sp)
    /* C5F88 80142E98 44856000 */  mtc1       $a1, $fa0
endlabel func_80142E90

nonmatching D_80142E9C, 0xF4

glabel D_80142E9C
    /* C5F8C 80142E9C 29C1000F */  slti       $at, $t6, 0xF
    /* C5F90 80142EA0 0080B025 */  or         $s6, $a0, $zero
    /* C5F94 80142EA4 AFBF006C */  sw         $ra, 0x6C($sp)
    /* C5F98 80142EA8 AFB70064 */  sw         $s7, 0x64($sp)
    /* C5F9C 80142EAC AFB5005C */  sw         $s5, 0x5C($sp)
    /* C5FA0 80142EB0 AFB40058 */  sw         $s4, 0x58($sp)
    /* C5FA4 80142EB4 AFB30054 */  sw         $s3, 0x54($sp)
    /* C5FA8 80142EB8 AFB20050 */  sw         $s2, 0x50($sp)
    /* C5FAC 80142EBC AFB1004C */  sw         $s1, 0x4C($sp)
    /* C5FB0 80142EC0 AFB00048 */  sw         $s0, 0x48($sp)
    /* C5FB4 80142EC4 F7BE0040 */  sdc1       $fs5, 0x40($sp)
    /* C5FB8 80142EC8 F7BC0038 */  sdc1       $fs4, 0x38($sp)
    /* C5FBC 80142ECC F7BA0030 */  sdc1       $fs3, 0x30($sp)
    /* C5FC0 80142ED0 F7B80028 */  sdc1       $fs2, 0x28($sp)
  alabel func_80142ED4
    /* C5FC4 80142ED4 F7B60020 */  sdc1       $fs1, 0x20($sp)
    /* C5FC8 80142ED8 F7B40018 */  sdc1       $fs0, 0x18($sp)
    /* C5FCC 80142EDC AFA600D8 */  sw         $a2, 0xD8($sp)
    /* C5FD0 80142EE0 AFA700DC */  sw         $a3, 0xDC($sp)
    /* C5FD4 80142EE4 14200004 */  bnez       $at, .L80142EF8
    /* C5FD8 80142EE8 0000F025 */   or        $fp, $zero, $zero
    /* C5FDC 80142EEC 240F000F */  addiu      $t7, $zero, 0xF
    /* C5FE0 80142EF0 AFAF00E0 */  sw         $t7, 0xE0($sp)
    /* C5FE4 80142EF4 241E0001 */  addiu      $fp, $zero, 0x1
  .L80142EF8:
    /* C5FE8 80142EF8 8FB800E0 */  lw         $t8, 0xE0($sp)
    /* C5FEC 80142EFC 3C158000 */  lui        $s5, %hi(func_800047C0)
    /* C5FF0 80142F00 26B547C0 */  addiu      $s5, $s5, %lo(func_800047C0)
    /* C5FF4 80142F04 1B00007A */  blez       $t8, .L801430F0
    /* C5FF8 80142F08 0000A025 */   or        $s4, $zero, $zero
    /* C5FFC 80142F0C 3C01801A */  lui        $at, %hi(D_80198138)
    /* C6000 80142F10 D43E8138 */  ldc1       $fs5, %lo(D_80198138)($at)
    /* C6004 80142F14 3C0140F0 */  lui        $at, (0x40F00000 >> 16)
    /* C6008 80142F18 4481E800 */  mtc1       $at, $fs4f
    /* C600C 80142F1C 3C014000 */  lui        $at, (0x40000000 >> 16)
    /* C6010 80142F20 4481D800 */  mtc1       $at, $fs3f
    /* C6014 80142F24 3C01801A */  lui        $at, %hi(D_80198140)
    /* C6018 80142F28 3C178006 */  lui        $s7, %hi(D_800594B8)
    /* C601C 80142F2C 4480E000 */  mtc1       $zero, $fs4
    /* C6020 80142F30 4480D000 */  mtc1       $zero, $fs3
    /* C6024 80142F34 26F794B8 */  addiu      $s7, $s7, %lo(D_800594B8)
    /* C6028 80142F38 D4388140 */  ldc1       $fs2, %lo(D_80198140)($at)
    /* C602C 80142F3C 460065A1 */  cvt.d.s    $fs1, $fa0
  .L80142F40:
    /* C6030 80142F40 02A0F809 */  jalr       $s5
    /* C6034 80142F44 24044E20 */   addiu     $a0, $zero, 0x4E20
    /* C6038 80142F48 2459D8F0 */  addiu      $t9, $v0, -0x2710
    /* C603C 80142F4C 44992000 */  mtc1       $t9, $ft0
    /* C6040 80142F50 24044E20 */  addiu      $a0, $zero, 0x4E20
    /* C6044 80142F54 468021A0 */  cvt.s.w    $ft1, $ft0
    /* C6048 80142F58 C6C40050 */  lwc1       $ft0, 0x50($s6)
    /* C604C 80142F5C 46003221 */  cvt.d.s    $ft2, $ft1
    /* C6050 80142F60 460021A1 */  cvt.d.s    $ft1, $ft0
    /* C6054 80142F64 46384282 */  mul.d      $ft3, $ft2, $fs2
    /* C6058 80142F68 00000000 */  nop
    /* C605C 80142F6C 46365402 */  mul.d      $ft4, $ft3, $fs1
    /* C6060 80142F70 463A8483 */  div.d      $ft5, $ft4, $fs3
    /* C6064 80142F74 44948000 */  mtc1       $s4, $ft4
    /* C6068 80142F78 00000000 */  nop
    /* C606C 80142F7C 46808120 */  cvt.s.w    $ft0, $ft4
    /* C6070 80142F80 46002021 */  cvt.d.s    $fv0, $ft0
    /* C6074 80142F84 46269200 */  add.d      $ft2, $ft5, $ft1
    /* C6078 80142F88 462042A0 */  cvt.s.d    $ft3, $ft2
    /* C607C 80142F8C 46200200 */  add.d      $ft2, $fv0, $fv0
endlabel D_80142E9C

nonmatching func_80142F90, 0x18

glabel func_80142F90
    /* C6080 80142F90 E7AA00C0 */  swc1       $ft3, 0xC0($sp)
    /* C6084 80142F94 C6D20054 */  lwc1       $ft5, 0x54($s6)
    /* C6088 80142F98 460091A1 */  cvt.d.s    $ft1, $ft5
    /* C608C 80142F9C 46283280 */  add.d      $ft3, $ft1, $ft2
    /* C6090 80142FA0 46205420 */  cvt.s.d    $ft4, $ft3
    /* C6094 80142FA4 02A0F809 */  jalr       $s5
endlabel func_80142F90

nonmatching func_80142FA8, 0x190

glabel func_80142FA8
    /* C6098 80142FA8 E7B000C4 */  swc1       $ft4, 0xC4($sp)
    /* C609C 80142FAC 2448D8F0 */  addiu      $t0, $v0, -0x2710
    /* C60A0 80142FB0 44882000 */  mtc1       $t0, $ft0
    /* C60A4 80142FB4 2404001E */  addiu      $a0, $zero, 0x1E
    /* C60A8 80142FB8 2405001E */  addiu      $a1, $zero, 0x1E
    /* C60AC 80142FBC 468024A0 */  cvt.s.w    $ft5, $ft0
    /* C60B0 80142FC0 C6C40058 */  lwc1       $ft0, 0x58($s6)
    /* C60B4 80142FC4 27A600C0 */  addiu      $a2, $sp, 0xC0
    /* C60B8 80142FC8 3C072080 */  lui        $a3, (0x20800000 >> 16)
    /* C60BC 80142FCC 460091A1 */  cvt.d.s    $ft1, $ft5
    /* C60C0 80142FD0 460024A1 */  cvt.d.s    $ft5, $ft0
    /* C60C4 80142FD4 46383202 */  mul.d      $ft2, $ft1, $fs2
    /* C60C8 80142FD8 00000000 */  nop
    /* C60CC 80142FDC 46364282 */  mul.d      $ft3, $ft2, $fs1
    /* C60D0 80142FE0 463A5403 */  div.d      $ft4, $ft3, $fs3
    /* C60D4 80142FE4 46328180 */  add.d      $ft1, $ft4, $ft5
    /* C60D8 80142FE8 46203220 */  cvt.s.d    $ft2, $ft1
    /* C60DC 80142FEC 02E0F809 */  jalr       $s7
    /* C60E0 80142FF0 E7A800C8 */   swc1      $ft2, 0xC8($sp)
    /* C60E4 80142FF4 1040003A */  beqz       $v0, .L801430E0
    /* C60E8 80142FF8 00408025 */   or        $s0, $v0, $zero
    /* C60EC 80142FFC 449E5000 */  mtc1       $fp, $ft3
    /* C60F0 80143000 3C118006 */  lui        $s1, %hi(func_8005C898)
    /* C60F4 80143004 3C128006 */  lui        $s2, %hi(func_8005CC84)
    /* C60F8 80143008 46805121 */  cvt.d.w    $ft0, $ft3
    /* C60FC 8014300C 3C138006 */  lui        $s3, %hi(func_8005D384)
    /* C6100 80143010 2673D384 */  addiu      $s3, $s3, %lo(func_8005D384)
    /* C6104 80143014 2652CC84 */  addiu      $s2, $s2, %lo(func_8005CC84)
    /* C6108 80143018 2631C898 */  addiu      $s1, $s1, %lo(func_8005C898)
    /* C610C 8014301C 4624F502 */  mul.d      $fs0, $fs5, $ft0
    /* C6110 80143020 02A0F809 */  jalr       $s5
    /* C6114 80143024 24047FFF */   addiu     $a0, $zero, 0x7FFF
    /* C6118 80143028 44828000 */  mtc1       $v0, $ft4
    /* C611C 8014302C 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
    /* C6120 80143030 04410005 */  bgez       $v0, .L80143048
    /* C6124 80143034 468084A1 */   cvt.d.w   $ft5, $ft4
    /* C6128 80143038 44813800 */  mtc1       $at, $ft1f
    /* C612C 8014303C 44803000 */  mtc1       $zero, $ft1
    /* C6130 80143040 00000000 */  nop
    /* C6134 80143044 46269480 */  add.d      $ft5, $ft5, $ft1
  .L80143048:
    /* C6138 80143048 463C9203 */  div.d      $ft2, $ft5, $fs4
    /* C613C 8014304C 3C01801A */  lui        $at, %hi(D_80198148)
    /* C6140 80143050 D4268148 */  ldc1       $ft1, %lo(D_80198148)($at)
    /* C6144 80143054 02002025 */  or         $a0, $s0, $zero
    /* C6148 80143058 27A500B4 */  addiu      $a1, $sp, 0xB4
    /* C614C 8014305C 34068000 */  ori        $a2, $zero, 0x8000
    /* C6150 80143060 462042A0 */  cvt.s.d    $ft3, $ft2
    /* C6154 80143064 46005121 */  cvt.d.s    $ft0, $ft3
    /* C6158 80143068 463E2402 */  mul.d      $ft4, $ft0, $fs5
    /* C615C 8014306C 46268480 */  add.d      $ft5, $ft4, $ft1
    /* C6160 80143070 46349200 */  add.d      $ft2, $ft5, $fs0
    /* C6164 80143074 46204020 */  cvt.s.d    $fv0, $ft2
    /* C6168 80143078 E7A000B8 */  swc1       $fv0, 0xB8($sp)
    /* C616C 8014307C E7A000B4 */  swc1       $fv0, 0xB4($sp)
    /* C6170 80143080 0220F809 */  jalr       $s1
    /* C6174 80143084 E7A000BC */   swc1      $fv0, 0xBC($sp)
    /* C6178 80143088 02002025 */  or         $a0, $s0, $zero
    /* C617C 8014308C 8FA500DC */  lw         $a1, 0xDC($sp)
    /* C6180 80143090 0240F809 */  jalr       $s2
    /* C6184 80143094 24060800 */   addiu     $a2, $zero, 0x800
    /* C6188 80143098 0260F809 */  jalr       $s3
    /* C618C 8014309C 02002025 */   or        $a0, $s0, $zero
    /* C6190 801430A0 1040000C */  beqz       $v0, .L801430D4
    /* C6194 801430A4 3C198006 */   lui       $t9, %hi(func_8005D13C)
    /* C6198 801430A8 3C01801A */  lui        $at, %hi(D_80198150)
    /* C619C 801430AC C42A8150 */  lwc1       $ft3, %lo(D_80198150)($at)
    /* C61A0 801430B0 3C198006 */  lui        $t9, %hi(func_8005D0B4)
    /* C61A4 801430B4 2739D0B4 */  addiu      $t9, $t9, %lo(func_8005D0B4)
    /* C61A8 801430B8 3C058014 */  lui        $a1, %hi(D_80145978)
    /* C61AC 801430BC 24A55978 */  addiu      $a1, $a1, %lo(D_80145978)
    /* C61B0 801430C0 02002025 */  or         $a0, $s0, $zero
    /* C61B4 801430C4 0320F809 */  jalr       $t9
    /* C61B8 801430C8 E44A0004 */   swc1      $ft3, 0x4($v0)
    /* C61BC 801430CC 10000005 */  b          .L801430E4
    /* C61C0 801430D0 8FA900E0 */   lw        $t1, 0xE0($sp)
  .L801430D4:
    /* C61C4 801430D4 2739D13C */  addiu      $t9, $t9, %lo(func_8005D13C)
    /* C61C8 801430D8 0320F809 */  jalr       $t9
    /* C61CC 801430DC 02002025 */   or        $a0, $s0, $zero
  .L801430E0:
    /* C61D0 801430E0 8FA900E0 */  lw         $t1, 0xE0($sp)
  .L801430E4:
    /* C61D4 801430E4 26940001 */  addiu      $s4, $s4, 0x1
    /* C61D8 801430E8 1689FF95 */  bne        $s4, $t1, .L80142F40
    /* C61DC 801430EC 00000000 */   nop
  .L801430F0:
    /* C61E0 801430F0 8FBF006C */  lw         $ra, 0x6C($sp)
    /* C61E4 801430F4 D7B40018 */  ldc1       $fs0, 0x18($sp)
    /* C61E8 801430F8 D7B60020 */  ldc1       $fs1, 0x20($sp)
    /* C61EC 801430FC D7B80028 */  ldc1       $fs2, 0x28($sp)
    /* C61F0 80143100 D7BA0030 */  ldc1       $fs3, 0x30($sp)
    /* C61F4 80143104 D7BC0038 */  ldc1       $fs4, 0x38($sp)
    /* C61F8 80143108 D7BE0040 */  ldc1       $fs5, 0x40($sp)
    /* C61FC 8014310C 8FB00048 */  lw         $s0, 0x48($sp)
    /* C6200 80143110 8FB1004C */  lw         $s1, 0x4C($sp)
    /* C6204 80143114 8FB20050 */  lw         $s2, 0x50($sp)
    /* C6208 80143118 8FB30054 */  lw         $s3, 0x54($sp)
    /* C620C 8014311C 8FB40058 */  lw         $s4, 0x58($sp)
    /* C6210 80143120 8FB5005C */  lw         $s5, 0x5C($sp)
    /* C6214 80143124 8FB60060 */  lw         $s6, 0x60($sp)
    /* C6218 80143128 8FB70064 */  lw         $s7, 0x64($sp)
    /* C621C 8014312C 8FBE0068 */  lw         $fp, 0x68($sp)
    /* C6220 80143130 03E00008 */  jr         $ra
    /* C6224 80143134 27BD00D0 */   addiu     $sp, $sp, 0xD0
endlabel func_80142FA8

nonmatching func_80143138, 0x14

glabel func_80143138
    /* C6228 80143138 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* C622C 8014313C 3C198006 */  lui        $t9, %hi(func_8005D384)
    /* C6230 80143140 AFBF0014 */  sw         $ra, 0x14($sp)
    /* C6234 80143144 2739D384 */  addiu      $t9, $t9, %lo(func_8005D384)
    /* C6238 80143148 0320F809 */  jalr       $t9
endlabel func_80143138

nonmatching func_8014314C, 0x60

glabel func_8014314C
    /* C623C 8014314C AFA40038 */  sw         $a0, 0x38($sp)
    /* C6240 80143150 44802000 */  mtc1       $zero, $ft0
    /* C6244 80143154 3C01801A */  lui        $at, %hi(D_80198154)
    /* C6248 80143158 C4208154 */  lwc1       $fv0, %lo(D_80198154)($at)
    /* C624C 8014315C AFA20034 */  sw         $v0, 0x34($sp)
    /* C6250 80143160 E7A40030 */  swc1       $ft0, 0x30($sp)
    /* C6254 80143164 E7A40028 */  swc1       $ft0, 0x28($sp)
    /* C6258 80143168 C4460004 */  lwc1       $ft1, 0x4($v0)
    /* C625C 8014316C 3C198006 */  lui        $t9, %hi(func_8005C638)
    /* C6260 80143170 2739C638 */  addiu      $t9, $t9, %lo(func_8005C638)
    /* C6264 80143174 8FA40038 */  lw         $a0, 0x38($sp)
    /* C6268 80143178 27A50028 */  addiu      $a1, $sp, 0x28
    /* C626C 8014317C 24064000 */  addiu      $a2, $zero, 0x4000
    /* C6270 80143180 E7A0001C */  swc1       $fv0, 0x1C($sp)
    /* C6274 80143184 E7A00020 */  swc1       $fv0, 0x20($sp)
    /* C6278 80143188 E7A00024 */  swc1       $fv0, 0x24($sp)
    /* C627C 8014318C 0320F809 */  jalr       $t9
    /* C6280 80143190 E7A6002C */   swc1      $ft1, 0x2C($sp)
    /* C6284 80143194 3C198006 */  lui        $t9, %hi(func_8005C898)
    /* C6288 80143198 2739C898 */  addiu      $t9, $t9, %lo(func_8005C898)
    /* C628C 8014319C 8FA40038 */  lw         $a0, 0x38($sp)
    /* C6290 801431A0 27A5001C */  addiu      $a1, $sp, 0x1C
    /* C6294 801431A4 0320F809 */  jalr       $t9
    /* C6298 801431A8 24062000 */   addiu     $a2, $zero, 0x2000
endlabel func_8014314C

nonmatching func_801431AC, 0x20

glabel func_801431AC
    /* C629C 801431AC 8FA30034 */  lw         $v1, 0x34($sp)
    /* C62A0 801431B0 3C01801A */  lui        $at, %hi(D_80198158)
    /* C62A4 801431B4 D4328158 */  ldc1       $ft5, %lo(D_80198158)($at)
    /* C62A8 801431B8 C46A0004 */  lwc1       $ft3, 0x4($v1)
    /* C62AC 801431BC 46005421 */  cvt.d.s    $ft4, $ft3
    /* C62B0 801431C0 46328100 */  add.d      $ft0, $ft4, $ft5
    /* C62B4 801431C4 462021A0 */  cvt.s.d    $ft1, $ft0
    /* C62B8 801431C8 E4660004 */  swc1       $ft1, 0x4($v1)
endlabel func_801431AC

nonmatching func_801431CC, 0x10

glabel func_801431CC
    /* C62BC 801431CC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* C62C0 801431D0 27BD0038 */  addiu      $sp, $sp, 0x38
    /* C62C4 801431D4 03E00008 */  jr         $ra
    /* C62C8 801431D8 00000000 */   nop
endlabel func_801431CC

nonmatching func_801431DC, 0x4

glabel func_801431DC
    /* C62CC 801431DC C4A40050 */  lwc1       $ft0, 0x50($a1)
endlabel func_801431DC
