.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80016A60, 0x98

glabel func_80016A60
    jr $ra
    nop
  .L80016AAC:
    jr $ra
    nop
  .L80016AC8:
    jr $ra
    nop
  .L80016AE0:
    jr $ra
    nop
endlabel func_80016A60

nonmatching func_80016AF8, 0x40

glabel func_80016AF8
    jr $ra
    nop
endlabel func_80016AF8

nonmatching func_80016B38, 0x10

glabel func_80016B38
    jr $ra
    nop
endlabel func_80016B38

nonmatching func_80016B48, 0x74

glabel func_80016B48
    jr $ra
    nop
  .L80016B74:
    jr $ra
    nop
  .L80016BA0:
    jr $ra
    nop
  .L80016BB0:
    jr $ra
    nop
endlabel func_80016B48

nonmatching func_80016BBC, 0x8

glabel func_80016BBC
    jr $ra
    nop
endlabel func_80016BBC

nonmatching func_80016BC4, 0x64

glabel func_80016BC4
    jr $ra
    nop
  .L80016C18:
    jr $ra
    nop
endlabel func_80016BC4

nonmatching func_80016C28, 0x8

glabel func_80016C28
    jr $ra
    nop
endlabel func_80016C28

nonmatching func_80016C30, 0x8

glabel func_80016C30
    jr $ra
    nop
endlabel func_80016C30

nonmatching func_80016C38, 0xC

glabel func_80016C38
    jr $ra
    nop
endlabel func_80016C38

nonmatching func_80016C44, 0xC

glabel func_80016C44
    jr $ra
    nop
endlabel func_80016C44

nonmatching func_80016C50, 0x50

glabel func_80016C50
    jr $ra
    nop
  .L80016C78:
    jr $ra
    nop
  .L80016C8C:
    jr $ra
    nop
endlabel func_80016C50

nonmatching func_80016CA0, 0x90

glabel func_80016CA0
    jr $ra
    nop
  .L80016CC8:
    jr $ra
    nop
  .L80016D08:
    jr $ra
    nop
  .L80016D10:
    jr $ra
    nop
  .L80016D1C:
    jr $ra
    nop
endlabel func_80016CA0

nonmatching func_80016D30, 0x8

glabel func_80016D30
    jr $ra
    nop
endlabel func_80016D30

nonmatching func_80016D38, 0xA0

glabel func_80016D38
    jr $ra
    nop
  .L80016D64:
    jr $ra
    nop
  .L80016DB4:
    jr $ra
    nop
  .L80016DBC:
    jr $ra
    nop
  .L80016DC0:
    jr $ra
    nop
endlabel func_80016D38

nonmatching func_80016DD8, 0x28

glabel func_80016DD8
    jr $ra
    nop
endlabel func_80016DD8
