.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80169D30, 0x38

glabel func_80169D30
    jr $ra
    nop
endlabel func_80169D30

nonmatching D_80169D68, 0x164

glabel D_80169D68
    jr $ra
    nop
  .L80169E08:
    jr $ra
    nop
  .L80169E78:
    jr $ra
    nop
  .L80169E80:
    jr $ra
    nop
  .L80169EC4:
    jr $ra
    nop
endlabel D_80169D68

nonmatching func_80169ECC, 0x290

glabel func_80169ECC
    jr $ra
    nop
  .L80169F00:
    jr $ra
    nop
  .L80169F20:
    jr $ra
    nop
  .L80169F88:
    jr $ra
    nop
  .L80169FF4:
    jr $ra
    nop
  .L8016A0A4:
    jr $ra
    nop
endlabel func_80169ECC

nonmatching func_8016A15C, 0x45C

glabel func_8016A15C
    jr $ra
    nop
  .L8016A164:
    jr $ra
    nop
  .L8016A210:
    jr $ra
    nop
  .L8016A294:
    jr $ra
    nop
  .L8016A298:
    jr $ra
    nop
  .L8016A2E4:
    jr $ra
    nop
  .L8016A2F0:
    jr $ra
    nop
  .L8016A350:
    jr $ra
    nop
  .L8016A3EC:
    jr $ra
    nop
  .L8016A498:
    jr $ra
    nop
  .L8016A548:
    jr $ra
    nop
endlabel func_8016A15C

nonmatching func_8016A5B8, 0x408

glabel func_8016A5B8
    jr $ra
    nop
  .L8016A5C0:
    jr $ra
    nop
  .L8016A5C8:
    jr $ra
    nop
  .L8016A60C:
    jr $ra
    nop
  .L8016A614:
    jr $ra
    nop
  .L8016A6AC:
    jr $ra
    nop
  .L8016A6CC:
    jr $ra
    nop
  .L8016A700:
    jr $ra
    nop
  .L8016A74C:
    jr $ra
    nop
  .L8016A798:
    jr $ra
    nop
  .L8016A7C8:
    jr $ra
    nop
  .L8016A7E4:
    jr $ra
    nop
  .L8016A834:
    jr $ra
    nop
  .L8016A868:
    jr $ra
    nop
  .L8016A870:
    jr $ra
    nop
  .L8016A874:
    jr $ra
    nop
  .L8016A880:
    jr $ra
    nop
  .L8016A8D8:
    jr $ra
    nop
  .L8016A8FC:
    jr $ra
    nop
  .L8016A918:
    jr $ra
    nop
  .L8016A960:
    jr $ra
    nop
  .L8016A984:
    jr $ra
    nop
  .L8016A9A0:
    jr $ra
    nop
endlabel func_8016A5B8

nonmatching func_8016A9C0, 0x78

glabel func_8016A9C0
    jr $ra
    nop
  .L8016A9DC:
    jr $ra
    nop
  .L8016AA04:
    jr $ra
    nop
  .L8016AA24:
    jr $ra
    nop
  .L8016AA28:
    jr $ra
    nop
endlabel func_8016A9C0

nonmatching func_8016AA38, 0x78

glabel func_8016AA38
    jr $ra
    nop
  .L8016AA54:
    jr $ra
    nop
  .L8016AA7C:
    jr $ra
    nop
  .L8016AA9C:
    jr $ra
    nop
  .L8016AAA0:
    jr $ra
    nop
endlabel func_8016AA38

nonmatching func_8016AAB0, 0x274

glabel func_8016AAB0
    jr $ra
    nop
  .L8016AB70:
    jr $ra
    nop
  .L8016AB98:
    jr $ra
    nop
  .L8016ABB4:
    jr $ra
    nop
  .L8016ABD4:
    jr $ra
    nop
  .L8016ABFC:
    jr $ra
    nop
  .L8016AC74:
    jr $ra
    nop
  .L8016AC98:
    jr $ra
    nop
  .L8016ACC0:
    jr $ra
    nop
  .L8016ACCC:
    jr $ra
    nop
  .L8016AD14:
    jr $ra
    nop
  .L8016AD18:
    jr $ra
    nop
endlabel func_8016AAB0

nonmatching func_8016AD24, 0x8

glabel func_8016AD24
    jr $ra
    nop
endlabel func_8016AD24

nonmatching func_8016AD2C, 0xE4

glabel func_8016AD2C
    jr $ra
    nop
  .L8016ADF4:
    jr $ra
    nop
endlabel func_8016AD2C

nonmatching func_8016AE10, 0xB4

glabel func_8016AE10
    jr $ra
    nop
  .L8016AE24:
    jr $ra
    nop
  .L8016AE68:
    jr $ra
    nop
  .L8016AE88:
    jr $ra
    nop
  .L8016AE98:
    jr $ra
    nop
endlabel func_8016AE10

nonmatching func_8016AEC4, 0x1C

glabel func_8016AEC4
    jr $ra
    nop
endlabel func_8016AEC4
