.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8005AEC0, 0x4

glabel func_8005AEC0
    jr $ra
    nop
endlabel func_8005AEC0

nonmatching func_8005AEC4, 0x4

glabel func_8005AEC4
    jr $ra
    nop
endlabel func_8005AEC4

nonmatching D_8005AEC8, 0x98

glabel D_8005AEC8
    jr $ra
    nop
  .L8005AF34:
    jr $ra
    nop
  .L8005AF40:
    jr $ra
    nop
  .L8005AF4C:
    jr $ra
    nop
endlabel D_8005AEC8

nonmatching D_8005AF60, 0x40

glabel D_8005AF60
    jr $ra
    nop
  .L8005AF8C:
    jr $ra
    nop
endlabel D_8005AF60
