.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800043E0, 0x12C

glabel func_800043E0
    jr $ra
    nop
  .L80004408:
    jr $ra
    nop
  .L8000440C:
    jr $ra
    nop
endlabel func_800043E0

nonmatching func_8000450C, 0x170

glabel func_8000450C
    jr $ra
    nop
  .L8000454C:
    jr $ra
    nop
  .L80004594:
    jr $ra
    nop
  .L80004664:
    jr $ra
    nop
  .L8000466C:
    jr $ra
    nop
endlabel func_8000450C
    /* 527C 8000467C 00000000 */  nop

nonmatching func_80004680, 0x18

glabel func_80004680
    jr $ra
    nop
  .L80004690:
    jr $ra
    nop
endlabel func_80004680

nonmatching func_80004698, 0x34

glabel func_80004698
    jr $ra
    nop
  .L800046C4:
    jr $ra
    nop
endlabel func_80004698

nonmatching func_800046CC, 0x54

glabel func_800046CC
    jr $ra
    nop
endlabel func_800046CC

nonmatching func_80004720, 0x90

glabel func_80004720
    jr $ra
    nop
  .L80004778:
    jr $ra
    nop
endlabel func_80004720

nonmatching func_800047B0, 0x10

glabel func_800047B0
    jr $ra
    nop
endlabel func_800047B0

nonmatching func_800047C0, 0x54

glabel func_800047C0
    jr $ra
    nop
  .L8000480C:
    jr $ra
    nop
endlabel func_800047C0

nonmatching func_80004814, 0x28

glabel func_80004814
    jr $ra
    nop
endlabel func_80004814

nonmatching func_8000483C, 0x20

glabel func_8000483C
    jr $ra
    nop
endlabel func_8000483C

nonmatching func_8000485C, 0x40

glabel func_8000485C
    jr $ra
    nop
endlabel func_8000485C
    /* 549C 8000489C 00000000 */  nop

nonmatching func_800048A0, 0x24

glabel func_800048A0
    jr $ra
    nop
endlabel func_800048A0

nonmatching func_800048C4, 0x28

glabel func_800048C4
    jr $ra
    nop
endlabel func_800048C4

nonmatching func_800048EC, 0x2C

glabel func_800048EC
    jr $ra
    nop
endlabel func_800048EC

nonmatching func_80004918, 0x28

glabel func_80004918
    jr $ra
    nop
endlabel func_80004918

nonmatching func_80004940, 0xA8

glabel func_80004940
    jr $ra
    nop
  .L80004970:
    jr $ra
    nop
  .L80004978:
    jr $ra
    nop
  .L80004988:
    jr $ra
    nop
  .L80004998:
    jr $ra
    nop
  .L800049B8:
    jr $ra
    nop
  .L800049D0:
    jr $ra
    nop
  .L800049D4:
    jr $ra
    nop
  .L800049DC:
    jr $ra
    nop
endlabel func_80004940

nonmatching func_800049E8, 0xBC

glabel func_800049E8
    jr $ra
    nop
  .L80004A04:
    jr $ra
    nop
  .L80004A24:
    jr $ra
    nop
  .L80004A38:
    jr $ra
    nop
  .L80004A48:
    jr $ra
    nop
  .L80004A70:
    jr $ra
    nop
  .L80004A8C:
    jr $ra
    nop
  .L80004A90:
    jr $ra
    nop
  .L80004A98:
    jr $ra
    nop
endlabel func_800049E8
    /* 56A4 80004AA4 00000000 */  nop
    /* 56A8 80004AA8 00000000 */  nop
    /* 56AC 80004AAC 00000000 */  nop

nonmatching func_80004AB0, 0x174

glabel func_80004AB0
    jr $ra
    nop
  .L80004AC0:
    jr $ra
    nop
  .L80004AC4:
    jr $ra
    nop
  .L80004AD4:
    jr $ra
    nop
  .L80004AD8:
    jr $ra
    nop
  .L80004AF0:
    jr $ra
    nop
  .L80004AF4:
    jr $ra
    nop
  .L80004B10:
    jr $ra
    nop
  .L80004B28:
    jr $ra
    nop
  .L80004B40:
    jr $ra
    nop
  .L80004B50:
    jr $ra
    nop
  .L80004B68:
    jr $ra
    nop
  .L80004B80:
    jr $ra
    nop
  .L80004B98:
    jr $ra
    nop
  .L80004BA8:
    jr $ra
    nop
  .L80004BC4:
    jr $ra
    nop
  .L80004BD0:
    jr $ra
    nop
  .L80004BE8:
    jr $ra
    nop
  .L80004C00:
    jr $ra
    nop
  .L80004C18:
    jr $ra
    nop
  .L80004C1C:
    jr $ra
    nop
endlabel func_80004AB0

nonmatching func_80004C24, 0x44

glabel func_80004C24
    jr $ra
    nop
endlabel func_80004C24

nonmatching func_80004C68, 0x44

glabel func_80004C68
    jr $ra
    nop
endlabel func_80004C68
    /* 58AC 80004CAC 00000000 */  nop

nonmatching func_80004CB0, 0x1A8

glabel func_80004CB0
    jr $ra
    nop
  .L80004CF8:
    jr $ra
    nop
  .L80004D54:
    jr $ra
    nop
  .L80004E48:
    jr $ra
    nop
endlabel func_80004CB0

nonmatching func_80004E58, 0x2C

glabel func_80004E58
    jr $ra
    nop
  .L80004E7C:
    jr $ra
    nop
endlabel func_80004E58

nonmatching func_80004E84, 0xC0

glabel func_80004E84
    jr $ra
    nop
  .L80004EB4:
    jr $ra
    nop
  .L80004EC8:
    jr $ra
    nop
  .L80004EE8:
    jr $ra
    nop
  .L80004F00:
    jr $ra
    nop
  .L80004F1C:
    jr $ra
    nop
  .L80004F24:
    jr $ra
    nop
  .L80004F28:
    jr $ra
    nop
endlabel func_80004E84

nonmatching func_80004F44, 0x228

glabel func_80004F44
    jr $ra
    nop
  .L80004F80:
    jr $ra
    nop
  .L80004F90:
    jr $ra
    nop
  .L80004FB4:
    jr $ra
    nop
  .L80004FE0:
    jr $ra
    nop
  .L80004FE4:
    jr $ra
    nop
  .L80004FF0:
    jr $ra
    nop
  .L80005000:
    jr $ra
    nop
  .L8000500C:
    jr $ra
    nop
  .L80005024:
    jr $ra
    nop
  .L8000502C:
    jr $ra
    nop
  .L80005048:
    jr $ra
    nop
  .L8000505C:
    jr $ra
    nop
  .L8000506C:
    jr $ra
    nop
  .L80005074:
    jr $ra
    nop
  .L800050A0:
    jr $ra
    nop
  .L800050BC:
    jr $ra
    nop
  .L800050D8:
    jr $ra
    nop
  .L80005110:
    jr $ra
    nop
  .L80005124:
    jr $ra
    nop
  .L80005128:
    jr $ra
    nop
  .L80005140:
    jr $ra
    nop
  .L80005144:
    jr $ra
    nop
  .L8000514C:
    jr $ra
    nop
endlabel func_80004F44

nonmatching func_8000516C, 0x250

glabel func_8000516C
    jr $ra
    nop
  .L800051B4:
    jr $ra
    nop
  .L800051D0:
    jr $ra
    nop
  .L800051FC:
    jr $ra
    nop
  .L80005200:
    jr $ra
    nop
  .L8000520C:
    jr $ra
    nop
  .L8000521C:
    jr $ra
    nop
  .L80005228:
    jr $ra
    nop
  .L80005240:
    jr $ra
    nop
  .L80005248:
    jr $ra
    nop
  .L80005264:
    jr $ra
    nop
  .L80005278:
    jr $ra
    nop
  .L80005288:
    jr $ra
    nop
  .L80005290:
    jr $ra
    nop
  .L800052C8:
    jr $ra
    nop
  .L800052F0:
    jr $ra
    nop
  .L80005318:
    jr $ra
    nop
  .L80005368:
    jr $ra
    nop
  .L80005390:
    jr $ra
    nop
  .L80005394:
    jr $ra
    nop
  .L800053AC:
    jr $ra
    nop
  .L800053B0:
    jr $ra
    nop
endlabel func_8000516C

nonmatching func_800053BC, 0xC8

glabel func_800053BC
    jr $ra
    nop
  .L800053F0:
    jr $ra
    nop
  .L8000540C:
    jr $ra
    nop
  .L8000543C:
    jr $ra
    nop
  .L80005448:
    jr $ra
    nop
  .L80005470:
    jr $ra
    nop
  .L8000547C:
    jr $ra
    nop
endlabel func_800053BC

nonmatching func_80005484, 0x2C

glabel func_80005484
    jr $ra
    nop
  .L800054A8:
    jr $ra
    nop
endlabel func_80005484

nonmatching func_800054B0, 0x80

glabel func_800054B0
    jr $ra
    nop
  .L800054C8:
    jr $ra
    nop
  .L800054FC:
    jr $ra
    nop
  .L80005520:
    jr $ra
    nop
endlabel func_800054B0

nonmatching func_80005530, 0x44

glabel func_80005530
    jr $ra
    nop
  .L80005564:
    jr $ra
    nop
endlabel func_80005530

nonmatching func_80005574, 0x1B8

glabel func_80005574
    jr $ra
    nop
  .L800055B0:
    jr $ra
    nop
  .L800055EC:
    jr $ra
    nop
  .L80005618:
    jr $ra
    nop
  .L8000562C:
    jr $ra
    nop
  .L80005640:
    jr $ra
    nop
  .L80005650:
    jr $ra
    nop
  .L80005658:
    jr $ra
    nop
  .L80005664:
    jr $ra
    nop
  .L8000568C:
    jr $ra
    nop
  .L800056DC:
    jr $ra
    nop
  .L800056F4:
    jr $ra
    nop
  .L8000570C:
    jr $ra
    nop
  .L80005718:
    jr $ra
    nop
  .L8000571C:
    jr $ra
    nop
endlabel func_80005574

nonmatching func_8000572C, 0x88

glabel func_8000572C
    jr $ra
    nop
  .L80005790:
    jr $ra
    nop
  .L80005798:
    jr $ra
    nop
endlabel func_8000572C

nonmatching func_800057B4, 0x3C

glabel func_800057B4
    jr $ra
    nop
  .L800057DC:
    jr $ra
    nop
endlabel func_800057B4

nonmatching func_800057F0, 0x6C

glabel func_800057F0
    jr $ra
    nop
  .L80005848:
    jr $ra
    nop
endlabel func_800057F0

nonmatching func_8000585C, 0x48

glabel func_8000585C
    jr $ra
    nop
  .L8000588C:
    jr $ra
    nop
  .L8000589C:
    jr $ra
    nop
endlabel func_8000585C

nonmatching func_800058A4, 0x54

glabel func_800058A4
    jr $ra
    nop
  .L800058D4:
    jr $ra
    nop
  .L800058E0:
    jr $ra
    nop
  .L800058F0:
    jr $ra
    nop
endlabel func_800058A4

nonmatching func_800058F8, 0x50

glabel func_800058F8
    jr $ra
    nop
  .L80005924:
    jr $ra
    nop
  .L80005930:
    jr $ra
    nop
  .L80005940:
    jr $ra
    nop
endlabel func_800058F8

nonmatching func_80005948, 0x60

glabel func_80005948
    jr $ra
    nop
  .L80005970:
    jr $ra
    nop
  .L80005980:
    jr $ra
    nop
  .L80005990:
    jr $ra
    nop
  .L80005994:
    jr $ra
    nop
  .L800059A0:
    jr $ra
    nop
endlabel func_80005948

nonmatching func_800059A8, 0x88

glabel func_800059A8
    jr $ra
    nop
  .L800059E0:
    jr $ra
    nop
  .L80005A0C:
    jr $ra
    nop
  .L80005A1C:
    jr $ra
    nop
endlabel func_800059A8

nonmatching func_80005A30, 0x8C

glabel func_80005A30
    jr $ra
    nop
  .L80005A6C:
    jr $ra
    nop
  .L80005A98:
    jr $ra
    nop
  .L80005AA8:
    jr $ra
    nop
endlabel func_80005A30

nonmatching func_80005ABC, 0xB8

glabel func_80005ABC
    jr $ra
    nop
  .L80005B20:
    jr $ra
    nop
  .L80005B50:
    jr $ra
    nop
  .L80005B60:
    jr $ra
    nop
endlabel func_80005ABC

nonmatching func_80005B74, 0x130

glabel func_80005B74
    jr $ra
    nop
  .L80005BAC:
    jr $ra
    nop
  .L80005BF0:
    jr $ra
    nop
  .L80005C64:
    jr $ra
    nop
  .L80005C78:
    jr $ra
    nop
  .L80005C80:
    jr $ra
    nop
  .L80005C84:
    jr $ra
    nop
endlabel func_80005B74

nonmatching func_80005CA4, 0xEC

glabel func_80005CA4
    jr $ra
    nop
  .L80005CF0:
    jr $ra
    nop
  .L80005D6C:
    jr $ra
    nop
  .L80005D7C:
    jr $ra
    nop
  .L80005D80:
    jr $ra
    nop
endlabel func_80005CA4

nonmatching func_80005D90, 0x140

glabel func_80005D90
    jr $ra
    nop
  .L80005E10:
    jr $ra
    nop
  .L80005E94:
    jr $ra
    nop
  .L80005EA8:
    jr $ra
    nop
  .L80005EBC:
    jr $ra
    nop
  .L80005EC0:
    jr $ra
    nop
endlabel func_80005D90

nonmatching func_80005ED0, 0x34

glabel func_80005ED0
    jr $ra
    nop
  .L80005EF4:
    jr $ra
    nop
  .L80005EFC:
    jr $ra
    nop
endlabel func_80005ED0

nonmatching func_80005F04, 0x50

glabel func_80005F04
    jr $ra
    nop
  .L80005F28:
    jr $ra
    nop
  .L80005F3C:
    jr $ra
    nop
  .L80005F4C:
    jr $ra
    nop
endlabel func_80005F04

nonmatching func_80005F54, 0x34

glabel func_80005F54
    jr $ra
    nop
  .L80005F7C:
    jr $ra
    nop
  .L80005F80:
    jr $ra
    nop
endlabel func_80005F54

nonmatching func_80005F88, 0x4C

glabel func_80005F88
    jr $ra
    nop
  .L80005FA8:
    jr $ra
    nop
  .L80005FBC:
    jr $ra
    nop
  .L80005FCC:
    jr $ra
    nop
endlabel func_80005F88

nonmatching func_80005FD4, 0x3C

glabel func_80005FD4
    jr $ra
    nop
  .L80006000:
    jr $ra
    nop
  .L80006008:
    jr $ra
    nop
endlabel func_80005FD4

nonmatching func_80006010, 0x8C

glabel func_80006010
    jr $ra
    nop
endlabel func_80006010

nonmatching func_8000609C, 0x90

glabel func_8000609C
    jr $ra
    nop
endlabel func_8000609C

nonmatching func_8000612C, 0x8C

glabel func_8000612C
    jr $ra
    nop
endlabel func_8000612C

nonmatching func_800061B8, 0x90

glabel func_800061B8
    jr $ra
    nop
endlabel func_800061B8

nonmatching func_80006248, 0x394

glabel func_80006248
    jr $ra
    nop
  .L80006270:
    jr $ra
    nop
  .L80006274:
    jr $ra
    nop
  .L800062E4:
    jr $ra
    nop
  .L80006338:
    jr $ra
    nop
  .L800063D8:
    jr $ra
    nop
  .L80006438:
    jr $ra
    nop
  .L8000643C:
    jr $ra
    nop
endlabel func_80006248

nonmatching func_800065DC, 0x2C

glabel func_800065DC
    jr $ra
    nop
endlabel func_800065DC

nonmatching func_80006608, 0x88

glabel func_80006608
    jr $ra
    nop
  .L80006664:
    jr $ra
    nop
endlabel func_80006608

nonmatching func_80006690, 0x300

glabel func_80006690
    jr $ra
    nop
  .L800066E8:
    jr $ra
    nop
  .L80006704:
    jr $ra
    nop
  .L8000672C:
    jr $ra
    nop
  .L80006730:
    jr $ra
    nop
  .L800067A0:
    jr $ra
    nop
  .L800067C4:
    jr $ra
    nop
  .L800067EC:
    jr $ra
    nop
  .L80006824:
    jr $ra
    nop
  .L80006848:
    jr $ra
    nop
  .L80006888:
    jr $ra
    nop
  .L800068C8:
    jr $ra
    nop
  .L80006908:
    jr $ra
    nop
  .L8000692C:
    jr $ra
    nop
  .L80006960:
    jr $ra
    nop
endlabel func_80006690

nonmatching func_80006990, 0x688

glabel func_80006990
    jr $ra
    nop
  .L80006A40:
    jr $ra
    nop
  .L80006AA4:
    jr $ra
    nop
  .L80006AC0:
    jr $ra
    nop
  .L80006AFC:
    jr $ra
    nop
  .L80006B64:
    jr $ra
    nop
  .L80006BC0:
    jr $ra
    nop
  .L80006C18:
    jr $ra
    nop
  .L80006CA8:
    jr $ra
    nop
  .L80006DC8:
    jr $ra
    nop
  .L80006E2C:
    jr $ra
    nop
  .L80006E34:
    jr $ra
    nop
  .L80006F90:
    jr $ra
    nop
  .L80006FB4:
    jr $ra
    nop
  .L8000700C:
    jr $ra
    nop
  .L80007010:
    jr $ra
    nop
endlabel func_80006990

nonmatching func_80007018, 0xD8

glabel func_80007018
    jr $ra
    nop
  .L8000704C:
    jr $ra
    nop
  .L80007088:
    jr $ra
    nop
  .L800070D8:
    jr $ra
    nop
endlabel func_80007018

nonmatching func_800070F0, 0x2FC

glabel func_800070F0
    jr $ra
    nop
  .L8000715C:
    jr $ra
    nop
  .L8000717C:
    jr $ra
    nop
  .L800071AC:
    jr $ra
    nop
  .L800071C0:
    jr $ra
    nop
  .L80007224:
    jr $ra
    nop
  .L80007274:
    jr $ra
    nop
  .L800072C4:
    jr $ra
    nop
  .L8000730C:
    jr $ra
    nop
  .L80007320:
    jr $ra
    nop
  .L8000736C:
    jr $ra
    nop
  .L80007388:
    jr $ra
    nop
  .L80007390:
    jr $ra
    nop
  .L800073B0:
    jr $ra
    nop
  .L800073B4:
    jr $ra
    nop
  .L800073BC:
    jr $ra
    nop
endlabel func_800070F0

nonmatching func_800073EC, 0x2A8

glabel func_800073EC
    jr $ra
    nop
  .L8000741C:
    jr $ra
    nop
  .L80007458:
    jr $ra
    nop
  .L80007474:
    jr $ra
    nop
  .L800074E8:
    jr $ra
    nop
  .L80007538:
    jr $ra
    nop
  .L80007588:
    jr $ra
    nop
  .L800075D0:
    jr $ra
    nop
  .L800075F4:
    jr $ra
    nop
  .L80007648:
    jr $ra
    nop
  .L8000764C:
    jr $ra
    nop
  .L80007664:
    jr $ra
    nop
  .L80007684:
    jr $ra
    nop
  .L80007688:
    jr $ra
    nop
endlabel func_800073EC

nonmatching func_80007694, 0x2B8

glabel func_80007694
    jr $ra
    nop
  .L800076FC:
    jr $ra
    nop
  .L80007738:
    jr $ra
    nop
  .L8000779C:
    jr $ra
    nop
  .L800077E8:
    jr $ra
    nop
  .L80007838:
    jr $ra
    nop
  .L80007880:
    jr $ra
    nop
  .L80007894:
    jr $ra
    nop
  .L800078DC:
    jr $ra
    nop
  .L800078E0:
    jr $ra
    nop
  .L80007910:
    jr $ra
    nop
  .L80007914:
    jr $ra
    nop
  .L8000791C:
    jr $ra
    nop
endlabel func_80007694

nonmatching func_8000794C, 0x248

glabel func_8000794C
    jr $ra
    nop
  .L8000798C:
    jr $ra
    nop
  .L80007A00:
    jr $ra
    nop
  .L80007A50:
    jr $ra
    nop
  .L80007AA0:
    jr $ra
    nop
  .L80007AEC:
    jr $ra
    nop
  .L80007B0C:
    jr $ra
    nop
  .L80007B60:
    jr $ra
    nop
  .L80007B64:
    jr $ra
    nop
  .L80007B84:
    jr $ra
    nop
  .L80007B88:
    jr $ra
    nop
endlabel func_8000794C

nonmatching func_80007B94, 0xC38

glabel func_80007B94
    jr $ra
    nop
  .L80007C3C:
    jr $ra
    nop
  .L80007C5C:
    jr $ra
    nop
  .L80007C90:
    jr $ra
    nop
  .L80007D00:
    jr $ra
    nop
  .L80007D08:
    jr $ra
    nop
  .L80007DFC:
    jr $ra
    nop
  .L80007E2C:
    jr $ra
    nop
  .L80007E98:
    jr $ra
    nop
  .L80007EC8:
    jr $ra
    nop
  .L80007FC8:
    jr $ra
    nop
  .L80007FE0:
    jr $ra
    nop
  .L80008000:
    jr $ra
    nop
  .L80008008:
    jr $ra
    nop
  .L800080D8:
    jr $ra
    nop
  .L800080F0:
    jr $ra
    nop
  .L80008108:
    jr $ra
    nop
  .L80008230:
    jr $ra
    nop
  .L80008274:
    jr $ra
    nop
  .L80008288:
    jr $ra
    nop
  .L800082B0:
    jr $ra
    nop
  .L800082B4:
    jr $ra
    nop
  .L800082F0:
    jr $ra
    nop
  .L80008300:
    jr $ra
    nop
  .L8000832C:
    jr $ra
    nop
  .L80008330:
    jr $ra
    nop
  .L800083D8:
    jr $ra
    nop
  .L8000845C:
    jr $ra
    nop
  .L80008474:
    jr $ra
    nop
  .L80008534:
    jr $ra
    nop
  .L8000854C:
    jr $ra
    nop
  .L800085C8:
    jr $ra
    nop
  .L800085E0:
    jr $ra
    nop
  .L80008654:
    jr $ra
    nop
  .L80008670:
    jr $ra
    nop
  .L80008698:
    jr $ra
    nop
  .L800086BC:
    jr $ra
    nop
  .L800086E0:
    jr $ra
    nop
  .L80008704:
    jr $ra
    nop
  .L8000871C:
    jr $ra
    nop
  .L80008734:
    jr $ra
    nop
  .L80008738:
    jr $ra
    nop
  .L8000875C:
    jr $ra
    nop
  .L8000877C:
    jr $ra
    nop
  .L80008780:
    jr $ra
    nop
  .L80008788:
    jr $ra
    nop
  .L80008794:
    jr $ra
    nop
endlabel func_80007B94

nonmatching func_800087CC, 0x88

glabel func_800087CC
    jr $ra
    nop
  .L80008810:
    jr $ra
    nop
  .L8000881C:
    jr $ra
    nop
  .L80008838:
    jr $ra
    nop
endlabel func_800087CC

nonmatching func_80008854, 0xE0

glabel func_80008854
    jr $ra
    nop
  .L80008880:
    jr $ra
    nop
  .L80008890:
    jr $ra
    nop
  .L800088D0:
    jr $ra
    nop
  .L800088EC:
    jr $ra
    nop
  .L80008900:
    jr $ra
    nop
  .L80008908:
    jr $ra
    nop
  .L8000890C:
    jr $ra
    nop
  .L80008918:
    jr $ra
    nop
endlabel func_80008854

nonmatching func_80008934, 0x194

glabel func_80008934
    jr $ra
    nop
  .L80008980:
    jr $ra
    nop
  .L8000899C:
    jr $ra
    nop
  .L800089AC:
    jr $ra
    nop
  .L80008A20:
    jr $ra
    nop
  .L80008A68:
    jr $ra
    nop
  .L80008A6C:
    jr $ra
    nop
  .L80008A7C:
    jr $ra
    nop
  .L80008A88:
    jr $ra
    nop
  .L80008A94:
    jr $ra
    nop
  .L80008A9C:
    jr $ra
    nop
endlabel func_80008934

nonmatching func_80008AC8, 0x58

glabel func_80008AC8
    jr $ra
    nop
  .L80008B08:
    jr $ra
    nop
  .L80008B14:
    jr $ra
    nop
endlabel func_80008AC8

nonmatching func_80008B20, 0x198

glabel func_80008B20
    jr $ra
    nop
  .L80008B6C:
    jr $ra
    nop
  .L80008B98:
    jr $ra
    nop
  .L80008C04:
    jr $ra
    nop
  .L80008C50:
    jr $ra
    nop
  .L80008C5C:
    jr $ra
    nop
  .L80008C60:
    jr $ra
    nop
  .L80008C78:
    jr $ra
    nop
  .L80008C90:
    jr $ra
    nop
  .L80008C94:
    jr $ra
    nop
endlabel func_80008B20

nonmatching func_80008CB8, 0x34

glabel func_80008CB8
    jr $ra
    nop
endlabel func_80008CB8

nonmatching func_80008CEC, 0x3C

glabel func_80008CEC
    jr $ra
    nop
endlabel func_80008CEC

nonmatching func_80008D28, 0x258

glabel func_80008D28
    jr $ra
    nop
  .L80008D84:
    jr $ra
    nop
  .L80008DB0:
    jr $ra
    nop
  .L80008E38:
    jr $ra
    nop
  .L80008EB4:
    jr $ra
    nop
  .L80008F20:
    jr $ra
    nop
  .L80008F24:
    jr $ra
    nop
  .L80008F3C:
    jr $ra
    nop
  .L80008F54:
    jr $ra
    nop
  .L80008F58:
    jr $ra
    nop
endlabel func_80008D28

nonmatching func_80008F80, 0x88

glabel func_80008F80
    jr $ra
    nop
  .L80008FBC:
    jr $ra
    nop
  .L80008FE8:
    jr $ra
    nop
endlabel func_80008F80

nonmatching func_80009008, 0x94

glabel func_80009008
    jr $ra
    nop
  .L80009048:
    jr $ra
    nop
  .L80009078:
    jr $ra
    nop
endlabel func_80009008

nonmatching func_8000909C, 0x318

glabel func_8000909C
    jr $ra
    nop
  .L8000910C:
    jr $ra
    nop
  .L80009138:
    jr $ra
    nop
  .L8000919C:
    jr $ra
    nop
  .L800091E0:
    jr $ra
    nop
  .L800091EC:
    jr $ra
    nop
  .L80009270:
    jr $ra
    nop
  .L800092E8:
    jr $ra
    nop
  .L80009348:
    jr $ra
    nop
  .L8000934C:
    jr $ra
    nop
  .L80009368:
    jr $ra
    nop
  .L80009380:
    jr $ra
    nop
  .L80009384:
    jr $ra
    nop
endlabel func_8000909C

nonmatching func_800093B4, 0x9C

glabel func_800093B4
    jr $ra
    nop
  .L80009400:
    jr $ra
    nop
  .L8000942C:
    jr $ra
    nop
endlabel func_800093B4

nonmatching func_80009450, 0xA8

glabel func_80009450
    jr $ra
    nop
  .L800094A0:
    jr $ra
    nop
  .L800094D0:
    jr $ra
    nop
endlabel func_80009450

nonmatching func_800094F8, 0xF0

glabel func_800094F8
    jr $ra
    nop
  .L8000952C:
    jr $ra
    nop
  .L80009550:
    jr $ra
    nop
  .L80009574:
    jr $ra
    nop
  .L80009598:
    jr $ra
    nop
endlabel func_800094F8

nonmatching func_800095E8, 0x28

glabel func_800095E8
    jr $ra
    nop
endlabel func_800095E8

nonmatching func_80009610, 0x300

glabel func_80009610
    jr $ra
    nop
  .L80009674:
    jr $ra
    nop
  .L8000969C:
    jr $ra
    nop
  .L80009700:
    jr $ra
    nop
  .L80009740:
    jr $ra
    nop
  .L8000974C:
    jr $ra
    nop
  .L800097CC:
    jr $ra
    nop
  .L80009828:
    jr $ra
    nop
  .L8000986C:
    jr $ra
    nop
  .L800098B8:
    jr $ra
    nop
  .L800098CC:
    jr $ra
    nop
  .L800098E4:
    jr $ra
    nop
  .L800098E8:
    jr $ra
    nop
endlabel func_80009610

nonmatching func_80009910, 0x144

glabel func_80009910
    jr $ra
    nop
  .L80009948:
    jr $ra
    nop
  .L80009974:
    jr $ra
    nop
  .L80009994:
    jr $ra
    nop
  .L800099B4:
    jr $ra
    nop
  .L80009A08:
    jr $ra
    nop
  .L80009A2C:
    jr $ra
    nop
endlabel func_80009910

nonmatching func_80009A54, 0x34

glabel func_80009A54
    jr $ra
    nop
endlabel func_80009A54

nonmatching func_80009A88, 0x4EC

glabel func_80009A88
    jr $ra
    nop
  .L80009AF4:
    jr $ra
    nop
  .L80009B20:
    jr $ra
    nop
  .L80009B88:
    jr $ra
    nop
  .L80009BC8:
    jr $ra
    nop
  .L80009BD8:
    jr $ra
    nop
  .L80009C58:
    jr $ra
    nop
  .L80009CB4:
    jr $ra
    nop
  .L80009CF8:
    jr $ra
    nop
  .L80009D60:
    jr $ra
    nop
  .L80009DA0:
    jr $ra
    nop
  .L80009DB0:
    jr $ra
    nop
  .L80009E30:
    jr $ra
    nop
  .L80009E8C:
    jr $ra
    nop
  .L80009ED0:
    jr $ra
    nop
  .L80009F10:
    jr $ra
    nop
  .L80009F24:
    jr $ra
    nop
  .L80009F3C:
    jr $ra
    nop
  .L80009F40:
    jr $ra
    nop
endlabel func_80009A88

nonmatching func_80009F74, 0x1F8

glabel func_80009F74
    jr $ra
    nop
  .L80009FAC:
    jr $ra
    nop
  .L80009FCC:
    jr $ra
    nop
  .L80009FEC:
    jr $ra
    nop
  .L8000A00C:
    jr $ra
    nop
  .L8000A05C:
    jr $ra
    nop
  .L8000A080:
    jr $ra
    nop
  .L8000A0A8:
    jr $ra
    nop
  .L8000A0C8:
    jr $ra
    nop
  .L8000A11C:
    jr $ra
    nop
  .L8000A140:
    jr $ra
    nop
endlabel func_80009F74

nonmatching func_8000A16C, 0x34

glabel func_8000A16C
    jr $ra
    nop
endlabel func_8000A16C

nonmatching func_8000A1A0, 0x1EC

glabel func_8000A1A0
    jr $ra
    nop
  .L8000A1B8:
    jr $ra
    nop
  .L8000A1CC:
    jr $ra
    nop
  .L8000A22C:
    jr $ra
    nop
  .L8000A244:
    jr $ra
    nop
  .L8000A250:
    jr $ra
    nop
  .L8000A258:
    jr $ra
    nop
  .L8000A280:
    jr $ra
    nop
  .L8000A2A4:
    jr $ra
    nop
  .L8000A2C4:
    jr $ra
    nop
  .L8000A2FC:
    jr $ra
    nop
  .L8000A32C:
    jr $ra
    nop
  .L8000A330:
    jr $ra
    nop
  .L8000A374:
    jr $ra
    nop
  .L8000A380:
    jr $ra
    nop
endlabel func_8000A1A0

nonmatching func_8000A38C, 0x1F0

glabel func_8000A38C
    jr $ra
    nop
  .L8000A3A4:
    jr $ra
    nop
  .L8000A3B8:
    jr $ra
    nop
  .L8000A41C:
    jr $ra
    nop
  .L8000A434:
    jr $ra
    nop
  .L8000A440:
    jr $ra
    nop
  .L8000A448:
    jr $ra
    nop
  .L8000A46C:
    jr $ra
    nop
  .L8000A490:
    jr $ra
    nop
  .L8000A4B0:
    jr $ra
    nop
  .L8000A4E8:
    jr $ra
    nop
  .L8000A51C:
    jr $ra
    nop
  .L8000A520:
    jr $ra
    nop
  .L8000A564:
    jr $ra
    nop
  .L8000A570:
    jr $ra
    nop
endlabel func_8000A38C

nonmatching func_8000A57C, 0x88

glabel func_8000A57C
    jr $ra
    nop
  .L8000A5B4:
    jr $ra
    nop
  .L8000A5C8:
    jr $ra
    nop
  .L8000A5E4:
    jr $ra
    nop
  .L8000A5F0:
    jr $ra
    nop
endlabel func_8000A57C

nonmatching func_8000A604, 0x124

glabel func_8000A604
    jr $ra
    nop
  .L8000A628:
    jr $ra
    nop
  .L8000A654:
    jr $ra
    nop
  .L8000A69C:
    jr $ra
    nop
  .L8000A708:
    jr $ra
    nop
  .L8000A718:
    jr $ra
    nop
endlabel func_8000A604

nonmatching func_8000A728, 0x128

glabel func_8000A728
    jr $ra
    nop
  .L8000A74C:
    jr $ra
    nop
  .L8000A778:
    jr $ra
    nop
  .L8000A7C4:
    jr $ra
    nop
  .L8000A830:
    jr $ra
    nop
  .L8000A840:
    jr $ra
    nop
endlabel func_8000A728

nonmatching func_8000A850, 0x48

glabel func_8000A850
    jr $ra
    nop
  .L8000A878:
    jr $ra
    nop
  .L8000A884:
    jr $ra
    nop
endlabel func_8000A850

nonmatching func_8000A898, 0x40

glabel func_8000A898
    jr $ra
    nop
endlabel func_8000A898

nonmatching func_8000A8D8, 0x9C

glabel func_8000A8D8
    jr $ra
    nop
  .L8000A950:
    jr $ra
    nop
  .L8000A95C:
    jr $ra
    nop
  .L8000A968:
    jr $ra
    nop
endlabel func_8000A8D8

nonmatching func_8000A974, 0x58

glabel func_8000A974
    jr $ra
    nop
  .L8000A9C4:
    jr $ra
    nop
endlabel func_8000A974

nonmatching func_8000A9CC, 0x44

glabel func_8000A9CC
    jr $ra
    nop
  .L8000A9E8:
    jr $ra
    nop
  .L8000AA04:
    jr $ra
    nop
endlabel func_8000A9CC

nonmatching func_8000AA10, 0x120

glabel func_8000AA10
    jr $ra
    nop
  .L8000AAA0:
    jr $ra
    nop
  .L8000AAAC:
    jr $ra
    nop
  .L8000AAB8:
    jr $ra
    nop
  .L8000AB1C:
    jr $ra
    nop
  .L8000AB28:
    jr $ra
    nop
endlabel func_8000AA10

nonmatching func_8000AB30, 0x128

glabel func_8000AB30
    jr $ra
    nop
  .L8000ABC0:
    jr $ra
    nop
  .L8000ABCC:
    jr $ra
    nop
  .L8000ABD8:
    jr $ra
    nop
  .L8000AC44:
    jr $ra
    nop
  .L8000AC50:
    jr $ra
    nop
endlabel func_8000AB30

nonmatching func_8000AC58, 0x40

glabel func_8000AC58
    jr $ra
    nop
endlabel func_8000AC58

nonmatching func_8000AC98, 0x48

glabel func_8000AC98
    jr $ra
    nop
endlabel func_8000AC98

nonmatching func_8000ACE0, 0x2C

glabel func_8000ACE0
    jr $ra
    nop
endlabel func_8000ACE0

nonmatching func_8000AD0C, 0x30

glabel func_8000AD0C
    jr $ra
    nop
endlabel func_8000AD0C

nonmatching func_8000AD3C, 0x34

glabel func_8000AD3C
    jr $ra
    nop
endlabel func_8000AD3C

nonmatching func_8000AD70, 0x3C

glabel func_8000AD70
    jr $ra
    nop
endlabel func_8000AD70

nonmatching func_8000ADAC, 0x5C

glabel func_8000ADAC
    jr $ra
    nop
endlabel func_8000ADAC

nonmatching func_8000AE08, 0x8

glabel func_8000AE08
    jr $ra
    nop
endlabel func_8000AE08

nonmatching func_8000AE10, 0x84

glabel func_8000AE10
    jr $ra
    nop
  .L8000AE24:
    jr $ra
    nop
  .L8000AE3C:
    jr $ra
    nop
  .L8000AE54:
    jr $ra
    nop
  .L8000AE6C:
    jr $ra
    nop
  .L8000AE88:
    jr $ra
    nop
endlabel func_8000AE10

nonmatching func_8000AE94, 0x9C

glabel func_8000AE94
    jr $ra
    nop
  .L8000AEEC:
    jr $ra
    nop
endlabel func_8000AE94

nonmatching func_8000AF30, 0x34

glabel func_8000AF30
    jr $ra
    nop
endlabel func_8000AF30

nonmatching func_8000AF64, 0x48

glabel func_8000AF64
    jr $ra
    nop
  .L8000AF98:
    jr $ra
    nop
  .L8000AFA0:
    jr $ra
    nop
endlabel func_8000AF64

nonmatching func_8000AFAC, 0x48

glabel func_8000AFAC
    jr $ra
    nop
  .L8000AFE0:
    jr $ra
    nop
  .L8000AFE8:
    jr $ra
    nop
endlabel func_8000AFAC

nonmatching func_8000AFF4, 0x2C

glabel func_8000AFF4
    jr $ra
    nop
endlabel func_8000AFF4

nonmatching func_8000B020, 0x28

glabel func_8000B020
    jr $ra
    nop
endlabel func_8000B020

nonmatching func_8000B048, 0x28

glabel func_8000B048
    jr $ra
    nop
endlabel func_8000B048

nonmatching func_8000B070, 0x28

glabel func_8000B070
    jr $ra
    nop
endlabel func_8000B070

nonmatching func_8000B098, 0x28

glabel func_8000B098
    jr $ra
    nop
endlabel func_8000B098

nonmatching func_8000B0C0, 0x28

glabel func_8000B0C0
    jr $ra
    nop
endlabel func_8000B0C0

nonmatching func_8000B0E8, 0x28

glabel func_8000B0E8
    jr $ra
    nop
endlabel func_8000B0E8

nonmatching func_8000B110, 0x24

glabel func_8000B110
    jr $ra
    nop
endlabel func_8000B110

nonmatching func_8000B134, 0x28

glabel func_8000B134
    jr $ra
    nop
endlabel func_8000B134

nonmatching func_8000B15C, 0x24

glabel func_8000B15C
    jr $ra
    nop
endlabel func_8000B15C

nonmatching func_8000B180, 0x28

glabel func_8000B180
    jr $ra
    nop
endlabel func_8000B180

nonmatching func_8000B1A8, 0x24

glabel func_8000B1A8
    jr $ra
    nop
endlabel func_8000B1A8

nonmatching func_8000B1CC, 0x28

glabel func_8000B1CC
    jr $ra
    nop
endlabel func_8000B1CC

nonmatching func_8000B1F4, 0x24

glabel func_8000B1F4
    jr $ra
    nop
endlabel func_8000B1F4

nonmatching func_8000B218, 0x28

glabel func_8000B218
    jr $ra
    nop
endlabel func_8000B218

nonmatching func_8000B240, 0x3C

glabel func_8000B240
    jr $ra
    nop
  .L8000B268:
    jr $ra
    nop
endlabel func_8000B240

nonmatching func_8000B27C, 0x3C

glabel func_8000B27C
    jr $ra
    nop
  .L8000B2A4:
    jr $ra
    nop
endlabel func_8000B27C

nonmatching func_8000B2B8, 0x3C

glabel func_8000B2B8
    jr $ra
    nop
  .L8000B2E0:
    jr $ra
    nop
endlabel func_8000B2B8

nonmatching func_8000B2F4, 0x3C

glabel func_8000B2F4
    jr $ra
    nop
endlabel func_8000B2F4

nonmatching func_8000B330, 0x3C

glabel func_8000B330
    jr $ra
    nop
endlabel func_8000B330

nonmatching func_8000B36C, 0x58

glabel func_8000B36C
    jr $ra
    nop
  .L8000B3B0:
    jr $ra
    nop
  .L8000B3B8:
    jr $ra
    nop
endlabel func_8000B36C

nonmatching func_8000B3C4, 0x58

glabel func_8000B3C4
    jr $ra
    nop
  .L8000B408:
    jr $ra
    nop
  .L8000B410:
    jr $ra
    nop
endlabel func_8000B3C4

nonmatching func_8000B41C, 0x40

glabel func_8000B41C
    jr $ra
    nop
endlabel func_8000B41C

nonmatching func_8000B45C, 0x40

glabel func_8000B45C
    jr $ra
    nop
endlabel func_8000B45C

nonmatching func_8000B49C, 0x60

glabel func_8000B49C
    jr $ra
    nop
  .L8000B4E8:
    jr $ra
    nop
  .L8000B4F0:
    jr $ra
    nop
endlabel func_8000B49C

nonmatching func_8000B4FC, 0x60

glabel func_8000B4FC
    jr $ra
    nop
  .L8000B548:
    jr $ra
    nop
  .L8000B550:
    jr $ra
    nop
endlabel func_8000B4FC

nonmatching func_8000B55C, 0x44

glabel func_8000B55C
    jr $ra
    nop
endlabel func_8000B55C

nonmatching func_8000B5A0, 0x90

glabel func_8000B5A0
    jr $ra
    nop
endlabel func_8000B5A0

nonmatching func_8000B630, 0x2D0

glabel func_8000B630
    jr $ra
    nop
  .L8000B664:
    jr $ra
    nop
  .L8000B680:
    jr $ra
    nop
  .L8000B684:
    jr $ra
    nop
  .L8000B6D8:
    jr $ra
    nop
  .L8000B7EC:
    jr $ra
    nop
  .L8000B868:
    jr $ra
    nop
  .L8000B874:
    jr $ra
    nop
  .L8000B880:
    jr $ra
    nop
  .L8000B898:
    jr $ra
    nop
  .L8000B8D0:
    jr $ra
    nop
  .L8000B8D8:
    jr $ra
    nop
  .L8000B8EC:
    jr $ra
    nop
endlabel func_8000B630

nonmatching func_8000B900, 0x40

glabel func_8000B900
    jr $ra
    nop
  .L8000B930:
    jr $ra
    nop
endlabel func_8000B900

nonmatching func_8000B940, 0xB8

glabel func_8000B940
    jr $ra
    nop
  .L8000B97C:
    jr $ra
    nop
  .L8000B9C4:
    jr $ra
    nop
  .L8000B9C8:
    jr $ra
    nop
  .L8000B9DC:
    jr $ra
    nop
endlabel func_8000B940

nonmatching func_8000B9F8, 0x5A0

glabel func_8000B9F8
    jr $ra
    nop
  .L8000BA74:
    jr $ra
    nop
  .L8000BA9C:
    jr $ra
    nop
  .L8000BAC4:
    jr $ra
    nop
  .L8000BAF0:
    jr $ra
    nop
  .L8000BB50:
    jr $ra
    nop
  .L8000BB6C:
    jr $ra
    nop
  .L8000BBA4:
    jr $ra
    nop
  .L8000BBBC:
    jr $ra
    nop
  .L8000BBF8:
    jr $ra
    nop
  .L8000BC1C:
    jr $ra
    nop
  .L8000BC40:
    jr $ra
    nop
  .L8000BC78:
    jr $ra
    nop
  .L8000BCB0:
    jr $ra
    nop
  .L8000BCEC:
    jr $ra
    nop
  .L8000BD24:
    jr $ra
    nop
  .L8000BD68:
    jr $ra
    nop
  .L8000BD80:
    jr $ra
    nop
  .L8000BD9C:
    jr $ra
    nop
  .L8000BDB8:
    jr $ra
    nop
  .L8000BDD0:
    jr $ra
    nop
  .L8000BDF0:
    jr $ra
    nop
  .L8000BE08:
    jr $ra
    nop
  .L8000BE34:
    jr $ra
    nop
  .L8000BE5C:
    jr $ra
    nop
  .L8000BE7C:
    jr $ra
    nop
  .L8000BE8C:
    jr $ra
    nop
  .L8000BEB4:
    jr $ra
    nop
  .L8000BED0:
    jr $ra
    nop
  .L8000BEEC:
    jr $ra
    nop
  .L8000BF14:
    jr $ra
    nop
  .L8000BF3C:
    jr $ra
    nop
  .L8000BF5C:
    jr $ra
    nop
endlabel func_8000B9F8

nonmatching func_8000BF98, 0x6C0

glabel func_8000BF98
    jr $ra
    nop
  .L8000C014:
    jr $ra
    nop
  .L8000C03C:
    jr $ra
    nop
  .L8000C064:
    jr $ra
    nop
  .L8000C090:
    jr $ra
    nop
  .L8000C100:
    jr $ra
    nop
  .L8000C118:
    jr $ra
    nop
  .L8000C130:
    jr $ra
    nop
  .L8000C140:
    jr $ra
    nop
  .L8000C14C:
    jr $ra
    nop
  .L8000C18C:
    jr $ra
    nop
  .L8000C1A4:
    jr $ra
    nop
  .L8000C1E4:
    jr $ra
    nop
  .L8000C208:
    jr $ra
    nop
  .L8000C234:
    jr $ra
    nop
  .L8000C250:
    jr $ra
    nop
  .L8000C270:
    jr $ra
    nop
  .L8000C280:
    jr $ra
    nop
  .L8000C2AC:
    jr $ra
    nop
  .L8000C2F8:
    jr $ra
    nop
  .L8000C334:
    jr $ra
    nop
  .L8000C36C:
    jr $ra
    nop
  .L8000C398:
    jr $ra
    nop
  .L8000C3C0:
    jr $ra
    nop
  .L8000C3CC:
    jr $ra
    nop
  .L8000C3E4:
    jr $ra
    nop
  .L8000C3F4:
    jr $ra
    nop
  .L8000C400:
    jr $ra
    nop
  .L8000C424:
    jr $ra
    nop
  .L8000C43C:
    jr $ra
    nop
  .L8000C460:
    jr $ra
    nop
  .L8000C478:
    jr $ra
    nop
  .L8000C4B4:
    jr $ra
    nop
  .L8000C4C0:
    jr $ra
    nop
  .L8000C4E8:
    jr $ra
    nop
  .L8000C508:
    jr $ra
    nop
  .L8000C518:
    jr $ra
    nop
  .L8000C550:
    jr $ra
    nop
  .L8000C55C:
    jr $ra
    nop
  .L8000C578:
    jr $ra
    nop
  .L8000C594:
    jr $ra
    nop
  .L8000C5CC:
    jr $ra
    nop
  .L8000C5D8:
    jr $ra
    nop
  .L8000C600:
    jr $ra
    nop
  .L8000C620:
    jr $ra
    nop
endlabel func_8000BF98

nonmatching func_8000C658, 0x18

glabel func_8000C658
    jr $ra
    nop
endlabel func_8000C658
