.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80000460, 0xDC

glabel func_80000460
    jr $ra
    nop
  .L800004C0:
    jr $ra
    nop
  .L800004C8:
    jr $ra
    nop
  .L800004CC:
    jr $ra
    nop
endlabel func_80000460

nonmatching func_8000053C, 0x3C

glabel func_8000053C
    jr $ra
    nop
  .L80000568:
    jr $ra
    nop
endlabel func_8000053C

nonmatching func_80000578, 0x104

glabel func_80000578
    jr $ra
    nop
  .L800005D4:
    jr $ra
    nop
  .L800005DC:
    jr $ra
    nop
  .L80000604:
    jr $ra
    nop
  .L80000644:
    jr $ra
    nop
  .L80000658:
    jr $ra
    nop
  .L80000668:
    jr $ra
    nop
  .L8000066C:
    jr $ra
    nop
endlabel func_80000578

nonmatching func_8000067C, 0xF4

glabel func_8000067C
    jr $ra
    nop
  .L800006B0:
    jr $ra
    nop
  .L800006B4:
    jr $ra
    nop
  .L80000748:
    jr $ra
    nop
  .L80000754:
    jr $ra
    nop
endlabel func_8000067C
