.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80000770, 0x40

glabel func_80000770
    jr $ra
    nop
endlabel func_80000770

nonmatching func_800007B0, 0xB4

glabel func_800007B0
    jr $ra
    nop
  alabel func_80000800
    jr $ra
    nop
endlabel func_800007B0

nonmatching func_80000864, 0x1CC

glabel func_80000864
    jr $ra
    nop
  .L800008D0:
    jr $ra
    nop
  .L800008EC:
    jr $ra
    nop
  .L800008F0:
    jr $ra
    nop
  .L800008F8:
    jr $ra
    nop
  .L80000908:
    jr $ra
    nop
  .L8000095C:
    jr $ra
    nop
  .L800009B4:
    jr $ra
    nop
  .L800009FC:
    jr $ra
    nop
  .L80000A24:
    jr $ra
    nop
endlabel func_80000864

nonmatching func_80000A30, 0x68

glabel func_80000A30
    jr $ra
    nop
  .L80000A80:
    jr $ra
    nop
  .L80000A8C:
    jr $ra
    nop
endlabel func_80000A30

nonmatching func_80000A98, 0x138

glabel func_80000A98
    jr $ra
    nop
  .L80000AFC:
    jr $ra
    nop
  .L80000B00:
    jr $ra
    nop
  .L80000B6C:
    jr $ra
    nop
  .L80000B78:
    jr $ra
    nop
endlabel func_80000A98

nonmatching func_80000BD0, 0x35C

glabel func_80000BD0
    jr $ra
    nop
  alabel func_80000C00
    jr $ra
    nop
  .L80000CDC:
    jr $ra
    nop
  .L80000D24:
    jr $ra
    nop
  .L80000D2C:
    jr $ra
    nop
  .L80000D64:
    jr $ra
    nop
  .L80000D74:
    jr $ra
    nop
  .L80000DC4:
    jr $ra
    nop
  .L80000DCC:
    jr $ra
    nop
  .L80000DFC:
    jr $ra
    nop
  .L80000E40:
    jr $ra
    nop
  .L80000E50:
    jr $ra
    nop
  .L80000E60:
    jr $ra
    nop
  .L80000EB0:
    jr $ra
    nop
  .L80000EB8:
    jr $ra
    nop
  .L80000EEC:
    jr $ra
    nop
  .L80000F1C:
    jr $ra
    nop
endlabel func_80000BD0
    /* 1B2C 80000F2C 00000000 */  nop

nonmatching func_80000F30, 0x160

glabel func_80000F30
    jr $ra
    nop
  .L80000F54:
    jr $ra
    nop
  .L80000F68:
    jr $ra
    nop
  .L80000F8C:
    jr $ra
    nop
  .L80000FB8:
    jr $ra
    nop
  .L80000FCC:
    jr $ra
    nop
  .L80000FE8:
    jr $ra
    nop
  .L80001008:
    jr $ra
    nop
  .L8000101C:
    jr $ra
    nop
  .L80001038:
    jr $ra
    nop
  .L80001058:
    jr $ra
    nop
  .L8000106C:
    jr $ra
    nop
  alabel .L80001088
    jr $ra
    nop
endlabel func_80000F30

nonmatching func_80001090, 0x358

glabel func_80001090
    jr $ra
    nop
  .L800010C4:
    jr $ra
    nop
  .L800010E4:
    jr $ra
    nop
  .L8000111C:
    jr $ra
    nop
  .L80001168:
    jr $ra
    nop
  .L80001188:
    jr $ra
    nop
  .L800011B8:
    jr $ra
    nop
  .L800011BC:
    jr $ra
    nop
  .L800011DC:
    jr $ra
    nop
  .L800011FC:
    jr $ra
    nop
  alabel func_8000121C
    jr $ra
    nop
  .L8000122C:
    jr $ra
    nop
  .L80001230:
    jr $ra
    nop
  .L80001250:
    jr $ra
    nop
  .L80001270:
    jr $ra
    nop
  .L800012A8:
    jr $ra
    nop
  .L800012E4:
    jr $ra
    nop
  .L80001308:
    jr $ra
    nop
  .L80001328:
    jr $ra
    nop
  .L80001358:
    jr $ra
    nop
  .L8000135C:
    jr $ra
    nop
  .L80001370:
    jr $ra
    nop
  .L80001390:
    jr $ra
    nop
  .L800013B0:
    jr $ra
    nop
  .L800013E0:
    jr $ra
    nop
endlabel func_80001090

nonmatching func_800013E8, 0x50

glabel func_800013E8
    jr $ra
    nop
endlabel func_800013E8

nonmatching func_80001438, 0x1C

glabel func_80001438
    jr $ra
    nop
endlabel func_80001438

nonmatching func_80001454, 0x60

glabel func_80001454
    jr $ra
    nop
  .L80001478:
    jr $ra
    nop
  .L80001494:
    jr $ra
    nop
endlabel func_80001454

nonmatching func_800014B4, 0x48

glabel func_800014B4
    jr $ra
    nop
endlabel func_800014B4

nonmatching func_800014FC, 0xC

glabel func_800014FC
    jr $ra
    nop
endlabel func_800014FC

nonmatching func_80001508, 0xC

glabel func_80001508
    jr $ra
    nop
endlabel func_80001508

nonmatching func_80001514, 0x128

glabel func_80001514
    jr $ra
    nop
  .L80001570:
    jr $ra
    nop
  .L80001580:
    jr $ra
    nop
  .L8000158C:
    jr $ra
    nop
  .L800015D0:
    jr $ra
    nop
  .L800015D4:
    jr $ra
    nop
  .L800015F8:
    jr $ra
    nop
  .L80001604:
    jr $ra
    nop
  .L80001608:
    jr $ra
    nop
  .L80001618:
    jr $ra
    nop
  .L8000161C:
    jr $ra
    nop
endlabel func_80001514

nonmatching func_8000163C, 0x44

glabel func_8000163C
    jr $ra
    nop
endlabel func_8000163C
