.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_801533C0, 0x4

glabel func_801533C0
    jr $ra
    nop
endlabel func_801533C0

nonmatching D_801533C4, 0xC

glabel D_801533C4
    jr $ra
    nop
endlabel D_801533C4

nonmatching D_801533D0, 0x140

glabel D_801533D0
    jr $ra
    nop
  .L801534A4:
    jr $ra
    nop
  .L801534C8:
    jr $ra
    nop
  .L801534CC:
    jr $ra
    nop
  .L801534E4:
    jr $ra
    nop
  .L801534F8:
    jr $ra
    nop
  .L801534FC:
    jr $ra
    nop
endlabel D_801533D0
