.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_801404E0, 0x170

glabel func_801404E0
# PATCHED: # PATCHED: /* C35D0 801404E0 5440FFD4 */  bnel       $v0, $zero, D_80140434
    nop
    nop
    /* C35D4 801404E4 862F0010 */   lh        $t7, 0x10($s1)
  alabel D_801404E8
    /* C35D8 801404E8 8FBF002C */  lw         $ra, 0x2C($sp)
    /* C35DC 801404EC 8FB00018 */  lw         $s0, 0x18($sp)
    /* C35E0 801404F0 8FB1001C */  lw         $s1, 0x1C($sp)
    /* C35E4 801404F4 8FB20020 */  lw         $s2, 0x20($sp)
    /* C35E8 801404F8 8FB30024 */  lw         $s3, 0x24($sp)
    /* C35EC 801404FC 8FB40028 */  lw         $s4, 0x28($sp)
    /* C35F0 80140500 03E00008 */  jr         $ra
    /* C35F4 80140504 27BD0030 */   addiu     $sp, $sp, 0x30
    /* C35F8 80140508 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* C35FC 8014050C AFBF0014 */  sw         $ra, 0x14($sp)
    /* C3600 80140510 8C830070 */  lw         $v1, 0x70($a0)
    /* C3604 80140514 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* C3608 80140518 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* C360C 8014051C 946E0002 */  lhu        $t6, 0x2($v1)
    /* C3610 80140520 3C02801A */  lui        $v0, %hi(D_8019D150)
    /* C3614 80140524 2442D150 */  addiu      $v0, $v0, %lo(D_8019D150)
    /* C3618 80140528 01C1C024 */  and        $t8, $t6, $at
    /* C361C 8014052C 3319BFFF */  andi       $t9, $t8, 0xBFFF
    /* C3620 80140530 A4780002 */  sh         $t8, 0x2($v1)
    /* C3624 80140534 A4790002 */  sh         $t9, 0x2($v1)
    /* C3628 80140538 8C480004 */  lw         $t0, 0x4($v0)
    /* C362C 8014053C 00802825 */  or         $a1, $a0, $zero
    /* C3630 80140540 2509FFFF */  addiu      $t1, $t0, -0x1
    /* C3634 80140544 AC490004 */  sw         $t1, 0x4($v0)
    /* C3638 80140548 8C84006C */  lw         $a0, 0x6C($a0)
    /* C363C 8014054C AFA50020 */  sw         $a1, 0x20($sp)
    /* C3640 80140550 0C050BA4 */  jal        func_80142E90
    /* C3644 80140554 AFA3001C */   sw        $v1, 0x1C($sp)
    /* C3648 80140558 8FA3001C */  lw         $v1, 0x1C($sp)
# PATCHED: # PATCHED: /* C364C 8014055C 10400004 */  beqz       $v0, D_80140570
    nop
    nop
    /* C3650 80140560 8FA50020 */   lw        $a1, 0x20($sp)
    /* C3654 80140564 946A0002 */  lhu        $t2, 0x2($v1)
    /* C3658 80140568 354B1000 */  ori        $t3, $t2, 0x1000
    /* C365C 8014056C A46B0002 */  sh         $t3, 0x2($v1)
  alabel D_80140570
    /* C3660 80140570 946C0002 */  lhu        $t4, 0x2($v1)
    /* C3664 80140574 00A02025 */  or         $a0, $a1, $zero
    /* C3668 80140578 318DDFFF */  andi       $t5, $t4, 0xDFFF
    /* C366C 8014057C 0C000B38 */  jal        func_80002CE0
    /* C3670 80140580 A46D0002 */   sh        $t5, 0x2($v1)
    /* C3674 80140584 8FBF0014 */  lw         $ra, 0x14($sp)
    /* C3678 80140588 27BD0020 */  addiu      $sp, $sp, 0x20
    /* C367C 8014058C 03E00008 */  jr         $ra
    /* C3680 80140590 00000000 */   nop
    /* C3684 80140594 03E00008 */  jr         $ra
    /* C3688 80140598 8C82003C */   lw        $v0, 0x3C($a0)
    /* C368C 8014059C 3C04801A */  lui        $a0, %hi(D_8019D174)
    /* C3690 801405A0 8C84D174 */  lw         $a0, %lo(D_8019D174)($a0)
    /* C3694 801405A4 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* C3698 801405A8 AFBF0014 */  sw         $ra, 0x14($sp)
# PATCHED: # PATCHED: /* C369C 801405AC 50800009 */  beql       $a0, $zero, D_801405D4
    nop
    nop
    /* C36A0 801405B0 2402FFFF */   addiu     $v0, $zero, -0x1
    /* C36A4 801405B4 0C050BA4 */  jal        func_80142E90
    /* C36A8 801405B8 AFA4001C */   sw        $a0, 0x1C($sp)
    /* C36AC 801405BC 10400004 */  beqz       $v0, .L801405D0
    /* C36B0 801405C0 8FA4001C */   lw        $a0, 0x1C($sp)
    /* C36B4 801405C4 8C830070 */  lw         $v1, 0x70($a0)
# PATCHED: # PATCHED: /* C36B8 801405C8 10000002 */  b          D_801405D4
    nop
    nop
    /* C36BC 801405CC 94620014 */   lhu       $v0, 0x14($v1)
  .L801405D0:
    /* C36C0 801405D0 2402FFFF */  addiu      $v0, $zero, -0x1
  alabel D_801405D4
    /* C36C4 801405D4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* C36C8 801405D8 27BD0020 */  addiu      $sp, $sp, 0x20
    /* C36CC 801405DC 03E00008 */  jr         $ra
    /* C36D0 801405E0 00000000 */   nop
    /* C36D4 801405E4 3C04801A */  lui        $a0, %hi(D_8019D174)
    /* C36D8 801405E8 8C84D174 */  lw         $a0, %lo(D_8019D174)($a0)
    /* C36DC 801405EC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* C36E0 801405F0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* C36E4 801405F4 50800008 */  beql       $a0, $zero, .L80140618
    /* C36E8 801405F8 00001025 */   or        $v0, $zero, $zero
    /* C36EC 801405FC 0C050BA4 */  jal        func_80142E90
    /* C36F0 80140600 AFA4001C */   sw        $a0, 0x1C($sp)
    /* C36F4 80140604 10400003 */  beqz       $v0, .L80140614
    /* C36F8 80140608 8FA4001C */   lw        $a0, 0x1C($sp)
    /* C36FC 8014060C 10000002 */  b          .L80140618
    /* C3700 80140610 00801025 */   or        $v0, $a0, $zero
  .L80140614:
    /* C3704 80140614 00001025 */  or         $v0, $zero, $zero
  .L80140618:
    /* C3708 80140618 8FBF0014 */  lw         $ra, 0x14($sp)
    /* C370C 8014061C 27BD0020 */  addiu      $sp, $sp, 0x20
    /* C3710 80140620 03E00008 */  jr         $ra
    /* C3714 80140624 00000000 */   nop
    /* C3718 80140628 908E0038 */  lbu        $t6, 0x38($a0)
    /* C371C 8014062C 00001025 */  or         $v0, $zero, $zero
    /* C3720 80140630 35CF0001 */  ori        $t7, $t6, 0x1
    /* C3724 80140634 03E00008 */  jr         $ra
    /* C3728 80140638 A08F0038 */   sb        $t7, 0x38($a0)
    /* C372C 8014063C 908E0038 */  lbu        $t6, 0x38($a0)
    /* C3730 80140640 00001025 */  or         $v0, $zero, $zero
    /* C3734 80140644 31CFFFFE */  andi       $t7, $t6, 0xFFFE
    /* C3738 80140648 03E00008 */  jr         $ra
    /* C373C 8014064C A08F0038 */   sb        $t7, 0x38($a0)
endlabel func_801404E0
