.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80164720, 0x2C

glabel func_80164720
    jr $ra
    nop
  .L8016472C:
    jr $ra
    nop
  .L80164740:
    jr $ra
    nop
endlabel func_80164720

nonmatching D_8016474C, 0xC

glabel D_8016474C
    jr $ra
    nop
endlabel D_8016474C

nonmatching func_80164758, 0xE0

glabel func_80164758
    jr $ra
    nop
  .L8016479C:
    jr $ra
    nop
  .L801647C0:
    jr $ra
    nop
  .L80164804:
    jr $ra
    nop
  .L8016480C:
    jr $ra
    nop
  .L80164810:
    jr $ra
    nop
  .L8016481C:
    jr $ra
    nop
endlabel func_80164758

nonmatching func_80164838, 0x14

glabel func_80164838
    jr $ra
    nop
endlabel func_80164838

nonmatching D_8016484C, 0x34

glabel D_8016484C
    jr $ra
    nop
  .L80164870:
    jr $ra
    nop
endlabel D_8016484C
