.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80163D50, 0x4

glabel func_80163D50
    jr $ra
    nop
endlabel func_80163D50

nonmatching D_80163D54, 0x108

glabel D_80163D54
    jr $ra
    nop
  .L80163E08:
    jr $ra
    nop
endlabel D_80163D54

nonmatching D_80163E5C, 0x10

glabel D_80163E5C
    jr $ra
    nop
endlabel D_80163E5C

nonmatching func_80163E6C, 0xF0

glabel func_80163E6C
    jr $ra
    nop
  .L80163EEC:
    jr $ra
    nop
  .L80163EF0:
    jr $ra
    nop
  .L80163F4C:
    jr $ra
    nop
endlabel func_80163E6C

nonmatching func_80163F5C, 0x1EC

glabel func_80163F5C
    jr $ra
    nop
  .L80163FEC:
    jr $ra
    nop
  .L8016407C:
    jr $ra
    nop
  .L80164098:
    jr $ra
    nop
  .L8016409C:
    jr $ra
    nop
  .L801640B4:
    jr $ra
    nop
  .L80164138:
    jr $ra
    nop
endlabel func_80163F5C

nonmatching func_80164148, 0x50

glabel func_80164148
    jr $ra
    nop
  .L80164170:
    jr $ra
    nop
  .L80164188:
    jr $ra
    nop
endlabel func_80164148

nonmatching func_80164198, 0x38

glabel func_80164198
    jr $ra
    nop
endlabel func_80164198
