.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8015A680, 0x14

glabel func_8015A680
    jr $ra
    nop
endlabel func_8015A680

nonmatching func_8015A694, 0x24

glabel func_8015A694
    jr $ra
    nop
endlabel func_8015A694

nonmatching D_8015A6B8, 0x60

glabel D_8015A6B8
    jr $ra
    nop
endlabel D_8015A6B8

nonmatching D_8015A718, 0x8C

glabel D_8015A718
    jr $ra
    nop
  .L8015A728:
    jr $ra
    nop
endlabel D_8015A718

nonmatching func_8015A7A4, 0x148

glabel func_8015A7A4
    jr $ra
    nop
  alabel D_8015A7C4
    jr $ra
    nop
  .L8015A83C:
    jr $ra
    nop
  .L8015A848:
    jr $ra
    nop
  .L8015A850:
    jr $ra
    nop
  .L8015A884:
    jr $ra
    nop
  .L8015A8D8:
    jr $ra
    nop
endlabel func_8015A7A4

nonmatching func_8015A8EC, 0x1D4

glabel func_8015A8EC
    jr $ra
    nop
  .L8015A944:
    jr $ra
    nop
  .L8015A960:
    jr $ra
    nop
  .L8015A9B4:
    jr $ra
    nop
  .L8015A9F0:
    jr $ra
    nop
  .L8015A9F4:
    jr $ra
    nop
  .L8015AA10:
    jr $ra
    nop
  .L8015AA34:
    jr $ra
    nop
  .L8015AA50:
    jr $ra
    nop
  .L8015AA90:
    jr $ra
    nop
  .L8015AA94:
    jr $ra
    nop
endlabel func_8015A8EC

nonmatching func_8015AAC0, 0xD0

glabel func_8015AAC0
    jr $ra
    nop
  .L8015AAE0:
    jr $ra
    nop
  .L8015AB04:
    jr $ra
    nop
  .L8015AB08:
    jr $ra
    nop
  .L8015AB28:
    jr $ra
    nop
  .L8015AB5C:
    jr $ra
    nop
  .L8015AB80:
    jr $ra
    nop
  .L8015AB84:
    jr $ra
    nop
endlabel func_8015AAC0

nonmatching func_8015AB90, 0x24

glabel func_8015AB90
    jr $ra
    nop
endlabel func_8015AB90

nonmatching func_8015ABB4, 0x98

glabel func_8015ABB4
    jr $ra
    nop
  .L8015ABE4:
    jr $ra
    nop
  .L8015AC04:
    jr $ra
    nop
  .L8015AC28:
    jr $ra
    nop
  .L8015AC44:
    jr $ra
    nop
endlabel func_8015ABB4

nonmatching func_8015AC4C, 0x3C

glabel func_8015AC4C
    jr $ra
    nop
  .L8015AC6C:
    jr $ra
    nop
endlabel func_8015AC4C

nonmatching func_8015AC88, 0x3C

glabel func_8015AC88
    jr $ra
    nop
endlabel func_8015AC88
    /* DDDB4 8015ACC4 00000000 */  nop
    /* DDDB8 8015ACC8 00000000 */  nop
    /* DDDBC 8015ACCC 00000000 */  nop

nonmatching func_8015ACD0, 0x70

glabel func_8015ACD0
    jr $ra
    nop
endlabel func_8015ACD0

nonmatching func_8015AD40, 0x10

glabel func_8015AD40
    jr $ra
    nop
endlabel func_8015AD40
