.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8015A680, 0x14

glabel func_8015A680
    /* DD770 8015A680 000FC040 */  sll        $t8, $t7, 1
    /* DD774 8015A684 00981021 */  addu       $v0, $a0, $t8
    /* DD778 8015A688 904A0009 */  lbu        $t2, 0x9($v0)
    /* DD77C 8015A68C 90480008 */  lbu        $t0, 0x8($v0)
    /* DD780 8015A690 24420008 */  addiu      $v0, $v0, 0x8
endlabel func_8015A680

nonmatching func_8015A694, 0x24

glabel func_8015A694
    /* DD784 8015A694 000A5880 */  sll        $t3, $t2, 2
    /* DD788 8015A698 25090001 */  addiu      $t1, $t0, 0x1
    /* DD78C 8015A69C A0490000 */  sb         $t1, 0x0($v0)
    /* DD790 8015A6A0 032BC821 */  addu       $t9, $t9, $t3
    /* DD794 8015A6A4 8F390E4C */  lw         $t9, 0xE4C($t9)
    /* DD798 8015A6A8 0320F809 */  jalr       $t9
    /* DD79C 8015A6AC 00000000 */   nop
    /* DD7A0 8015A6B0 1000001D */  b          .L8015A728
    /* DD7A4 8015A6B4 8FBF0014 */   lw        $ra, 0x14($sp)
endlabel func_8015A694

nonmatching D_8015A6B8, 0x60

glabel D_8015A6B8
    /* DD7A8 8015A6B8 3C198000 */  lui        $t9, %hi(func_80001E30)
    /* DD7AC 8015A6BC 27391E30 */  addiu      $t9, $t9, %lo(func_80001E30)
    /* DD7B0 8015A6C0 24E5000E */  addiu      $a1, $a3, 0xE
    /* DD7B4 8015A6C4 24060002 */  addiu      $a2, $zero, 0x2
    /* DD7B8 8015A6C8 0320F809 */  jalr       $t9
    /* DD7BC 8015A6CC AFA70018 */   sw        $a3, 0x18($sp)
    /* DD7C0 8015A6D0 8FA40018 */  lw         $a0, 0x18($sp)
    /* DD7C4 8015A6D4 3C198019 */  lui        $t9, %hi(D_80190E4C)
    /* DD7C8 8015A6D8 848C000E */  lh         $t4, 0xE($a0)
    /* DD7CC 8015A6DC 000C6840 */  sll        $t5, $t4, 1
    /* DD7D0 8015A6E0 008D1021 */  addu       $v0, $a0, $t5
    /* DD7D4 8015A6E4 90580009 */  lbu        $t8, 0x9($v0)
    /* DD7D8 8015A6E8 904E0008 */  lbu        $t6, 0x8($v0)
    /* DD7DC 8015A6EC 24420008 */  addiu      $v0, $v0, 0x8
    /* DD7E0 8015A6F0 00184080 */  sll        $t0, $t8, 2
    /* DD7E4 8015A6F4 25CF0001 */  addiu      $t7, $t6, 0x1
    /* DD7E8 8015A6F8 A04F0000 */  sb         $t7, 0x0($v0)
    /* DD7EC 8015A6FC 0328C821 */  addu       $t9, $t9, $t0
    /* DD7F0 8015A700 8F390E4C */  lw         $t9, %lo(D_80190E4C)($t9)
    /* DD7F4 8015A704 0320F809 */  jalr       $t9
    /* DD7F8 8015A708 00000000 */   nop
    /* DD7FC 8015A70C 10000006 */  b          .L8015A728
    /* DD800 8015A710 8FBF0014 */   lw        $ra, 0x14($sp)
    /* DD804 8015A714 8CF90010 */  lw         $t9, 0x10($a3)
endlabel D_8015A6B8

nonmatching D_8015A718, 0x8C

glabel D_8015A718
    /* DD808 8015A718 00E02025 */  or         $a0, $a3, $zero
    /* DD80C 8015A71C 0320F809 */  jalr       $t9
    /* DD810 8015A720 00000000 */   nop
    /* DD814 8015A724 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8015A728:
    /* DD818 8015A728 27BD0018 */  addiu      $sp, $sp, 0x18
    /* DD81C 8015A72C 03E00008 */  jr         $ra
    /* DD820 8015A730 00000000 */   nop
    /* DD824 8015A734 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* DD828 8015A738 AFBF0014 */  sw         $ra, 0x14($sp)
    /* DD82C 8015A73C 8483000E */  lh         $v1, 0xE($a0)
    /* DD830 8015A740 24630001 */  addiu      $v1, $v1, 0x1
    /* DD834 8015A744 00031C00 */  sll        $v1, $v1, 16
    /* DD838 8015A748 00031C03 */  sra        $v1, $v1, 16
    /* DD83C 8015A74C 00037040 */  sll        $t6, $v1, 1
    /* DD840 8015A750 008E1021 */  addu       $v0, $a0, $t6
    /* DD844 8015A754 A483000E */  sh         $v1, 0xE($a0)
    /* DD848 8015A758 904F0008 */  lbu        $t7, 0x8($v0)
    /* DD84C 8015A75C 25F80001 */  addiu      $t8, $t7, 0x1
    /* DD850 8015A760 A0580008 */  sb         $t8, 0x8($v0)
    /* DD854 8015A764 AFA40018 */  sw         $a0, 0x18($sp)
    /* DD858 8015A768 90590009 */  lbu        $t9, 0x9($v0)
    /* DD85C 8015A76C 00194080 */  sll        $t0, $t9, 2
    /* DD860 8015A770 3C198019 */  lui        $t9, %hi(D_80190E58)
    /* DD864 8015A774 0328C821 */  addu       $t9, $t9, $t0
    /* DD868 8015A778 8F390E58 */  lw         $t9, %lo(D_80190E58)($t9)
    /* DD86C 8015A77C 0320F809 */  jalr       $t9
    /* DD870 8015A780 00000000 */   nop
    /* DD874 8015A784 8FA40018 */  lw         $a0, 0x18($sp)
    /* DD878 8015A788 8489000E */  lh         $t1, 0xE($a0)
    /* DD87C 8015A78C 252AFFFF */  addiu      $t2, $t1, -0x1
    /* DD880 8015A790 A48A000E */  sh         $t2, 0xE($a0)
    /* DD884 8015A794 8FBF0014 */  lw         $ra, 0x14($sp)
    /* DD888 8015A798 27BD0018 */  addiu      $sp, $sp, 0x18
    /* DD88C 8015A79C 03E00008 */  jr         $ra
    /* DD890 8015A7A0 00000000 */   nop
endlabel D_8015A718

nonmatching func_8015A7A4, 0x148

glabel func_8015A7A4
    /* DD894 8015A7A4 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* DD898 8015A7A8 AFBF001C */  sw         $ra, 0x1C($sp)
    /* DD89C 8015A7AC AFB10018 */  sw         $s1, 0x18($sp)
    /* DD8A0 8015A7B0 AFB00014 */  sw         $s0, 0x14($sp)
    /* DD8A4 8015A7B4 8C8E0070 */  lw         $t6, 0x70($a0)
    /* DD8A8 8015A7B8 00808025 */  or         $s0, $a0, $zero
    /* DD8AC 8015A7BC AFAE0030 */  sw         $t6, 0x30($sp)
    /* DD8B0 8015A7C0 8C8F0034 */  lw         $t7, 0x34($a0)
  alabel D_8015A7C4
    /* DD8B4 8015A7C4 8C910024 */  lw         $s1, 0x24($a0)
    /* DD8B8 8015A7C8 0C051DC6 */  jal        func_80147718
    /* DD8BC 8015A7CC 95E40008 */   lhu       $a0, 0x8($t7)
    /* DD8C0 8015A7D0 1040001F */  beqz       $v0, .L8015A850
    /* DD8C4 8015A7D4 26030034 */   addiu     $v1, $s0, 0x34
    /* DD8C8 8015A7D8 26030034 */  addiu      $v1, $s0, 0x34
    /* DD8CC 8015A7DC 8C790000 */  lw         $t9, 0x0($v1)
    /* DD8D0 8015A7E0 8FB80030 */  lw         $t8, 0x30($sp)
    /* DD8D4 8015A7E4 C46A0020 */  lwc1       $ft3, 0x20($v1)
    /* DD8D8 8015A7E8 C7260004 */  lwc1       $ft1, 0x4($t9)
    /* DD8DC 8015A7EC C7040008 */  lwc1       $ft0, 0x8($t8)
    /* DD8E0 8015A7F0 24090001 */  addiu      $t1, $zero, 0x1
    /* DD8E4 8015A7F4 46062201 */  sub.s      $ft2, $ft0, $ft1
    /* DD8E8 8015A7F8 4608503E */  c.le.s     $ft3, $ft2
    /* DD8EC 8015A7FC 00000000 */  nop
    /* DD8F0 8015A800 45000011 */  bc1f       .L8015A848
    /* DD8F4 8015A804 00000000 */   nop
    /* DD8F8 8015A808 8468002A */  lh         $t0, 0x2A($v1)
    /* DD8FC 8015A80C 24010001 */  addiu      $at, $zero, 0x1
    /* DD900 8015A810 24060008 */  addiu      $a2, $zero, 0x8
    /* DD904 8015A814 15010009 */  bne        $t0, $at, .L8015A83C
    /* DD908 8015A818 3C198014 */   lui       $t9, %hi(func_80146504)
    /* DD90C 8015A81C 8E24003C */  lw         $a0, 0x3C($s1)
    /* DD910 8015A820 8E250040 */  lw         $a1, 0x40($s1)
    /* DD914 8015A824 27396504 */  addiu      $t9, $t9, %lo(func_80146504)
    /* DD918 8015A828 0320F809 */  jalr       $t9
    /* DD91C 8015A82C AFA30020 */   sw        $v1, 0x20($sp)
    /* DD920 8015A830 8FA30020 */  lw         $v1, 0x20($sp)
    /* DD924 8015A834 AE220074 */  sw         $v0, 0x74($s1)
    /* DD928 8015A838 A460002A */  sh         $zero, 0x2A($v1)
  .L8015A83C:
    /* DD92C 8015A83C 44808000 */  mtc1       $zero, $ft4
    /* DD930 8015A840 10000025 */  b          .L8015A8D8
    /* DD934 8015A844 E4700014 */   swc1      $ft4, 0x14($v1)
  .L8015A848:
    /* DD938 8015A848 1000000E */  b          .L8015A884
    /* DD93C 8015A84C A4690018 */   sh        $t1, 0x18($v1)
  .L8015A850:
    /* DD940 8015A850 846A002A */  lh         $t2, 0x2A($v1)
    /* DD944 8015A854 3C198014 */  lui        $t9, %hi(func_80146504)
    /* DD948 8015A858 27396504 */  addiu      $t9, $t9, %lo(func_80146504)
    /* DD94C 8015A85C 15400009 */  bnez       $t2, .L8015A884
    /* DD950 8015A860 24060001 */   addiu     $a2, $zero, 0x1
    /* DD954 8015A864 8E24003C */  lw         $a0, 0x3C($s1)
    /* DD958 8015A868 8E250040 */  lw         $a1, 0x40($s1)
    /* DD95C 8015A86C 0320F809 */  jalr       $t9
    /* DD960 8015A870 AFA30020 */   sw        $v1, 0x20($sp)
    /* DD964 8015A874 8FA30020 */  lw         $v1, 0x20($sp)
    /* DD968 8015A878 AE220074 */  sw         $v0, 0x74($s1)
    /* DD96C 8015A87C 240B0001 */  addiu      $t3, $zero, 0x1
    /* DD970 8015A880 A46B002A */  sh         $t3, 0x2A($v1)
  .L8015A884:
    /* DD974 8015A884 8603000E */  lh         $v1, 0xE($s0)
    /* DD978 8015A888 3C198019 */  lui        $t9, %hi(D_80190E5C)
    /* DD97C 8015A88C 02002025 */  or         $a0, $s0, $zero
    /* DD980 8015A890 24630001 */  addiu      $v1, $v1, 0x1
    /* DD984 8015A894 00031C00 */  sll        $v1, $v1, 16
    /* DD988 8015A898 00031C03 */  sra        $v1, $v1, 16
    /* DD98C 8015A89C 00036040 */  sll        $t4, $v1, 1
    /* DD990 8015A8A0 020C1021 */  addu       $v0, $s0, $t4
    /* DD994 8015A8A4 A603000E */  sh         $v1, 0xE($s0)
    /* DD998 8015A8A8 904F0009 */  lbu        $t7, 0x9($v0)
    /* DD99C 8015A8AC 904D0008 */  lbu        $t5, 0x8($v0)
    /* DD9A0 8015A8B0 000FC080 */  sll        $t8, $t7, 2
    /* DD9A4 8015A8B4 25AE0001 */  addiu      $t6, $t5, 0x1
    /* DD9A8 8015A8B8 A04E0008 */  sb         $t6, 0x8($v0)
    /* DD9AC 8015A8BC 0338C821 */  addu       $t9, $t9, $t8
    /* DD9B0 8015A8C0 8F390E5C */  lw         $t9, %lo(D_80190E5C)($t9)
    /* DD9B4 8015A8C4 0320F809 */  jalr       $t9
    /* DD9B8 8015A8C8 00000000 */   nop
    /* DD9BC 8015A8CC 8608000E */  lh         $t0, 0xE($s0)
    /* DD9C0 8015A8D0 2509FFFF */  addiu      $t1, $t0, -0x1
    /* DD9C4 8015A8D4 A609000E */  sh         $t1, 0xE($s0)
  .L8015A8D8:
    /* DD9C8 8015A8D8 8FBF001C */  lw         $ra, 0x1C($sp)
    /* DD9CC 8015A8DC 8FB00014 */  lw         $s0, 0x14($sp)
    /* DD9D0 8015A8E0 8FB10018 */  lw         $s1, 0x18($sp)
    /* DD9D4 8015A8E4 03E00008 */  jr         $ra
    /* DD9D8 8015A8E8 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_8015A7A4

nonmatching func_8015A8EC, 0x1D4

glabel func_8015A8EC
    /* DD9DC 8015A8EC 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* DD9E0 8015A8F0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* DD9E4 8015A8F4 C4840054 */  lwc1       $ft0, 0x54($a0)
    /* DD9E8 8015A8F8 C4860048 */  lwc1       $ft1, 0x48($a0)
    /* DD9EC 8015A8FC 3C07801D */  lui        $a3, %hi(D_801C82C0)
    /* DD9F0 8015A900 24E782C0 */  addiu      $a3, $a3, %lo(D_801C82C0)
    /* DD9F4 8015A904 46062200 */  add.s      $ft2, $ft0, $ft1
    /* DD9F8 8015A908 8CE22968 */  lw         $v0, 0x2968($a3)
    /* DD9FC 8015A90C 44807800 */  mtc1       $zero, $fa1f
    /* DDA00 8015A910 44807000 */  mtc1       $zero, $fa1
    /* DDA04 8015A914 E4880054 */  swc1       $ft2, 0x54($a0)
    /* DDA08 8015A918 C4400030 */  lwc1       $fv0, 0x30($v0)
    /* DDA0C 8015A91C 8C850070 */  lw         $a1, 0x70($a0)
    /* DDA10 8015A920 24830034 */  addiu      $v1, $a0, 0x34
    /* DDA14 8015A924 460002A1 */  cvt.d.s    $ft3, $fv0
    /* DDA18 8015A928 3C01801A */  lui        $at, %hi(D_8019A0D0)
    /* DDA1C 8015A92C 462E503C */  c.lt.d     $ft3, $fa1
    /* DDA20 8015A930 00000000 */  nop
    /* DDA24 8015A934 45020003 */  bc1fl      .L8015A944
    /* DDA28 8015A938 846E0018 */   lh        $t6, 0x18($v1)
    /* DDA2C 8015A93C E4800050 */  swc1       $fv0, 0x50($a0)
    /* DDA30 8015A940 846E0018 */  lh         $t6, 0x18($v1)
  .L8015A944:
    /* DDA34 8015A944 24060001 */  addiu      $a2, $zero, 0x1
    /* DDA38 8015A948 50CE0005 */  beql       $a2, $t6, .L8015A960
    /* DDA3C 8015A94C 8CF82858 */   lw        $t8, 0x2858($a3)
    /* DDA40 8015A950 846F001A */  lh         $t7, 0x1A($v1)
    /* DDA44 8015A954 14CF0074 */  bne        $a2, $t7, .L8015AB28
    /* DDA48 8015A958 00000000 */   nop
    /* DDA4C 8015A95C 8CF82858 */  lw         $t8, 0x2858($a3)
  .L8015A960:
    /* DDA50 8015A960 C430A0D0 */  lwc1       $ft4, %lo(D_8019A0D0)($at)
    /* DDA54 8015A964 44809000 */  mtc1       $zero, $ft5
    /* DDA58 8015A968 33190010 */  andi       $t9, $t8, 0x10
    /* DDA5C 8015A96C 46008306 */  mov.s      $fa0, $ft4
    /* DDA60 8015A970 1720001F */  bnez       $t9, .L8015A9F0
    /* DDA64 8015A974 46009086 */   mov.s     $fv1, $ft5
    /* DDA68 8015A978 C4440030 */  lwc1       $ft0, 0x30($v0)
    /* DDA6C 8015A97C 3C01801A */  lui        $at, %hi(D_8019A0D8)
    /* DDA70 8015A980 46002021 */  cvt.d.s    $fv0, $ft0
    /* DDA74 8015A984 4620703C */  c.lt.d     $fa1, $fv0
    /* DDA78 8015A988 00000000 */  nop
    /* DDA7C 8015A98C 45020009 */  bc1fl      .L8015A9B4
    /* DDA80 8015A990 C460001C */   lwc1      $fv0, 0x1C($v1)
    /* DDA84 8015A994 D426A0D8 */  ldc1       $ft1, %lo(D_8019A0D8)($at)
    /* DDA88 8015A998 3C01801A */  lui        $at, %hi(D_8019A0E0)
    /* DDA8C 8015A99C D42AA0E0 */  ldc1       $ft3, %lo(D_8019A0E0)($at)
    /* DDA90 8015A9A0 46260202 */  mul.d      $ft2, $fv0, $ft1
    /* DDA94 8015A9A4 00000000 */  nop
    /* DDA98 8015A9A8 462A4102 */  mul.d      $ft0, $ft2, $ft3
    /* DDA9C 8015A9AC 462020A0 */  cvt.s.d    $fv1, $ft0
    /* DDAA0 8015A9B0 C460001C */  lwc1       $fv0, 0x1C($v1)
  .L8015A9B4:
    /* DDAA4 8015A9B4 3C01801A */  lui        $at, %hi(D_8019A0E8)
    /* DDAA8 8015A9B8 460001A1 */  cvt.d.s    $ft1, $fv0
    /* DDAAC 8015A9BC 462E303C */  c.lt.d     $ft1, $fa1
    /* DDAB0 8015A9C0 00000000 */  nop
    /* DDAB4 8015A9C4 4502000B */  bc1fl      .L8015A9F4
    /* DDAB8 8015A9C8 C4640014 */   lwc1      $ft0, 0x14($v1)
    /* DDABC 8015A9CC 46000207 */  neg.s      $ft2, $fv0
    /* DDAC0 8015A9D0 D424A0E8 */  ldc1       $ft0, %lo(D_8019A0E8)($at)
    /* DDAC4 8015A9D4 460042A1 */  cvt.d.s    $ft3, $ft2
    /* DDAC8 8015A9D8 3C01801A */  lui        $at, %hi(D_8019A0F0)
    /* DDACC 8015A9DC 46245182 */  mul.d      $ft1, $ft3, $ft0
    /* DDAD0 8015A9E0 D428A0F0 */  ldc1       $ft2, %lo(D_8019A0F0)($at)
    /* DDAD4 8015A9E4 E472001C */  swc1       $ft5, 0x1C($v1)
    /* DDAD8 8015A9E8 46283282 */  mul.d      $ft3, $ft1, $ft2
    /* DDADC 8015A9EC 462050A0 */  cvt.s.d    $fv1, $ft3
  .L8015A9F0:
    /* DDAE0 8015A9F0 C4640014 */  lwc1       $ft0, 0x14($v1)
  .L8015A9F4:
    /* DDAE4 8015A9F4 3C013FD0 */  lui        $at, (0x3FD00000 >> 16)
    /* DDAE8 8015A9F8 4604103C */  c.lt.s     $fv1, $ft0
    /* DDAEC 8015A9FC 00000000 */  nop
    /* DDAF0 8015AA00 45020003 */  bc1fl      .L8015AA10
    /* DDAF4 8015AA04 8CE22858 */   lw        $v0, 0x2858($a3)
    /* DDAF8 8015AA08 E4620014 */  swc1       $fv1, 0x14($v1)
    /* DDAFC 8015AA0C 8CE22858 */  lw         $v0, 0x2858($a3)
  .L8015AA10:
    /* DDB00 8015AA10 30480010 */  andi       $t0, $v0, 0x10
    /* DDB04 8015AA14 11000007 */  beqz       $t0, .L8015AA34
    /* DDB08 8015AA18 30490040 */   andi      $t1, $v0, 0x40
    /* DDB0C 8015AA1C 44814800 */  mtc1       $at, $ft2f
    /* DDB10 8015AA20 44804000 */  mtc1       $zero, $ft2
    /* DDB14 8015AA24 460081A1 */  cvt.d.s    $ft1, $ft4
    /* DDB18 8015AA28 46283282 */  mul.d      $ft3, $ft1, $ft2
    /* DDB1C 8015AA2C 10000008 */  b          .L8015AA50
    /* DDB20 8015AA30 46205320 */   cvt.s.d   $fa0, $ft3
  .L8015AA34:
    /* DDB24 8015AA34 11200006 */  beqz       $t1, .L8015AA50
    /* DDB28 8015AA38 3C013FF4 */   lui       $at, (0x3FF40000 >> 16)
    /* DDB2C 8015AA3C 44813800 */  mtc1       $at, $ft1f
    /* DDB30 8015AA40 44803000 */  mtc1       $zero, $ft1
    /* DDB34 8015AA44 46008121 */  cvt.d.s    $ft0, $ft4
    /* DDB38 8015AA48 46262202 */  mul.d      $ft2, $ft0, $ft1
    /* DDB3C 8015AA4C 46204320 */  cvt.s.d    $fa0, $ft2
  .L8015AA50:
    /* DDB40 8015AA50 8C620000 */  lw         $v0, 0x0($v1)
    /* DDB44 8015AA54 24010005 */  addiu      $at, $zero, 0x5
    /* DDB48 8015AA58 904A000A */  lbu        $t2, 0xA($v0)
    /* DDB4C 8015AA5C 5541000D */  bnel       $t2, $at, .L8015AA94
    /* DDB50 8015AA60 C4600014 */   lwc1      $fv0, 0x14($v1)
    /* DDB54 8015AA64 94440008 */  lhu        $a0, 0x8($v0)
    /* DDB58 8015AA68 E7AC0020 */  swc1       $fa0, 0x20($sp)
    /* DDB5C 8015AA6C 0C051DC6 */  jal        func_80147718
    /* DDB60 8015AA70 AFA3001C */   sw        $v1, 0x1C($sp)
    /* DDB64 8015AA74 3C07801D */  lui        $a3, %hi(D_801C82C0)
    /* DDB68 8015AA78 24E782C0 */  addiu      $a3, $a3, %lo(D_801C82C0)
    /* DDB6C 8015AA7C 8FA3001C */  lw         $v1, 0x1C($sp)
    /* DDB70 8015AA80 10400003 */  beqz       $v0, .L8015AA90
    /* DDB74 8015AA84 C7AC0020 */   lwc1      $fa0, 0x20($sp)
    /* DDB78 8015AA88 3C01801A */  lui        $at, %hi(D_8019A0F8)
    /* DDB7C 8015AA8C C42CA0F8 */  lwc1       $fa0, %lo(D_8019A0F8)($at)
  .L8015AA90:
    /* DDB80 8015AA90 C4600014 */  lwc1       $fv0, 0x14($v1)
  .L8015AA94:
    /* DDB84 8015AA94 46006032 */  c.eq.s     $fa0, $fv0
    /* DDB88 8015AA98 00000000 */  nop
    /* DDB8C 8015AA9C 4503001A */  bc1tl      .L8015AB08
    /* DDB90 8015AAA0 8CEB2964 */   lw        $t3, 0x2964($a3)
    /* DDB94 8015AAA4 4600603C */  c.lt.s     $fa0, $fv0
    /* DDB98 8015AAA8 3C01801A */  lui        $at, (0x801A0000 >> 16)
    /* DDB9C 8015AAAC 4500000C */  bc1f       .L8015AAE0
    /* DDBA0 8015AAB0 00000000 */   nop
    /* DDBA4 8015AAB4 3C01801A */  lui        $at, %hi(D_8019A0FC)
    /* DDBA8 8015AAB8 C42AA0FC */  lwc1       $ft3, %lo(D_8019A0FC)($at)
    /* DDBAC 8015AABC 460A0100 */  add.s      $ft0, $fv0, $ft3
endlabel func_8015A8EC

nonmatching func_8015AAC0, 0xD0

glabel func_8015AAC0
    /* DDBB0 8015AAC0 E4640014 */  swc1       $ft0, 0x14($v1)
    /* DDBB4 8015AAC4 C4660014 */  lwc1       $ft1, 0x14($v1)
    /* DDBB8 8015AAC8 460C303C */  c.lt.s     $ft1, $fa0
    /* DDBBC 8015AACC 00000000 */  nop
    /* DDBC0 8015AAD0 4502000D */  bc1fl      .L8015AB08
    /* DDBC4 8015AAD4 8CEB2964 */   lw        $t3, 0x2964($a3)
    /* DDBC8 8015AAD8 1000000A */  b          .L8015AB04
    /* DDBCC 8015AADC E46C0014 */   swc1      $fa0, 0x14($v1)
  .L8015AAE0:
    /* DDBD0 8015AAE0 C428A100 */  lwc1       $ft2, -0x5F00($at)
    /* DDBD4 8015AAE4 46080280 */  add.s      $ft3, $fv0, $ft2
    /* DDBD8 8015AAE8 E46A0014 */  swc1       $ft3, 0x14($v1)
    /* DDBDC 8015AAEC C4640014 */  lwc1       $ft0, 0x14($v1)
    /* DDBE0 8015AAF0 4604603C */  c.lt.s     $fa0, $ft0
    /* DDBE4 8015AAF4 00000000 */  nop
    /* DDBE8 8015AAF8 45020003 */  bc1fl      .L8015AB08
    /* DDBEC 8015AAFC 8CEB2964 */   lw        $t3, 0x2964($a3)
    /* DDBF0 8015AB00 E46C0014 */  swc1       $fa0, 0x14($v1)
  .L8015AB04:
    /* DDBF4 8015AB04 8CEB2964 */  lw         $t3, 0x2964($a3)
  .L8015AB08:
    /* DDBF8 8015AB08 3C01801A */  lui        $at, %hi(D_8019A104)
    /* DDBFC 8015AB0C 8D6C0000 */  lw         $t4, 0x0($t3)
    /* DDC00 8015AB10 000C6800 */  sll        $t5, $t4, 0
    /* DDC04 8015AB14 05A3001B */  bgezl      $t5, .L8015AB84
    /* DDC08 8015AB18 8FBF0014 */   lw        $ra, 0x14($sp)
    /* DDC0C 8015AB1C C426A104 */  lwc1       $ft1, %lo(D_8019A104)($at)
    /* DDC10 8015AB20 10000017 */  b          .L8015AB80
    /* DDC14 8015AB24 E4660014 */   swc1      $ft1, 0x14($v1)
  .L8015AB28:
    /* DDC18 8015AB28 3C01801A */  lui        $at, %hi(D_8019A108)
    /* DDC1C 8015AB2C C422A108 */  lwc1       $fv1, %lo(D_8019A108)($at)
    /* DDC20 8015AB30 C4600014 */  lwc1       $fv0, 0x14($v1)
    /* DDC24 8015AB34 3C01801A */  lui        $at, %hi(D_8019A10C)
    /* DDC28 8015AB38 4602003C */  c.lt.s     $fv0, $fv1
    /* DDC2C 8015AB3C 00000000 */  nop
    /* DDC30 8015AB40 45020006 */  bc1fl      .L8015AB5C
    /* DDC34 8015AB44 E4620014 */   swc1      $fv1, 0x14($v1)
    /* DDC38 8015AB48 C428A10C */  lwc1       $ft2, %lo(D_8019A10C)($at)
    /* DDC3C 8015AB4C 46080280 */  add.s      $ft3, $fv0, $ft2
    /* DDC40 8015AB50 10000002 */  b          .L8015AB5C
    /* DDC44 8015AB54 E46A0014 */   swc1      $ft3, 0x14($v1)
    /* DDC48 8015AB58 E4620014 */  swc1       $fv1, 0x14($v1)
  .L8015AB5C:
    /* DDC4C 8015AB5C C4A00008 */  lwc1       $fv0, 0x8($a1)
    /* DDC50 8015AB60 C4640020 */  lwc1       $ft0, 0x20($v1)
    /* DDC54 8015AB64 4604003E */  c.le.s     $fv0, $ft0
    /* DDC58 8015AB68 00000000 */  nop
    /* DDC5C 8015AB6C 45020005 */  bc1fl      .L8015AB84
    /* DDC60 8015AB70 8FBF0014 */   lw        $ra, 0x14($sp)
    /* DDC64 8015AB74 44809000 */  mtc1       $zero, $ft5
    /* DDC68 8015AB78 E4600020 */  swc1       $fv0, 0x20($v1)
    /* DDC6C 8015AB7C E4720014 */  swc1       $ft5, 0x14($v1)
  .L8015AB80:
    /* DDC70 8015AB80 8FBF0014 */  lw         $ra, 0x14($sp)
  .L8015AB84:
    /* DDC74 8015AB84 27BD0038 */  addiu      $sp, $sp, 0x38
    /* DDC78 8015AB88 03E00008 */  jr         $ra
    /* DDC7C 8015AB8C 00000000 */   nop
endlabel func_8015AAC0

nonmatching func_8015AB90, 0x24

glabel func_8015AB90
    /* DDC80 8015AB90 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* DDC84 8015AB94 AFBF0014 */  sw         $ra, 0x14($sp)
    /* DDC88 8015AB98 8C990010 */  lw         $t9, 0x10($a0)
    /* DDC8C 8015AB9C 0320F809 */  jalr       $t9
    /* DDC90 8015ABA0 00000000 */   nop
    /* DDC94 8015ABA4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* DDC98 8015ABA8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* DDC9C 8015ABAC 03E00008 */  jr         $ra
    /* DDCA0 8015ABB0 00000000 */   nop
endlabel func_8015AB90

nonmatching func_8015ABB4, 0x98

glabel func_8015ABB4
    /* DDCA4 8015ABB4 3C02801D */  lui        $v0, %hi(D_801CAB90)
    /* DDCA8 8015ABB8 8442AB90 */  lh         $v0, %lo(D_801CAB90)($v0)
    /* DDCAC 8015ABBC 2401001E */  addiu      $at, $zero, 0x1E
    /* DDCB0 8015ABC0 8C830070 */  lw         $v1, 0x70($a0)
    /* DDCB4 8015ABC4 10410007 */  beq        $v0, $at, .L8015ABE4
    /* DDCB8 8015ABC8 24010020 */   addiu     $at, $zero, 0x20
    /* DDCBC 8015ABCC 1041000D */  beq        $v0, $at, .L8015AC04
    /* DDCC0 8015ABD0 24010027 */   addiu     $at, $zero, 0x27
    /* DDCC4 8015ABD4 50410014 */  beql       $v0, $at, .L8015AC28
    /* DDCC8 8015ABD8 946A0018 */   lhu       $t2, 0x18($v1)
    /* DDCCC 8015ABDC 10000019 */  b          .L8015AC44
    /* DDCD0 8015ABE0 00001025 */   or        $v0, $zero, $zero
  .L8015ABE4:
    /* DDCD4 8015ABE4 946E0018 */  lhu        $t6, 0x18($v1)
    /* DDCD8 8015ABE8 3C188019 */  lui        $t8, %hi(D_80190CF0)
    /* DDCDC 8015ABEC 27180CF0 */  addiu      $t8, $t8, %lo(D_80190CF0)
    /* DDCE0 8015ABF0 000E7880 */  sll        $t7, $t6, 2
    /* DDCE4 8015ABF4 01EE7823 */  subu       $t7, $t7, $t6
    /* DDCE8 8015ABF8 000F7880 */  sll        $t7, $t7, 2
    /* DDCEC 8015ABFC 03E00008 */  jr         $ra
    /* DDCF0 8015AC00 01F81021 */   addu      $v0, $t7, $t8
  .L8015AC04:
    /* DDCF4 8015AC04 94790018 */  lhu        $t9, 0x18($v1)
    /* DDCF8 8015AC08 3C098019 */  lui        $t1, %hi(D_80190D14)
    /* DDCFC 8015AC0C 25290D14 */  addiu      $t1, $t1, %lo(D_80190D14)
    /* DDD00 8015AC10 00194080 */  sll        $t0, $t9, 2
    /* DDD04 8015AC14 01194023 */  subu       $t0, $t0, $t9
    /* DDD08 8015AC18 00084080 */  sll        $t0, $t0, 2
    /* DDD0C 8015AC1C 03E00008 */  jr         $ra
    /* DDD10 8015AC20 01091021 */   addu      $v0, $t0, $t1
    /* DDD14 8015AC24 946A0018 */  lhu        $t2, 0x18($v1)
  .L8015AC28:
    /* DDD18 8015AC28 3C0C8019 */  lui        $t4, %hi(D_80190DC8)
    /* DDD1C 8015AC2C 258C0DC8 */  addiu      $t4, $t4, %lo(D_80190DC8)
    /* DDD20 8015AC30 000A5880 */  sll        $t3, $t2, 2
    /* DDD24 8015AC34 016A5823 */  subu       $t3, $t3, $t2
    /* DDD28 8015AC38 000B5880 */  sll        $t3, $t3, 2
    /* DDD2C 8015AC3C 03E00008 */  jr         $ra
    /* DDD30 8015AC40 016C1021 */   addu      $v0, $t3, $t4
  .L8015AC44:
    /* DDD34 8015AC44 03E00008 */  jr         $ra
    /* DDD38 8015AC48 00000000 */   nop
endlabel func_8015ABB4

nonmatching func_8015AC4C, 0x3C

glabel func_8015AC4C
    /* DDD3C 8015AC4C 3C0E800F */  lui        $t6, %hi(D_800F3648)
    /* DDD40 8015AC50 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* DDD44 8015AC54 25CE3648 */  addiu      $t6, $t6, %lo(D_800F3648)
    /* DDD48 8015AC58 AFBF0014 */  sw         $ra, 0x14($sp)
    /* DDD4C 8015AC5C 14AE0003 */  bne        $a1, $t6, .L8015AC6C
    /* DDD50 8015AC60 00803825 */   or        $a3, $a0, $zero
    /* DDD54 8015AC64 240F0001 */  addiu      $t7, $zero, 0x1
    /* DDD58 8015AC68 A48F004C */  sh         $t7, 0x4C($a0)
  .L8015AC6C:
    /* DDD5C 8015AC6C 8CE40024 */  lw         $a0, 0x24($a3)
    /* DDD60 8015AC70 0C052086 */  jal        func_80148218
    /* DDD64 8015AC74 24E6003C */   addiu     $a2, $a3, 0x3C
    /* DDD68 8015AC78 8FBF0014 */  lw         $ra, 0x14($sp)
    /* DDD6C 8015AC7C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* DDD70 8015AC80 03E00008 */  jr         $ra
    /* DDD74 8015AC84 00000000 */   nop
endlabel func_8015AC4C

nonmatching func_8015AC88, 0x3C

glabel func_8015AC88
    /* DDD78 8015AC88 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* DDD7C 8015AC8C AFBF0014 */  sw         $ra, 0x14($sp)
    /* DDD80 8015AC90 848E0000 */  lh         $t6, 0x0($a0)
    /* DDD84 8015AC94 31CFF7FF */  andi       $t7, $t6, 0xF7FF
    /* DDD88 8015AC98 A48F0000 */  sh         $t7, 0x0($a0)
    /* DDD8C 8015AC9C 0C051A7D */  jal        func_801469F4
    /* DDD90 8015ACA0 AFA40018 */   sw        $a0, 0x18($sp)
    /* DDD94 8015ACA4 8FA40018 */  lw         $a0, 0x18($sp)
    /* DDD98 8015ACA8 8C990038 */  lw         $t9, 0x38($a0)
    /* DDD9C 8015ACAC 0320F809 */  jalr       $t9
    /* DDDA0 8015ACB0 00000000 */   nop
    /* DDDA4 8015ACB4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* DDDA8 8015ACB8 27BD0018 */  addiu      $sp, $sp, 0x18
    /* DDDAC 8015ACBC 03E00008 */  jr         $ra
    /* DDDB0 8015ACC0 00000000 */   nop
endlabel func_8015AC88
    /* DDDB4 8015ACC4 00000000 */  nop
    /* DDDB8 8015ACC8 00000000 */  nop
    /* DDDBC 8015ACCC 00000000 */  nop

nonmatching func_8015ACD0, 0x70

glabel func_8015ACD0
    /* DDDC0 8015ACD0 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* DDDC4 8015ACD4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* DDDC8 8015ACD8 8483000E */  lh         $v1, 0xE($a0)
    /* DDDCC 8015ACDC 24630001 */  addiu      $v1, $v1, 0x1
    /* DDDD0 8015ACE0 00031C00 */  sll        $v1, $v1, 16
    /* DDDD4 8015ACE4 00031C03 */  sra        $v1, $v1, 16
    /* DDDD8 8015ACE8 00037040 */  sll        $t6, $v1, 1
    /* DDDDC 8015ACEC 008E1021 */  addu       $v0, $a0, $t6
    /* DDDE0 8015ACF0 A483000E */  sh         $v1, 0xE($a0)
    /* DDDE4 8015ACF4 904F0008 */  lbu        $t7, 0x8($v0)
    /* DDDE8 8015ACF8 25F80001 */  addiu      $t8, $t7, 0x1
    /* DDDEC 8015ACFC A0580008 */  sb         $t8, 0x8($v0)
    /* DDDF0 8015AD00 AFA40018 */  sw         $a0, 0x18($sp)
    /* DDDF4 8015AD04 90590009 */  lbu        $t9, 0x9($v0)
    /* DDDF8 8015AD08 00194080 */  sll        $t0, $t9, 2
    /* DDDFC 8015AD0C 3C198019 */  lui        $t9, %hi(D_80190E60)
    /* DDE00 8015AD10 0328C821 */  addu       $t9, $t9, $t0
    /* DDE04 8015AD14 8F390E60 */  lw         $t9, %lo(D_80190E60)($t9)
    /* DDE08 8015AD18 0320F809 */  jalr       $t9
    /* DDE0C 8015AD1C 00000000 */   nop
    /* DDE10 8015AD20 8FA40018 */  lw         $a0, 0x18($sp)
    /* DDE14 8015AD24 8489000E */  lh         $t1, 0xE($a0)
    /* DDE18 8015AD28 252AFFFF */  addiu      $t2, $t1, -0x1
    /* DDE1C 8015AD2C A48A000E */  sh         $t2, 0xE($a0)
    /* DDE20 8015AD30 8FBF0014 */  lw         $ra, 0x14($sp)
    /* DDE24 8015AD34 27BD0018 */  addiu      $sp, $sp, 0x18
    /* DDE28 8015AD38 03E00008 */  jr         $ra
    /* DDE2C 8015AD3C 00000000 */   nop
endlabel func_8015ACD0

nonmatching func_8015AD40, 0x10

glabel func_8015AD40
    /* DDE30 8015AD40 27BDFFD0 */  addiu      $sp, $sp, -0x30
    /* DDE34 8015AD44 AFB00018 */  sw         $s0, 0x18($sp)
    /* DDE38 8015AD48 3C198000 */  lui        $t9, (0x80000000 >> 16)
    /* DDE3C 8015AD4C 00808025 */  or         $s0, $a0, $zero
endlabel func_8015AD40
