.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80086FA0, 0x90

glabel func_80086FA0
    jr $ra
    nop
  .L80086FC8:
    jr $ra
    nop
  .L80087018:
    jr $ra
    nop
  .L80087020:
    jr $ra
    nop
endlabel func_80086FA0

nonmatching func_80087030, 0x40

glabel func_80087030
    jr $ra
    nop
endlabel func_80087030

nonmatching func_80087070, 0x40

glabel func_80087070
    jr $ra
    nop
  .L800870A8:
    jr $ra
    nop
endlabel func_80087070
