.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008B990, 0x80

glabel func_8008B990
    /* 8C590 8008B990 84CA287A */  lh         $t2, 0x287A($a2)
    /* 8C594 8008B994 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
    /* 8C598 8008B998 44819000 */  mtc1       $at, $ft5
    /* 8C59C 8008B99C 254B0064 */  addiu      $t3, $t2, 0x64
    /* 8C5A0 8008B9A0 A4CB287A */  sh         $t3, 0x287A($a2)
    /* 8C5A4 8008B9A4 C446000C */  lwc1       $ft1, 0xC($v0)
    /* 8C5A8 8008B9A8 240D2710 */  addiu      $t5, $zero, 0x2710
    /* 8C5AC 8008B9AC 240E0001 */  addiu      $t6, $zero, 0x1
    /* 8C5B0 8008B9B0 46123101 */  sub.s      $ft0, $ft1, $ft5
    /* 8C5B4 8008B9B4 3C0F800B */  lui        $t7, %hi(D_800B78C4)
    /* 8C5B8 8008B9B8 E444000C */  swc1       $ft0, 0xC($v0)
    /* 8C5BC 8008B9BC 84CC287A */  lh         $t4, 0x287A($a2)
    /* 8C5C0 8008B9C0 29812710 */  slti       $at, $t4, 0x2710
    /* 8C5C4 8008B9C4 54200008 */  bnel       $at, $zero, .L8008B9E8
    /* 8C5C8 8008B9C8 C44A000C */   lwc1      $ft3, 0xC($v0)
    /* 8C5CC 8008B9CC A4CD287A */  sh         $t5, 0x287A($a2)
    /* 8C5D0 8008B9D0 A440000A */  sh         $zero, 0xA($v0)
    /* 8C5D4 8008B9D4 E44E000C */  swc1       $fa1, 0xC($v0)
    /* 8C5D8 8008B9D8 E4EE0068 */  swc1       $fa1, 0x68($a3)
    /* 8C5DC 8008B9DC A440003C */  sh         $zero, 0x3C($v0)
    /* 8C5E0 8008B9E0 A10E0000 */  sb         $t6, 0x0($t0)
    /* 8C5E4 8008B9E4 C44A000C */  lwc1       $ft3, 0xC($v0)
  .L8008B9E8:
    /* 8C5E8 8008B9E8 460A7032 */  c.eq.s     $fa1, $ft3
    /* 8C5EC 8008B9EC 00000000 */  nop
# PATCHED: # PATCHED: /* 8C5F0 8008B9F0 45000020 */  bc1f       D_8008BA74
    nop
    nop
    /* 8C5F4 8008B9F4 00000000 */   nop
    /* 8C5F8 8008B9F8 91EF78C4 */  lbu        $t7, %lo(D_800B78C4)($t7)
# PATCHED: # PATCHED: /* 8C5FC 8008B9FC 15E0001B */  bnez       $t7, D_8008BA6C
    nop
    nop
    /* 8C600 8008BA00 00000000 */   nop
    /* 8C604 8008BA04 84D82874 */  lh         $t8, 0x2874($a2)
    /* 8C608 8008BA08 24010001 */  addiu      $at, $zero, 0x1
    /* 8C60C 8008BA0C 24040258 */  addiu      $a0, $zero, 0x258
endlabel func_8008B990
