.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80089D60, 0x40

glabel func_80089D60
    /* 8A960 80089D60 44199000 */  mfc1       $t9, $ft5
    /* 8A964 80089D64 46802420 */  cvt.s.w    $ft4, $ft0
    /* 8A968 80089D68 00195823 */  negu       $t3, $t9
    /* 8A96C 80089D6C 05810003 */  bgez       $t4, .L80089D7C
    /* 8A970 80089D70 000C7043 */   sra       $t6, $t4, 1
    /* 8A974 80089D74 25810001 */  addiu      $at, $t4, 0x1
    /* 8A978 80089D78 00017043 */  sra        $t6, $at, 1
  .L80089D7C:
    /* 8A97C 80089D7C 46100281 */  sub.s      $ft3, $fv0, $ft4
    /* 8A980 80089D80 016E3023 */  subu       $a2, $t3, $t6
    /* 8A984 80089D84 24C60078 */  addiu      $a2, $a2, 0x78
    /* 8A988 80089D88 30C6FFFF */  andi       $a2, $a2, 0xFFFF
    /* 8A98C 80089D8C 460051A1 */  cvt.d.s    $ft1, $ft3
    /* 8A990 80089D90 4626103C */  c.lt.d     $fv1, $ft1
    /* 8A994 80089D94 00000000 */  nop
# PATCHED: # PATCHED: /* 8A998 80089D98 45020004 */  bc1fl      D_80089DAC
    nop
    nop
    /* 8A99C 80089D9C C5200054 */   lwc1      $fv0, 0x54($t1)
endlabel func_80089D60
