.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008F470, 0x38

glabel func_8008F470
    jr $ra
    nop
endlabel func_8008F470
    /* 900A8 8008F4A8 00000000 */  nop
    /* 900AC 8008F4AC 00000000 */  nop

nonmatching func_8008F4B0, 0x20

glabel func_8008F4B0
    jr $ra
    nop
endlabel func_8008F4B0
