.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80086340, 0xFC

glabel func_80086340
    jr $ra
    nop
  .L800863E4:
    jr $ra
    nop
  .L800863E8:
    jr $ra
    nop
  .L800863EC:
    jr $ra
    nop
  .L80086418:
    jr $ra
    nop
  .L80086430:
    jr $ra
    nop
endlabel func_80086340

nonmatching func_8008643C, 0xEC

glabel func_8008643C
    jr $ra
    nop
  .L80086474:
    jr $ra
    nop
  .L80086484:
    jr $ra
    nop
  .L800864A8:
    jr $ra
    nop
  .L800864CC:
    jr $ra
    nop
  .L800864F0:
    jr $ra
    nop
  .L8008651C:
    jr $ra
    nop
endlabel func_8008643C

nonmatching func_80086528, 0xC8

glabel func_80086528
    jr $ra
    nop
  .L80086570:
    jr $ra
    nop
  .L80086590:
    jr $ra
    nop
  .L800865B0:
    jr $ra
    nop
  .L800865D0:
    jr $ra
    nop
  .L800865E0:
    jr $ra
    nop
  .L800865E4:
    jr $ra
    nop
endlabel func_80086528

nonmatching func_800865F0, 0x1E4

glabel func_800865F0
    jr $ra
    nop
  .L8008666C:
    jr $ra
    nop
  .L80086774:
    jr $ra
    nop
  .L80086780:
    jr $ra
    nop
  .L8008678C:
    jr $ra
    nop
  .L800867A8:
    jr $ra
    nop
  .L800867C0:
    jr $ra
    nop
endlabel func_800865F0

nonmatching func_800867D4, 0xA4

glabel func_800867D4
    jr $ra
    nop
  .L8008680C:
    jr $ra
    nop
  .L80086828:
    jr $ra
    nop
  .L8008684C:
    jr $ra
    nop
  .L80086868:
    jr $ra
    nop
endlabel func_800867D4

nonmatching func_80086878, 0x7C

glabel func_80086878
    jr $ra
    nop
  .L800868B0:
    jr $ra
    nop
  .L800868CC:
    jr $ra
    nop
  .L800868E4:
    jr $ra
    nop
endlabel func_80086878

nonmatching func_800868F4, 0x150

glabel func_800868F4
    jr $ra
    nop
  .L8008692C:
    jr $ra
    nop
  .L800869FC:
    jr $ra
    nop
  .L80086A08:
    jr $ra
    nop
  .L80086A14:
    jr $ra
    nop
  .L80086A2C:
    jr $ra
    nop
  .L80086A30:
    jr $ra
    nop
endlabel func_800868F4

nonmatching func_80086A44, 0x1F8

glabel func_80086A44
    jr $ra
    nop
  .L80086A70:
    jr $ra
    nop
  .L80086B54:
    jr $ra
    nop
  .L80086B60:
    jr $ra
    nop
  .L80086B6C:
    jr $ra
    nop
  .L80086B9C:
    jr $ra
    nop
  .L80086BC0:
    jr $ra
    nop
  .L80086BEC:
    jr $ra
    nop
  .L80086C0C:
    jr $ra
    nop
  .L80086C24:
    jr $ra
    nop
  .L80086C28:
    jr $ra
    nop
endlabel func_80086A44

nonmatching func_80086C3C, 0x274

glabel func_80086C3C
    jr $ra
    nop
  .L80086CC8:
    jr $ra
    nop
  .L80086CFC:
    jr $ra
    nop
  .L80086D70:
    jr $ra
    nop
  .L80086E5C:
    jr $ra
    nop
  .L80086E68:
    jr $ra
    nop
  .L80086E74:
    jr $ra
    nop
  .L80086E84:
    jr $ra
    nop
  .L80086E98:
    jr $ra
    nop
  .L80086E9C:
    jr $ra
    nop
endlabel func_80086C3C

nonmatching func_80086EB0, 0xD4

glabel func_80086EB0
    jr $ra
    nop
  .L80086EF4:
    jr $ra
    nop
  .L80086F04:
    jr $ra
    nop
  .L80086F18:
    jr $ra
    nop
  .L80086F24:
    jr $ra
    nop
  .L80086F5C:
    jr $ra
    nop
  .L80086F6C:
    jr $ra
    nop
  .L80086F70:
    jr $ra
    nop
endlabel func_80086EB0
    /* 87B84 80086F84 00000000 */  nop
    /* 87B88 80086F88 00000000 */  nop
    /* 87B8C 80086F8C 00000000 */  nop

nonmatching func_80086F90, 0x10

glabel func_80086F90
    jr $ra
    nop
endlabel func_80086F90
