.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80083D20, 0x8

glabel func_80083D20
    jr $ra
    nop
endlabel func_80083D20

nonmatching D_80083D28, 0x88

glabel D_80083D28
    jr $ra
    nop
  .L80083D40:
    jr $ra
    nop
  .L80083D50:
    jr $ra
    nop
  .L80083D78:
    jr $ra
    nop
  .L80083D88:
    jr $ra
    nop
  .L80083D94:
    jr $ra
    nop
  .L80083DA8:
    jr $ra
    nop
endlabel D_80083D28
