.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_800844C0, 0x4

glabel func_800844C0
    /* 850C0 800844C0 00000000 */  nop
endlabel func_800844C0

nonmatching .L800844C4, 0x4

glabel .L800844C4
    /* 850C4 800844C4 8C430020 */  lw         $v1, 0x20($v0)
endlabel .L800844C4

nonmatching D_800844C8, 0x10

glabel D_800844C8
    /* 850C8 800844C8 30780008 */  andi       $t8, $v1, 0x8
# PATCHED: # PATCHED: /* 850CC 800844CC 17000002 */  bnez       $t8, D_800844D8
    nop
    nop
    /* 850D0 800844D0 34790008 */   ori       $t9, $v1, 0x8
    /* 850D4 800844D4 AC590020 */  sw         $t9, 0x20($v0)
endlabel D_800844C8

nonmatching D_800844D8, 0x74

glabel D_800844D8
    /* 850D8 800844D8 03E00008 */  jr         $ra
    /* 850DC 800844DC 00000000 */   nop
    /* 850E0 800844E0 AFA50004 */  sw         $a1, 0x4($sp)
    /* 850E4 800844E4 8C820038 */  lw         $v0, 0x38($a0)
    /* 850E8 800844E8 30A500FF */  andi       $a1, $a1, 0xFF
    /* 850EC 800844EC 8C83003C */  lw         $v1, 0x3C($a0)
# PATCHED: # PATCHED: /* 850F0 800844F0 10400038 */  beqz       $v0, D_800845D4
    nop
    nop
    /* 850F4 800844F4 00000000 */   nop
# PATCHED: # PATCHED: /* 850F8 800844F8 10600036 */  beqz       $v1, D_800845D4
    nop
    nop
    /* 850FC 800844FC 00000000 */   nop
    /* 85100 80084500 90440026 */  lbu        $a0, 0x26($v0)
    /* 85104 80084504 24060001 */  addiu      $a2, $zero, 0x1
# PATCHED: # PATCHED: /* 85108 80084508 10800032 */  beqz       $a0, D_800845D4
    nop
    nop
    /* 8510C 8008450C 00000000 */   nop
# PATCHED: # PATCHED: /* 85110 80084510 10C40030 */  beq        $a2, $a0, D_800845D4
    nop
    nop
    /* 85114 80084514 24010002 */   addiu     $at, $zero, 0x2
# PATCHED: # PATCHED: /* 85118 80084518 1081002E */  beq        $a0, $at, D_800845D4
    nop
    nop
    /* 8511C 8008451C 00000000 */   nop
    /* 85120 80084520 50A00006 */  beql       $a1, $zero, .L8008453C
    /* 85124 80084524 904E0024 */   lbu       $t6, 0x24($v0)
# PATCHED: # PATCHED: /* 85128 80084528 50A60016 */  beql       $a1, $a2, D_80084584
    nop
    nop
    /* 8512C 8008452C 90480024 */   lbu       $t0, 0x24($v0)
# PATCHED: # PATCHED: /* 85130 80084530 10000024 */  b          D_800845C4
    nop
    nop
    /* 85134 80084534 8C430020 */   lw        $v1, 0x20($v0)
    /* 85138 80084538 904E0024 */  lbu        $t6, 0x24($v0)
  .L8008453C:
    /* 8513C 8008453C 00002025 */  or         $a0, $zero, $zero
    /* 85140 80084540 2405000E */  addiu      $a1, $zero, 0xE
# PATCHED: # PATCHED: /* 85144 80084544 59C0001F */  blezl      $t6, D_800845C4
    nop
    nop
    /* 85148 80084548 8C430020 */   lw        $v1, 0x20($v0)
endlabel D_800844D8

nonmatching D_8008454C, 0x4

glabel D_8008454C
    /* 8514C 8008454C 00850019 */  multu      $a0, $a1
endlabel D_8008454C
