.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80089A70, 0x140

glabel func_80089A70
    jr $ra
    nop
endlabel func_80089A70

nonmatching D_80089BB0, 0x8

glabel D_80089BB0
    jr $ra
    nop
endlabel D_80089BB0

nonmatching func_80089BB8, 0x78

glabel func_80089BB8
    jr $ra
    nop
  .L80089C08:
    jr $ra
    nop
  .L80089C0C:
    jr $ra
    nop
  .L80089C24:
    jr $ra
    nop
endlabel func_80089BB8
