.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8007FCF0, 0x1C0

glabel func_8007FCF0
    jr $ra
    nop
  .L8007FDC8:
    jr $ra
    nop
  .L8007FE84:
    jr $ra
    nop
  .L8007FEA0:
    jr $ra
    nop
endlabel func_8007FCF0
