.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8004CF20, 0x28

glabel func_8004CF20
    jr $ra
    nop
  .L8004CF28:
    jr $ra
    nop
endlabel func_8004CF20

nonmatching D_8004CF48, 0x18

glabel D_8004CF48
    jr $ra
    nop
endlabel D_8004CF48

nonmatching D_8004CF60, 0x38

glabel D_8004CF60
    jr $ra
    nop
  .L8004CF88:
    jr $ra
    nop
  .L8004CF8C:
    jr $ra
    nop
endlabel D_8004CF60

nonmatching func_8004CF98, 0x328

glabel func_8004CF98
    jr $ra
    nop
  .L8004CFEC:
    jr $ra
    nop
  .L8004D038:
    jr $ra
    nop
  .L8004D04C:
    jr $ra
    nop
  .L8004D0D0:
    jr $ra
    nop
  .L8004D0F8:
    jr $ra
    nop
  .L8004D1C4:
    jr $ra
    nop
  .L8004D1E8:
    jr $ra
    nop
  .L8004D214:
    jr $ra
    nop
endlabel func_8004CF98
