.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80055890, 0x240

glabel func_80055890
    jr $ra
    nop
  .L800558F0:
    jr $ra
    nop
  .L80055974:
    jr $ra
    nop
  alabel D_80055AC0
    jr $ra
    nop
endlabel func_80055890
