.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_800A7050

dlabel D_800A7050
    /* A7C50 800A7050 15800005 */ .word 0x15800005
    /* A7C54 800A7054 00000000 */ .word 0x00000000
    /* A7C58 800A7058 440C2000 */ .word 0x440C2000
    /* A7C5C 800A705C 3C018000 */ .word 0x3C018000
enddlabel D_800A7050
