.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80088C50, 0x20

glabel func_80088C50
    jr $ra
    nop
endlabel func_80088C50
