.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80080CB0, 0x44

glabel func_80080CB0
    jr $ra
    nop
  .L80080CBC:
    jr $ra
    nop
  .L80080CE0:
    jr $ra
    nop
endlabel func_80080CB0

nonmatching D_80080CF4, 0xC8

glabel D_80080CF4
    jr $ra
    nop
  alabel func_80080CFC
    jr $ra
    nop
  .L80080D30:
    jr $ra
    nop
  .L80080D54:
    jr $ra
    nop
  .L80080D6C:
    jr $ra
    nop
  .L80080D70:
    jr $ra
    nop
  .L80080D94:
    jr $ra
    nop
  .L80080DA8:
    jr $ra
    nop
endlabel D_80080CF4

nonmatching D_80080DBC, 0x4

glabel D_80080DBC
    jr $ra
    nop
endlabel D_80080DBC
