.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching .L800824A0, 0x8

glabel .L800824A0
    /* 830A0 800824A0 256C0001 */  addiu      $t4, $t3, 0x1
    /* 830A4 800824A4 A4CC0002 */  sh         $t4, 0x2($a2)
endlabel .L800824A0

nonmatching D_800824A8, 0x8

glabel D_800824A8
    /* 830A8 800824A8 94AD0000 */  lhu        $t5, 0x0($a1)
    /* 830AC 800824AC 00001025 */  or         $v0, $zero, $zero
endlabel D_800824A8
