.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008AFB0, 0x90

glabel func_8008AFB0
    jr $ra
    nop
endlabel func_8008AFB0
