.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008A510, 0x1C

glabel func_8008A510
    jr $ra
    nop
endlabel func_8008A510

nonmatching D_8008A52C, 0x4

glabel D_8008A52C
    jr $ra
    nop
endlabel D_8008A52C
