.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008D7A0, 0x40

glabel func_8008D7A0
    /* 8E3A0 8008D7A0 A478001E */  sh         $t8, 0x1E($v1)
    /* 8E3A4 8008D7A4 A4790022 */  sh         $t9, 0x22($v1)
    /* 8E3A8 8008D7A8 AC6F0024 */  sw         $t7, 0x24($v1)
    /* 8E3AC 8008D7AC E4600014 */  swc1       $fv0, 0x14($v1)
    /* 8E3B0 8008D7B0 E4600010 */  swc1       $fv0, 0x10($v1)
    /* 8E3B4 8008D7B4 E4620008 */  swc1       $fv1, 0x8($v1)
    /* 8E3B8 8008D7B8 E4620004 */  swc1       $fv1, 0x4($v1)
    /* 8E3BC 8008D7BC 8FAE0040 */  lw         $t6, 0x40($sp)
    /* 8E3C0 8008D7C0 3C0D800B */  lui        $t5, %hi(D_800B7A94)
    /* 8E3C4 8008D7C4 8DC4006C */  lw         $a0, 0x6C($t6)
    /* 8E3C8 8008D7C8 30840003 */  andi       $a0, $a0, 0x3
    /* 8E3CC 8008D7CC 00046080 */  sll        $t4, $a0, 2
    /* 8E3D0 8008D7D0 01AC6821 */  addu       $t5, $t5, $t4
    /* 8E3D4 8008D7D4 8DAD7A94 */  lw         $t5, %lo(D_800B7A94)($t5)
    /* 8E3D8 8008D7D8 AC6D0024 */  sw         $t5, 0x24($v1)
    /* 8E3DC 8008D7DC 8FA50020 */  lw         $a1, 0x20($sp)
endlabel func_8008D7A0

nonmatching D_8008D7E0, 0x20

glabel D_8008D7E0
    /* 8E3E0 8008D7E0 02002025 */  or         $a0, $s0, $zero
    /* 8E3E4 8008D7E4 AFAB0034 */  sw         $t3, 0x34($sp)
    /* 8E3E8 8008D7E8 0C0237A0 */  jal        func_8008DE80
    /* 8E3EC 8008D7EC 24A60020 */   addiu     $a2, $a1, 0x20
    /* 8E3F0 8008D7F0 8FAB0034 */  lw         $t3, 0x34($sp)
    /* 8E3F4 8008D7F4 3C198000 */  lui        $t9, %hi(func_80001CE8)
    /* 8E3F8 8008D7F8 27391CE8 */  addiu      $t9, $t9, %lo(func_80001CE8)
    /* 8E3FC 8008D7FC AD620038 */  sw         $v0, 0x38($t3)
endlabel D_8008D7E0
