.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008BA10, 0x5C

glabel func_8008BA10
    jr $ra
    nop
  .L8008BA48:
    jr $ra
    nop
endlabel func_8008BA10

nonmatching D_8008BA6C, 0x4

glabel D_8008BA6C
    jr $ra
    nop
endlabel D_8008BA6C
