.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008E090, 0xC

glabel func_8008E090
    jr $ra
    nop
endlabel func_8008E090

nonmatching D_8008E09C, 0x48

glabel D_8008E09C
    jr $ra
    nop
  .L8008E0CC:
    jr $ra
    nop
endlabel D_8008E09C

nonmatching D_8008E0E4, 0x8C

glabel D_8008E0E4
    jr $ra
    nop
endlabel D_8008E0E4
