.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching .L8008F890, 0xF4

glabel .L8008F890
    /* 90490 8008F890 10810009 */  beq        $a0, $at, .L8008F8B8
    /* 90494 8008F894 3C06801D */   lui       $a2, %hi(D_801C82C0)
    /* 90498 8008F898 24010005 */  addiu      $at, $zero, 0x5
    /* 9049C 8008F89C 1081000B */  beq        $a0, $at, .L8008F8CC
    /* 904A0 8008F8A0 3C06801D */   lui       $a2, %hi(D_801C82C0)
    /* 904A4 8008F8A4 24010006 */  addiu      $at, $zero, 0x6
    /* 904A8 8008F8A8 1081000D */  beq        $a0, $at, .L8008F8E0
    /* 904AC 8008F8AC 3C06801D */   lui       $a2, %hi(D_801C82C0)
    /* 904B0 8008F8B0 10000011 */  b          .L8008F8F8
    /* 904B4 8008F8B4 24010002 */   addiu     $at, $zero, 0x2
  .L8008F8B8:
    /* 904B8 8008F8B8 24C682C0 */  addiu      $a2, $a2, %lo(D_801C82C0)
    /* 904BC 8008F8BC 00071600 */  sll        $v0, $a3, 24
    /* 904C0 8008F8C0 A0C32887 */  sb         $v1, 0x2887($a2)
# PATCHED: # PATCHED: /* 904C4 8008F8C4 100000F3 */  b          D_8008FC94
    nop
    nop
    /* 904C8 8008F8C8 00021603 */   sra       $v0, $v0, 24
  .L8008F8CC:
    /* 904CC 8008F8CC 24C682C0 */  addiu      $a2, $a2, %lo(D_801C82C0)
    /* 904D0 8008F8D0 00071600 */  sll        $v0, $a3, 24
    /* 904D4 8008F8D4 A0C32888 */  sb         $v1, 0x2888($a2)
# PATCHED: # PATCHED: /* 904D8 8008F8D8 100000EE */  b          D_8008FC94
    nop
    nop
    /* 904DC 8008F8DC 00021603 */   sra       $v0, $v0, 24
  .L8008F8E0:
    /* 904E0 8008F8E0 24C682C0 */  addiu      $a2, $a2, %lo(D_801C82C0)
    /* 904E4 8008F8E4 00071600 */  sll        $v0, $a3, 24
    /* 904E8 8008F8E8 A0C32889 */  sb         $v1, 0x2889($a2)
# PATCHED: # PATCHED: /* 904EC 8008F8EC 100000E9 */  b          D_8008FC94
    nop
    nop
    /* 904F0 8008F8F0 00021603 */   sra       $v0, $v0, 24
    /* 904F4 8008F8F4 24010002 */  addiu      $at, $zero, 0x2
  .L8008F8F8:
    /* 904F8 8008F8F8 14810004 */  bne        $a0, $at, .L8008F90C
    /* 904FC 8008F8FC 3C06801D */   lui       $a2, %hi(D_801C82C0)
    /* 90500 8008F900 240E0005 */  addiu      $t6, $zero, 0x5
    /* 90504 8008F904 10000005 */  b          .L8008F91C
    /* 90508 8008F908 AFAE0034 */   sw        $t6, 0x34($sp)
  .L8008F90C:
    /* 9050C 8008F90C 24010003 */  addiu      $at, $zero, 0x3
    /* 90510 8008F910 14810002 */  bne        $a0, $at, .L8008F91C
    /* 90514 8008F914 240F000A */   addiu     $t7, $zero, 0xA
    /* 90518 8008F918 AFAF0034 */  sw         $t7, 0x34($sp)
  .L8008F91C:
    /* 9051C 8008F91C 24C682C0 */  addiu      $a2, $a2, %lo(D_801C82C0)
    /* 90520 8008F920 80D82885 */  lb         $t8, 0x2885($a2)
    /* 90524 8008F924 8FB90034 */  lw         $t9, 0x34($sp)
    /* 90528 8008F928 24040187 */  addiu      $a0, $zero, 0x187
    /* 9052C 8008F92C 03191021 */  addu       $v0, $t8, $t9
    /* 90530 8008F930 28410064 */  slti       $at, $v0, 0x64
    /* 90534 8008F934 10200003 */  beqz       $at, .L8008F944
    /* 90538 8008F938 3C198000 */   lui       $t9, %hi(func_80002560)
    /* 9053C 8008F93C 10000003 */  b          .L8008F94C
    /* 90540 8008F940 A0C22885 */   sb        $v0, 0x2885($a2)
  .L8008F944:
    /* 90544 8008F944 24080063 */  addiu      $t0, $zero, 0x63
    /* 90548 8008F948 A0C82885 */  sb         $t0, 0x2885($a2)
  .L8008F94C:
    /* 9054C 8008F94C 27392560 */  addiu      $t9, $t9, %lo(func_80002560)
    /* 90550 8008F950 0320F809 */  jalr       $t9
    /* 90554 8008F954 AFA70044 */   sw        $a3, 0x44($sp)
    /* 90558 8008F958 10400003 */  beqz       $v0, .L8008F968
    /* 9055C 8008F95C 8FA70044 */   lw        $a3, 0x44($sp)
    /* 90560 8008F960 10000002 */  b          .L8008F96C
    /* 90564 8008F964 8C430070 */   lw        $v1, 0x70($v0)
  .L8008F968:
    /* 90568 8008F968 00001825 */  or         $v1, $zero, $zero
  .L8008F96C:
    /* 9056C 8008F96C 90690000 */  lbu        $t1, 0x0($v1)
    /* 90570 8008F970 00071600 */  sll        $v0, $a3, 24
    /* 90574 8008F974 00021603 */  sra        $v0, $v0, 24
    /* 90578 8008F978 352A0008 */  ori        $t2, $t1, 0x8
# PATCHED: # PATCHED: /* 9057C 8008F97C 100000C5 */  b          D_8008FC94
    nop
    nop
    /* 90580 8008F980 A06A0000 */   sb        $t2, 0x0($v1)
endlabel .L8008F890

nonmatching D_8008F984, 0x5C

glabel D_8008F984
    /* 90584 8008F984 28810007 */  slti       $at, $a0, 0x7
# PATCHED: # PATCHED: /* 90588 8008F988 14200025 */  bnez       $at, D_8008FA20
    nop
    nop
    /* 9058C 8008F98C 2881000D */   slti      $at, $a0, 0xD
# PATCHED: # PATCHED: /* 90590 8008F990 10200023 */  beqz       $at, D_8008FA20
    nop
    nop
    /* 90594 8008F994 2401000C */   addiu     $at, $zero, 0xC
# PATCHED: # PATCHED: /* 90598 8008F998 1481001E */  bne        $a0, $at, D_8008FA14
    nop
    nop
    /* 9059C 8008F99C 3C06801D */   lui       $a2, %hi(D_801C82C0)
    /* 905A0 8008F9A0 24C682C0 */  addiu      $a2, $a2, %lo(D_801C82C0)
    /* 905A4 8008F9A4 84C32B62 */  lh         $v1, 0x2B62($a2)
    /* 905A8 8008F9A8 3C198007 */  lui        $t9, %hi(func_8006E0F0)
    /* 905AC 8008F9AC 2739E0F0 */  addiu      $t9, $t9, %lo(func_8006E0F0)
    /* 905B0 8008F9B0 28610002 */  slti       $at, $v1, 0x2
# PATCHED: # PATCHED: /* 905B4 8008F9B4 10200012 */  beqz       $at, D_8008FA00
    nop
    nop
    /* 905B8 8008F9B8 24650001 */   addiu     $a1, $v1, 0x1
    /* 905BC 8008F9BC 8CC42960 */  lw         $a0, 0x2960($a2)
    /* 905C0 8008F9C0 30A500FF */  andi       $a1, $a1, 0xFF
    /* 905C4 8008F9C4 0320F809 */  jalr       $t9
    /* 905C8 8008F9C8 AFA70044 */   sw        $a3, 0x44($sp)
    /* 905CC 8008F9CC 3C038001 */  lui        $v1, %hi(func_800166F8)
    /* 905D0 8008F9D0 246366F8 */  addiu      $v1, $v1, %lo(func_800166F8)
    /* 905D4 8008F9D4 AFA3001C */  sw         $v1, 0x1C($sp)
    /* 905D8 8008F9D8 0060F809 */  jalr       $v1
    /* 905DC 8008F9DC 240401C3 */   addiu     $a0, $zero, 0x1C3
endlabel D_8008F984
