.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_8008B040, 0x364

glabel func_8008B040
    jr $ra
    nop
  .L8008B340:
    jr $ra
    nop
endlabel func_8008B040

nonmatching func_8008B3A4, 0x9C

glabel func_8008B3A4
    jr $ra
    nop
  .L8008B3DC:
    jr $ra
    nop
  .L8008B400:
    jr $ra
    nop
  .L8008B434:
    jr $ra
    nop
  .L8008B438:
    jr $ra
    nop
endlabel func_8008B3A4
