.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.39.3 */

nonmatching func_80081D00, 0x80

glabel func_80081D00
    jr $ra
    nop
  .L80081D24:
    jr $ra
    nop
  .L80081D40:
    jr $ra
    nop
  .L80081D5C:
    jr $ra
    nop
  .L80081D74:
    jr $ra
    nop
endlabel func_80081D00
