#!/usr/bin/env python3
"""
Generate stub implementations for stubbed functions.

Reads the stubs list from recomp.toml and generates empty C function
implementations for any stubbed functions that are called but not defined.
"""

import re
import sys
from pathlib import Path

def get_stubs_from_toml(toml_path: Path) -> set[str]:
    """Extract stub function names from recomp.toml."""
    with open(toml_path, 'r') as f:
        content = f.read()

    # Find the stubs array
    match = re.search(r'stubs\s*=\s*\[(.*?)\]', content, re.DOTALL)
    if not match:
        return set()

    stubs_content = match.group(1)
    stubs = set(re.findall(r'"([^"]+)"', stubs_content))
    return stubs

def get_defined_functions(funcs_dir: Path) -> set[str]:
    """Get all function names that are defined in the C files."""
    defined = set()

    # Check the header for declarations
    header_path = funcs_dir / "funcs.h"
    if header_path.exists():
        with open(header_path, 'r') as f:
            content = f.read()
        # Match function declarations
        defined.update(re.findall(r'^void\s+(\w+)\s*\(', content, re.MULTILINE))

    return defined

def generate_stubs(stubs: set[str], defined: set[str], output_path: Path):
    """Generate stub implementations for undefined stubbed functions."""
    undefined = stubs - defined

    if not undefined:
        print("All stubbed functions are already defined")
        return 0

    with open(output_path, 'w') as f:
        f.write('''/**
 * CVLoD Recomp - Stub Implementations
 *
 * Auto-generated by tools/gen_stubs.py
 * Provides empty implementations for stubbed functions.
 */

#include "recomp.h"

''')

        for func_name in sorted(undefined):
            f.write(f'''// Stub: {func_name}
RECOMP_FUNC void {func_name}(uint8_t* rdram, recomp_context* ctx) {{
    // Stubbed function - no implementation
}}

''')

    return len(undefined)

def main():
    project_root = Path(__file__).parent.parent
    toml_path = project_root / "recomp.toml"
    funcs_dir = project_root / "recompiled" / "functions"
    output_path = funcs_dir / "stubs.c"

    if not toml_path.exists():
        print(f"Error: {toml_path} not found")
        return 1

    print("Generating stub implementations...")

    stubs = get_stubs_from_toml(toml_path)
    print(f"Found {len(stubs)} stubs in recomp.toml")

    defined = get_defined_functions(funcs_dir)
    print(f"Found {len(defined)} defined functions")

    count = generate_stubs(stubs, defined, output_path)
    if count:
        print(f"Generated {count} stub implementations in {output_path}")
    else:
        print("No stub implementations needed")

    return 0

if __name__ == "__main__":
    sys.exit(main())
