#!/usr/bin/env python3
"""
Generate function lookup table (funcs.cpp) from funcs.h declarations.

This creates a hash map of function addresses to function pointers,
enabling the LOOKUP_FUNC macro to resolve indirect calls at runtime.
"""

import re
import sys
from pathlib import Path

def parse_funcs_header(header_path: Path) -> list[tuple[str, int]]:
    """Parse funcs.h and extract function names with their addresses."""
    functions = []

    with open(header_path, 'r') as f:
        content = f.read()

    # Match function declarations: void func_XXXXXXXX(...)
    # Also match D_XXXXXXXX and static_N_XXXXXXXX patterns
    pattern = r'^void\s+((?:func_|D_|static_\d+_)([0-9A-Fa-f]{8}))\s*\('

    for line in content.split('\n'):
        match = re.match(pattern, line.strip())
        if match:
            func_name = match.group(1)
            addr_str = match.group(2)
            try:
                addr = int(addr_str, 16)
                functions.append((func_name, addr))
            except ValueError:
                pass

    return functions

def generate_cpp(functions: list[tuple[str, int]], output_path: Path):
    """Generate the C++ source file with the function lookup table."""

    # Sort by address for potential binary search optimization
    functions.sort(key=lambda x: x[1])

    with open(output_path, 'w') as f:
        f.write('''/**
 * CVLoD Recomp - Function Lookup Table
 *
 * Auto-generated by tools/gen_func_table.py
 * Contains mapping from VRAM addresses to function pointers for indirect calls.
 */

#include <cstdint>
#include <unordered_map>
#include "recomp.h"
#include "funcs.h"

// Function lookup table
static std::unordered_map<int32_t, recomp_func_t*> g_function_table;

// Forward declarations for all recompiled functions
''')

        # Write extern declarations
        for func_name, addr in functions:
            f.write(f'extern "C" void {func_name}(uint8_t* rdram, recomp_context* ctx);\n')

        f.write('''
void init_function_table() {
    g_function_table.clear();
    g_function_table.reserve(''' + str(len(functions)) + ''');

''')

        # Write table entries
        for func_name, addr in functions:
            f.write(f'    g_function_table[0x{addr:08X}] = {func_name};\n')

        f.write('''}

recomp_func_t* cvlod_get_function(int32_t vram) {
    auto it = g_function_table.find(vram);
    if (it != g_function_table.end()) {
        return it->second;
    }

    // Function not found - this could be:
    // 1. A stubbed function
    // 2. A function we missed during recompilation
    // 3. An invalid address
    return nullptr;
}
''')

def main():
    project_root = Path(__file__).parent.parent
    header_path = project_root / "recompiled" / "functions" / "funcs.h"
    output_path = project_root / "src" / "funcs.cpp"

    if not header_path.exists():
        print(f"Error: {header_path} not found")
        print("Run N64Recomp first to generate the recompiled code")
        sys.exit(1)

    print(f"Parsing {header_path}...")
    functions = parse_funcs_header(header_path)
    print(f"Found {len(functions)} functions")

    print(f"Generating {output_path}...")
    generate_cpp(functions, output_path)
    print("Done!")

    return 0

if __name__ == "__main__":
    sys.exit(main())
