.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_800A2530

dlabel D_800A2530
    /* A3130 800A2530 00000000 */ .word 0x00000000
    /* A3134 800A2534 5487FFFA */ .word 0x5487FFFA
    /* A3138 800A2538 90820000 */ .word 0x90820000
    /* A313C 800A253C 03E00008 */ .word 0x03E00008
enddlabel D_800A2530
