.include "macro.inc"

.section .data, "wa"

/* Generated by spimdisasm 1.39.3 */

nonmatching D_800A21C0

dlabel D_800A21C0
    /* A2DC0 800A21C0 03E00008 */ .word 0x03E00008
    /* A2DC4 800A21C4 00000000 */ .word 0x00000000
    /* A2DC8 800A21C8 00000000 */ .word 0x00000000
    /* A2DCC 800A21CC 00000000 */ .word 0x00000000
enddlabel D_800A21C0
